ahampriyanshu/algo_ds_101

Algorithms/Search_Algorithms/Linear_Search/linear_search.java

added => linear_search => algorithm => java

---

Algorithms/Search_Algorithms/Linear_Search/Linear_Search.cpp

Linear Search added.

---

Algorithms/Search_Algorithms/Binary_Search/binary_search.java

added => binary_search => algorithm => java

---

Algorithms/Binary Search/binarysearch.java
Algorithms/Binary Search/binarysearch.py

For java And Python programmers

Added Binary Search Algorithm in java and python

---

Algorithms/Sort_Algorithms/Bubble_Sort/bubbleSort.cpp

added => bubble_sort => algo => C++

---

Algorithms/Search_Algorithms/Binary_Search/Binary_search_javascript.js

Added the recursive binary search algorithm js, Please review my pull request

Adding recursive binary search in javascript

---

Data_Structures/Linked_List/Doubly_Linked_List/Java/DoubleLinkedList.java
Data_Structures/Linked_List/Singly_Linked_List/C#/LinkedList.cs
Data_Structures/Linked_List/Singly_Linked_List/Java/LinkedList.java

Add Linked list class in C# and Java and double linked list class in Java, which also can be used as binary tree

Add Linked list class in and double linked list class

---

Abantika20_BubblesortinC

This implements Bubble sort in C

Bubble Sort in C

---

Algorithms/Sort_Algorithms/Merge_Sort/MERGE_SORT.cpp

added => merge_sort => algo => C++

---

Algorithms/Sort_Algorithms/Bubble_Sort/Bubble_Sort.py

Added the Bubble Sort in Python version.
Enjoyed the contibution Process.
Thank you @Singh-Aishwarya  @ahampriyanshu

Created Bubble_Sort.py

---

Algorithms/Sort_Algorithms/Bubble_Sort/bubble_sort.java

added => bubble_sort => algorithm => java

---

Algorithms/Sort_Algorithms/Merge_Sort/MERGE_SORT.java

added => merge_sort => algorithms => Java

---

Data_Structures/Linked_List/Doubly_Linked_List/Double linked List circular with double headers C++/LDLCCED.cbp
Data_Structures/Linked_List/Doubly_Linked_List/Double linked List circular with double headers C++/LDLCCED.layout
Data_Structures/Linked_List/Doubly_Linked_List/Double linked List circular with double headers C++/dllist.cpp
Data_Structures/Linked_List/Doubly_Linked_List/Double linked List circular with double headers C++/dllist.h
Data_Structures/Linked_List/Doubly_Linked_List/Double linked List circular with double headers C++/dlnode.cpp
Data_Structures/Linked_List/Doubly_Linked_List/Double linked List circular with double headers C++/dlnode.h
Data_Structures/Linked_List/Doubly_Linked_List/Double linked List circular with double headers C++/listexception.h
Data_Structures/Linked_List/Doubly_Linked_List/Double linked List circular with double headers C++/main.cpp
Data_Structures/Linked_List/Doubly_Linked_List/Double linked List circular with double headers C++/nodeexception.h
Data_Structures/Linked_List/Doubly_Linked_List/simple linked list circular without header/LSLCSE.cbp
Data_Structures/Linked_List/Doubly_Linked_List/simple linked list circular without header/LSLCSE.layout
Data_Structures/Linked_List/Doubly_Linked_List/simple linked list circular without header/main.cpp
Data_Structures/Linked_List/Doubly_Linked_List/simple linked list circular without header/sllist.cpp
Data_Structures/Linked_List/Doubly_Linked_List/simple linked list circular without header/sllist.h
Data_Structures/Linked_List/Doubly_Linked_List/simple linked list circular without header/slnode.cpp
Data_Structures/Linked_List/Doubly_Linked_List/simple linked list circular without header/slnode.h

#39
I create two list, one simple linked list circular without header and a Double linked List circular with double headers in C++, both are projects so i hope u can use it
Yep
imlemented both codes

Created two circular linked list, one double and one simple, hope u enjoy it

---

Algorithms/Sort_Algorithms/Bubble_Sort/BubbleSort.js

@ahampriyanshu  I usually do this in leetcode and get the result.
Please let me know if this is good or shall I explore more on how to create a web page to display results. 
Thank You.

Bubble Sort added for JavaScript

---

Algorithms/Search_Algorithms/Binary_Search/binary_search.cpp

added => binary_search => algorithms => C++

---

Data_Structures/Linked_List/Circular_Linked_List/circularLinkedList.js
Data_Structures/Linked_List/Circular_Linked_List/circularLinkedList.py

(#39 )
(Yes i have read https://github.com/ahampriyanshu/algo_ds_101/blob/master/CONTRIBUTING.md )
###Submission Title
Circular Linked List
###Submission Type
Data Structure
Submission Description
I implement circular linked list in python javascript language using my own node class and provide isEmpty(), addToTail(), and printAll(), and etc. method for circular linked list

circular linked list in python and javascript

---

Algorithms/Binary Search/binarySearch.js
Data_Structures/Linked_List/Circular_Linked_List/java/CircularLinkedList.java
Data_Structures/Tree/Binary_Search_Tree/java/BinarySearchTree.java

- Binary Search in Javascript
- Circular Linked List in Java
- Binary Search Tree in Java
Yes
I create 3 files which are 
1) Algorithms/Binary Search/binarySearch.js
2) Data_Structures/Linked_List/Circular_Linked_List/java/CircularLinkedList.java
3) Data_Structures/Tree/Binary_Search_Tree/java/BinarySearchTree.java

Add Binary Search in Javascript, Circular Linked List & Binary Search Tree in Java

---

Data_Structures/Tree/Binary_Search_Tree/Binary_Search_Tree.py

Binary Search Tree in Python3
Yes, I have.
I created a python file which contains an implementation of the Binary Search Tree, with 3 forms of traversal operations as well. 
The file is located at algo_ds_101\Data_Structures\Tree\Binary_Search_Tree\Binary_Search_Tree.py

Binary Search Tree Implemented

---

Algorithms/Sorting_Algorithms/Bitonic_sort.c

Added bitonic sort

---

Algorithms/Graph_Algorithms/Bellman_Ford/README.md
Algorithms/Graph_Algorithms/Bellman_Ford/bellmanFord.cpp

#83
Yes
[bellmanFord.cpp](https://github.com/ahampriyanshu/algo_ds_101/files/5315977/bellmanFord.cpp)
bellmanFord.cpp

Bellman–Ford

---

Algorithms/Graph_Algorithms/BFS/BFS.cpp

#21
Yes/No
name_of_file.extension

Added C++ source file of Bfs code in BFS folder

---

Algorithms/Graph_Algorithms/Floyd_Warshall/Floyd_Warshall.java

#84 
Yes
Floyd_Warshall.java
- [X ] I've read the contribution guidelines.
- [X ] I've checked the issue list before deciding what to submit.

Added Floyd_Warshall.java

---

Algorithms/Sorting_Algorithms/Brick_Sort.c

Added Brick sort 

---

Algorithms/Sorting_Algorithms/Merge_Sort/MERGE_SORT.js

added merge_sort javascript version

---

Algorithms/Sorting_Algorithms/Insertion_Sort/InsertionSort.java

#90 
Yes
InsertionSort.java
- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.

Added Insertion Sort in java

---

Algorithms/Dynamic_Programming/Edit_Distance/Edit_distance.cpp

added edit distance problem

---

Algorithms/Sorting_Algorithms/brickSort.py

#117
Yes
brickSort.py
- [*] I've checked the issue list before deciding what to submit.

Brick Sort

---

Data_Structures/Stacks/README.md
Data_Structures/Stacks/StackDynamic.java
Data_Structures/Stacks/StackStatic.java

#74
Yes
Data_Structures/Stacks/README.md
Data_Structures/Stacks/StackDynamic.java
Data_Structures/Stacks/StackStatic.java

Implementation Dynamic Stack and Static Stack.

---

Data_Structures/Arrays/Array_in_C.c
Data_Structures/Arrays/README.md

Array in C.

---

Data_Structures/Queues/CPP/Queue.cpp

#73 [Issue](https://github.com/ahampriyanshu/algo_ds_101/issues/73)
Yes
Queue.cpp

Added queue in DS Folder C++

---

Algorithms/Search_Algorithms/Ternary_Search/ternarySearch.cpp

Ternary Search implemented in c++

---

Maths_And_Stats/armstrongnumber.cpp

Armstrong number

---

Algorithms/Graph_Algorithms/Bellman_Ford/BellMan_Ford.py

Created BellmanFord.py

---

Maths_And_Stats/meanOfGivenNumbers.c
Maths_And_Stats/meanOfGivenNumbers.cs
Maths_And_Stats/meanOfGivenNumbers.js

#159 
C/C#/javascript
3
algo_ds_101 => Maths_And_Stats => meanOfGivenNumbers.c , meanOfGivenNumbers.cs , meanOfGivenNumbers.js

added javascript c# and c

---

.github/pull_request_template.md

fibonacci.cpp

---

Maths_And_Stats/sumofNnaturalnums.py

#157 
Yes/No : Yes
sum_ of_n_natural.py
- [ x] I've checked the issue list before deciding what to submit.
Added a python program to calculatate sum of N natural number.

Sumof nnaturalnumber rs py

---

.vscode/launch.json
Algorithms/Sorting_Algorithms/Quick_Sort/QuickSort.py

adding quicksort.py file

---

Algorithms/Dynamic_Programming/LIS/LIS.cpp
Algorithms/Dynamic_Programming/LIS/README.md

LIS in c++ added

---

Maths_And_Stats/Java/SumOfNumber.java

#IssueNumber    157
Java
1
Maths_And_Stats => Java => SumOfNumber.java
- [✓ ] I've read the contribution guidelines.
- [ ✓] I've referred the correct issue number.
- [ ✓] I've fill up this entire template correctly.

Sum of  N Natural Number

---

Maths_And_Stats/series/sumOfn_squared.py

#165 
Python 3
1
Maths_And_Stats => series  => sumOfn_squared.py

Sum of n squared added

---

Maths_And_Stats/Stats/Standard_Deviation.cpp

#177 
C++
1
Maths_And_Stats => Stats => Standard_Deviation.cpp

Adding Standard Deviation in C++

---

README.md

Just a minor spelling error rectified

Corrected spelling error in readme added a new line

---

Maths_And_Stats/Discrete/Ackermann_Peter/README.md

I wrote briefly about topics and a book for dm. I am doing this course in college right now.

Added readme for Discrete Math

---

Algorithms/Search_Algorithms/Jump_Search/jumpSearch.js

#143 
JavaScript
1
Algorithms/Search_Algorithms/Jump_Search/jumpSearch.js

JumpSearch implementation in JavaScript

---

Data_Structures/Linked_List/Circular_Linked_List/C++/Circular_Link_List.cpp

Added Circular Link List in C++

---

Data_Structures/Queues/Python/Queue.py

Queue in Python

---

Algorithms/Sorting_Algorithms/insertion_sort_python(souvick roy)/insertion_sort.py
Algorithms/Sorting_Algorithms/insertion_sort_python(souvick roy)/insertion_sort_output.txt

Insertion sort
#90 
Python
2
Algorithms => Sorting_Algorithms => insertion_sort_python(souvick roy) => insertion_sort.py
Algorithms => Sorting_Algorithms => insertion_sort_python(souvick roy) => insertion_sort_output.txt

Added insertion sort using python

---

Maths_And_Stats/fibonacci  series in Java #167

fibonacci in java #167

---

Algorithms/Sorting_Algorithms/Insertion_Sort/Insertion Sort.cpp

#90 
Yes
Insertion Sort.cpp
- [ yes] I've read the contribution guidelines.
- [ yes ] I've checked the issue list before deciding what to submit.

Added Insertion Sort in Cpp

---

Algorithms/Dynamic_Programming/Longest_Common_Subsequence_of_Two_Sequences.c
Algorithms/Dynamic_Programming/Longest_Common_Subsequence_of_Two_Sequences.cpp

#113 
Yes
Longest_Common_Subsequence_of_Two_Sequences.cpp

added Longest Common Subsequence of Two Sequences

---

Maths_And_Stats/Series/Sum_Of_n^2.py

#165 
Python
1
Maths_And_Stats => Series => Sum_Of_n^2.py
example :

I have given soln for sum of n^2 in python for hactoberfest

---

Maths_And_Stats/mean.cpp

#159 
C++
1
mean.cpp
example :
algo_ds_101 => Maths_And_Stats => mean.cpp
Maths_And_Stats/mean.cpp

C++ program calculates the mean of numbers the user inputs

---

armstrongin java

create armstrong number in java

---

Algorithms/Sorting_Algorithms/Merge_Sort/MERGE_SORT.c

#20 
C
1
Algorithms => Sorting_Algorithms => Merge_Sort => MERGE_SORT.cpp

added => merge_sort => algorithms => C

---

Data_Structures/Maps_Hash_Dict/multimap.cpp

Implementation of C++ STL multimap

---

Maths_And_Stats/Algebra/Sieve of Eratosthenes/SieveOfEratosthenes.py

#221 
Python
1
Maths_And_Stats => Algebra => Sieve of Eratosthenes => SieveOfEratosthenes.py
example :

Fastest method for Prime number

---

Algorithms/Sorting_Algorithms/BrickSort.js

Created BrickSort.js

---

Data_Structures/Segment Tree/Range-Sum Query.cpp
Data_Structures/Segment Tree/Range-XOR Query.cpp

#134 
Yes
Range-Sum Query.cpp
Range-XOR Query.cpp
-  I've read the contribution guidelines.
-  I've checked the issue list before deciding what to submit.

Adding new Data Structure

---

Algorithms/merging intervals/#999 merging_intervals.py

#229  Closed
Python
1
Algorithms => merging_intervals => #999 merging_intervals.py
example :
Algorithms => merging_intervals => #999 merging_intervals.py

Added Solution for Merging intervals

---

Algorithms/Dynamic_Programming/knapsack_problem_0_1.py

Added 0-1 Knapsack in python

---

Algorithms/Dynamic_Programming/0-1 Knapsack Problem/knapsack_problem_0_1.cpp
Maths_And_Stats/Armstrong Number/armstrongnumber.js

#214 #148 
C++
2
Algorithms => Dynamic_Programming => 0-1 Knapsack Problem =>knapsack_problem_0_1.cpp
+1 more

0-1 Knapsack problem

---

Maths_And_Stats/Stats/Median.js

#174 
Javascript
1
Algorithms =>Maths_And_Stats =>Stats => Median.js

Add Median Algorithm in Javascript

---

Maths_And_Stats/Series/sumOfNSquare.js

#165 
JavaScript
1
Maths_And_Stats => series => sumOfNSquare.js
- [True] I've read the contribution guidelines.
- [True] I've referred the correct issue number.
- [True] I've fill up this entire template correctly.

JavaScript program for sum of n square

---

Maths_And_Stats/Algebra/Prime_Factorization/PrimeFactorisation.cpp

#263 
C++
1
Maths_And_Stats => Algebra => Prime_Factorization => PrimeFactorisation.cpp => 
example :

Add Maths and stats => Algebra => Prime factorization

---

Maths_And_Stats/Algebra/Factorial/factorial.py

#279 
Python
1
Maths_And_Stats => Algebra => Factorial => factorial.py

Added => Maths_And_Stats => Algebra => Factorial => Python

---

Maths_And_Stats/Algebra/Factorial/factorial.cpp
Maths_And_Stats/series/sumofNnaturalnums.cs

#279 #173 
C++ and C#
2
Maths_And_Stats => Algebra => Factorial => factorial.cpp
+1 more

Added the code for factorial in C++

---

Maths_And_Stats/series/sumofNnaturalnums.cs

#157
C#
1
Maths_And_Stats => series => sumofNnatualnums.cs
- [1 ] I've read the contribution guidelines.
- [1] I've referred the correct issue number.
- [1] I've fill up this entire template correctly.

Added sum of N natural numbers in C#

---

Maths_And_Stats/Algebra/Factorial/factorial.c

#279
C
1
Maths_And_Stats => Algebra => Factorial => factorial.c

Added Factorial program in C

---

Maths_And_Stats/Algorithm/Prime_Facrotisation/Prime_Factorisation.cpp

#263 
C++
1
Maths->Algorithm->PrimeFactorisation->PrimeFactorisation.cpp

Prime Factorisation

---

Algorithms/Sorting_Algorithms/Quick_Sort/quickSort.py

#91 
Python
1
Algorithms => Sorting_Algorithms => Quick_Sort => quickSort.py

Added Quick Sort in Python

---

Maths_And_Stats/Algebra/Factorial/Factorial.java
Maths_And_Stats/Algebra/Factorial/factorial.c
Maths_And_Stats/Algebra/Factorial/factorial.js

#279
C//Java/Javascript
3
Maths_And_Stats => Algebra => Factorial => factorial.c
Maths_And_Stats => Algebra => Factorial => Factorial.java
Maths_And_Stats => Algebra => Factorial => factorial.js

Added Factorial programs in C, Java, and Javascript

---

Algorithms/Search_Algorithms/Binary_Search/binarySearch.js

#188 
Swift
1
Algorithm => Sort_Algorithm => Insertion_Sort => Insertion_Sort.swift

Added Insertion Sort Swift Implementation 

---

Algorithms/Search_Algorithms/Jump_Search/jumpSearch.cs

#143 
C#
1
Algorithms/Search_Algorithms/Jump_Search/jumpSearch.cs

JumpSearch implementation in C#

---

Algorithms/String_Algorithms/anagram c#.cs

#232 
C#
1
Algorithms => String_Algorithms =>anagram c#.cs

Added anagram c#

---

Maths_And_Stats/Algebra/GCD/GCD.cs
Maths_And_Stats/Algebra/Prime_Factorization/Prime_Factorization.cs

#250 #263 
C#
2
Maths_And_Stats => Algebra => GCD => GCD.cpp
Maths_And_Stats => Algebra => Prime_Factorization => Prime_Factorization.cs
[ 1] I've read the contribution guidelines.
[ 1] I've referred the correct issue number.
[ 1] I've fill up this entire template correctly.

Added GCD in C# and Prime Factorization in C#

---

Maths_And_Stats/Number_Theory/Armstrong_Number/Python/armstrong.py

#148 
Python
1
Maths_And_Stats => Number_Theory => Armstrong_Number => Python => Armstrong.py
example :

Added Armstrong Number in python

---

Maths_And_Stats/Algebra/Factorial/factorial.rb

#279
Ruby
1
Maths_And_Stats => Algebra => Factorial => factorial.rb

Added Factorial Program in Ruby

---

Data_Structures/Queues/queue.c

#73 
C
1
algo_ds_101 =>  Data_Structures => Queues => queue.c
example :

Add queue.c

---

Maths_And_Stats/Algebra/GCD/swift/EuclidGCD.swift

#250
Swift
1.
Maths_And_Stats => Algebra => GCD =>swift => EuclidGCD.swift
example :

implement Euclid GCD algo in Swift as part of Hacktoberfest

---

STL/array_swap_using_STL(souvick roy)/array_STL_Swap.txt
STL/array_swap_using_STL(souvick roy)/array_STL_swap.cpp

#77
C++
2
STL => array_swap_using_STL(souvick roy) => array_STL_swap.cpp
STL => array_swap_using_STL(souvick roy) => array_STL_Swap.txt
- [#] I've read the contribution guidelines.
- [#] I've referred the correct issue number.
- [#] I've fill up this entire template correctly.

Added array swap using C++ STL

---

Algorithms/Dynamic_Programming/Golomb_Sequence/Golomb.cpp

#205 
C++
1
Algorithms => Dynamic Programming => Golomb_Sequence => Golomb.cpp

Added Golomb Sequence in C++

---

Maths_And_Stats/Algebra/GCD/GCD.php

#250 
php
1
Maths_And_Stats => Algebra => GCD => GCD.php
example :

GCD in php

---

Algorithms/Sorting_Algorithms/Radix_Sort/RadixSort.py

#136 
Python
1
Algorithms => Sorting_Algorithms => Radix_Sort => RadixSort.py

Added Radix Sort in Python

---

Maths_And_Stats/Algebra/Factorial/factorial.cs

#279
C#
1
Maths_And_Stats => Algebra => Factorial => factorial.cs

Added Factorial Program in C#

---

Maths_And_Stats/Algebra/Prime_Factorization/prime_factorization.java

#263 
Java
1
Maths_And_Stats => Algebra => Prime_Factorization => prime_factorization.java

added prime factorization in java

---

Data_Structures/Queues/CPP/queue_op.cpp

#80 
C++
1
example :
Data_Structures => Queues => CPP => queue_op.cpp

STL queue operations

---

Algorithms/Graph_Algorithms/DFS/dfs.js

#82
Javascript
1
algo_ds_101 => Algorithms => Graph_Algorithms => DFS => dfs.js

added dfs graph algorithm javascript

---

Algorithms/Dynamic_Programming/0-1 Knapsack Problem/knapsackProblem.java
Maths_And_Stats/Statistics/Standard_Deviation/Standard_Deviation.c

added Standard_Deviation in C
#177 #214 
C and Java
2
Maths_And_Stats=> Statistics=> Standard_Deviation=> Standard_Deviation.c
example :

Added =>Maths_And_Stats=>Statistics=>Standard_Deviation

---

Algorithms/Graph_Algorithms/Kruskal's_MST/KruskalMST.c

C - Kruskal'sMST

---

Maths_And_Stats/Series/Sum_of_n.c

C program added to find the sum of N natural numbers

---

Algorithms/Sorting_Algorithms/Insertion_Sort/insertion_sort.d.ts

#90 
Yes
name_of_file.extension

adding insertion sort in typescript

---

Algorithms/Graph_Algorithms/Dijkstra/Dijkstra.cpp

#257 
C++
1
Algorithm => Graph_Algorithm => Dijkstra => Dijkstra.cpp
example :

Dijkstra's Algorithm implementation in C++

---

Algorithms/Search_Algorithms/Jump_Search/jumpSearch.go

#143 
Golang
1
Algorithms/Search_Algorithms/Jump_Search/jumpSearch.go

JumpSearch implementation in Golang

---

Algorithms/Search_Algorithms/Jump_Search/jumpSearch.ts

#143 
TypeScript
1
Algorithms/Search_Algorithms/Jump_Search/jumpSearch.ts

JumpSearch implementation in TypeScript

---

Algorithms/Search_Algorithms/Jump_Search/jump_search.py
Maths_And_Stats/perfec_numper.py

#143 #151 
Yes
jump_search.py
perfect_number.py

Added jump search implementation in python

---

Algorithms/Search_Algorithms/Binary_Search/binary_search.cpp

made the binary search modular

---

Algorithms/Sorting_Algorithms/Quick_Sort/QuickSort.js

#91 
Yes
Algorithms/Sorting_Algorithms/Quick_Sort/QuickSort.js

Quicksort javascript

---

Maths_And_Stats/Algebra/LCM/LCM.java

LCM in Java

---

Maths_And_Stats/Algebra/LCM/LCM.py

#301 
Python
1
Maths_And_Stats => Algebra => LCM => LCM.py

Added=>Math and Stats=>Algebra=>LCM=>Python

---

Algorithms/Sorting_Algorithms/Heap_Sort/README.md
Algorithms/Sorting_Algorithms/Heap_Sort/heap-sort.py

Heap Sort in Python added

---

Algorithms/Search_Algorithms/Linear_Search/LinearSearch.js

Hello,
I'm adding Linear Search in JavaScript.

Added Linear Search in Javascript.

---

Algorithms/Dynamic_Programming/Fibonacci_Series/fibonacci.go

#120 
Golang
1
Algorithm => Dynamic_Programming => Fibonacci_Series => fibonacci.go

Added => Algo => Dynamic_Prog => Fibonacci_Series => fibonacci.go

---

Maths_And_Stats/Statistics/Mode/mode.cpp

#161
C++
1
Maths_And_Stats => stats => mode => mode.cpp 
example :

add mode.cpp file

---

Algorithms/Graph_Algorithms/BFS/BFS.go

#81 
GoLang
1.
Algorithm => Graph_Algorithm => BFS =>BFS.go

BFS using Q in Go Lang

---

Maths_And_Stats/Stats/Median.py

#174 
Python
1
Maths_And_Stats => Stats => Median.py
- [True] I've read the contribution guidelines.
- [True] I've referred the correct issue number.
- [True] I've fill up this entire template correctly.

Python program for finding median

---

Algorithms/Search_Algorithms/Binary_Search/binarySearch.js

#165 
Swift
1
Maths_And_Stats => series => Sum_of_n^2.swift

Added Maths_And_Stats => series => Sum_of_n^2.swift

---

.github/workflows/contributors.yml
Algorithms/Graph_Algorithms/Kruskal's_MST/cpp/kruskal.cpp
Algorithms/Graph_Algorithms/Kruskal's_MST/rust/kruskal.rs

#225
Rust and cpp
2
Algorithms => Graph_Algorithms => Kruskal's_MST => rust => kruskal.rs + kruskal.cpp

Added implementation for kruskal's MST algorithm in rust

---

Algorithms/Sorting_Algorithms/Merge_Sort/merge_Sort.rb

merge sory in ruby
#20 
Ruby
1
example :

merge_Sort.rb

---

Maths_And_Stats/Algebra/Matrix_Multipication/MatrixMultipication.py

#314 
Python
1
Maths_and_Stats => Algebra => Matrix_Multiplication => MatrixMultipication.py

Maths_and_Stats => Algebra => Matrix_Multiplication => MatrixMultipication.py

---

Algorithms/Sorting_Algorithms/Bucket_Sort/BucketSort.py
Algorithms/Sorting_Algorithms/Insertion_Sort/InsertionSort.py
Algorithms/Sorting_Algorithms/Selection_Sort/SelectionSort.py

#90 #89
Python
3
Algorithms/Sorting_Algorithms/Insertion_Sort/InsertionSort.py
Algorithms/Sorting_Algorithms/Bucket_Sort/BucketSort.py 
Algorithms/Sorting_Algorithms/Selection_Sort/SelectionSort.py

Added  Sorting Algorithms 

---

Maths_And_Stats/Algebra/GCD/GCD.rb

#250 
ruby
1
Added => Maths_And_Stats => Algebra => GCD => GCD.rb

Added => Maths_And_Stats => Algebra => GCD => ruby

---

Perfect_Number_ c++

Maths_And_Stats/Perfect_Number.cpp

---

Maths_And_Stats/Algebra/Geometric_Progression/GeometricProgression.cs

#307 
C#
1
Maths_And_Stats => Algebra => Geometric_Progression => GeometricProgression.cs

added Geometric Progression.cs (C#)

---

Maths_And_Stats/Algebra/Geometric_Progression/GeometricProgression.java
Maths_And_Stats/Algebra/Geometric_Progression/JavaImplementation.java

#307 
Java
1
Maths_And_Stats => Algebra => Geometric_Progression => GeometricProgression.java
- [Yes] I've read the contribution guidelines.
- [Yes] I've referred the correct issue number.
- [Yes] I've fill up this entire template correctly.

Adding Geometric progression in java

---

Algorithms/Sorting_Algorithms/Binary_Insertion_Sort/Binary_Insertion_Sort.py

#188 
Python
1
Algorithms => Sorting_Algorithms => Binary_Insertion_Sort => Binary_Insertion_Sort.py

add binary insertion sort in python

---

Maths_And_Stats/Algebra/Perfect Number.cpp

#151 
C++.
1
Maths_And_Stats => Alzebra =>Perfect Number.cpp
example :

Create Perfect Number.cpp

---

Algorithms/Sorting_Algorithms/Radix_Sort/radixsort.cpp

#136 
C++
1
Algorithm => Sort_Algorithm => radixsort.cpp
example :
- [yes ] I've read the contribution guidelines.
- [ yes] I've referred the correct issue number.
- [ yes] I've fill up this entire template correctly.

Radix sort in CPP

---

Maths_And_Stats/Statistics/Standard_Deviation/Standard_Deviation.swift

#177 
Swift
1
Maths_And_Stats => Statistics => Standard_Deviation => Standard_Deviation.swift
example :
[ ] I've read the contribution guidelines.
[ ] I've referred the correct issue number.
[ ] I've fill up this entire template correctly.

Add Standard Deviation calcutaion in Swift as part of Hacktoberfest

---

Algorithms/String_Algorithms/anagram.c
Algorithms/String_Algorithms/anagram.java
Maths_And_Stats/Statistics/Standard_Deviation/Standard_Deviation.py

#232 , #177 
C, Java, Python
3
Algorithms => String_Algorithms => anagram.c, anagram.java
Maths_And_Stats => Stats => Standard_Deviation.extension => Standard_Deviation.py

added Anagram code in c language. Issue #232

---

Maths_And_Stats/Algebra/Geometric_Progression/Geometric Progression.py

#307
Python
1
Maths_And_Stats=> Algebra  => Geometric_Progression => Geometric_Progression.py
example :

Geometric Progression in python

---

Maths_And_Stats/Perfect_Number/perfectnumber.php

#151 
php
1
algo_ds_101\Maths_And_Stats\Perfect_Number\perfectnumber.php

added perfect number in php

---

Algorithms/Sorting_Algorithms/Quick_Sort/Quick_Sort.go

#91
Go
1
Algorithms => Sorting_Algorithms => Quick_Sort => Quick_Sort.go

Added => Algo => Quick Sort => Go

---

Algorithms/Sorting_Algorithms/Radix_Sort/RadixSort.java

Radix Sort for java added

---

Algorithms/Sorting_Algorithms/Insertion_Sort/Binary Insertion Sort.c

#188 
C
@ahampriyanshu  just go through this

Added Binary insertion Sort in C

---

sushants2k  #113

Create sushants2k  #113 Longest-Common-Subsequence

---

Algorithms/Search_Algorithms/Trie_Search/Trie Data Structure.cpp

#243 
C++
1
Algorithm => Search_Algorithm => Trie_Search => Trie Data Structure.cpp
example :

Added Trie Data Structure

---

Algorithms/Dynamic_Programming/LCS of 3 strings/lcs_of_3_strings.cpp

#245 
C++
1
Algorithms =>Dynammic_Programming =>LCS of 3 Strings => lcs_of3_strings.cpp

Added code for LCS of 3 Strings

---

Data_Structures/Linked_List/Singly_Linked_List/Python/LinkedList.py

Added Python Program for Linked List
#007
1/2/3/4/...
example :

LinkedList.py

---

Algorithms/Sorting_Algorithms/Binary_Insertion_Sort/Binary_Insertion_Sort.cpp

#188 
C++
1
Algorithm => Sorting_Algorithm => Binary_Insertion_Sort => Binary_Insertion_Sort.cpp

Added Binary Insertion Sort in cpp

---

Algorithms/Dynamic_Programming/Edit_Distance/edit_distance.py

- Implemented in Python
- Calculates the Levenshtein distance (edit distance) using the Wagner-Fischer algorithm.
#118 
Python
1.
Algorithms => Dynamic_Programming => Edit_Distance => edit_distance.py

Add edit distance function in Python

---

Maths_And_Stats/Algebra/Factorial_of_Large_Number/Factorial_of_Large_Number.js

#311 
JavaScript
1
Maths_And_Stats=>Algebra=>Factorial_of_Large_Number=>Factorial_of_Large_Number.js
Thank you
Please review and merge my PR #378 .
Happy Hacktoberfest 🥳

Added=>Maths_And_Stats=>Algebra=>Factorial_of_Large_Number=>JS

---

Maths_And_Stats/Algebra/Sum_of_GP/Sum_Of_GP.cpp

#308 
C++
1
Maths_And_Stat => Algebra => Sum Of GP => Sum_Of_GP.cpp

Added => Maths_And_Stat =>Algebra =>Sum Of GP

---

Algorithms/Sorting_Algorithms/Radix_Sort/radixSort.php

#136
PHP
1
Algorithm => Sorting_Algorithms => Radix_Sort => radixSort.php

Updated RadixSort.php

---

Algorithms/Graph_Algorithms/Dijkstra/Dijikstra.java

#257 
Java
1
Algorithm => Graph_Alogoithm => Dijikstra => Dijikstra.java

Added => Algorithm => Graph_Alogoithm => Dijikstra => Dijikstra.java

---

Maths_And_Stats/Series/sum_of_n_natural_no.cpp

add sum of n natural numbers in cpp

---

Algorithms/Sorting_Algorithms/Bucket_Sort/bucketsort.rb
Maths_And_Stats/Algebra/GCD/gcd.java
Maths_And_Stats/Algebra/Prime_Factorization/prime.cpp
Maths_And_Stats/GCD/gcd.java
Maths_And_Stats/PRIME/prime.cpp

#250  #263 #365 
Java, CPP, Ruby
3
Maths_And_Stats/Algebra/GCD/gcd.java
Maths_And_Stats/Algebra/Prime_Factorization/prime.cpp
Algorithms/Sorting_Algorithms/Bucket_Sort/bucketsort.rb
- I've read the contribution guidelines.
- I've referred the correct issue number.
-  I've fill up this entire template correctly.

GCD IN JAVA AND PRIME FACTORIZATION

---

Data_Structures/Segment Tree/Segment_Tree.c

#134
C/C++
1
Data_Structures/Segment Tree/Segment_Tree.c

Added implementation for Segment Tree

---

Data_Structures/Queues/QueueUsingArray.java

#007
Java
1 file added
main folder => Queue => QueueUsingArray.java
example :

Created QueueUsingArray.java

---

Algorithms/Dynamic_Programming/Target_Sum/Target_Sum.py

#356 
Python3
1
Algorithm => Dynamic_Programming => Target_Sum => Target_Sum.py

created Target_Sum in python3

---

Algorithm/Dynamic_Programming/0-1 knapsack problem/knapsack_problem_0_1.c

#214 
C
1
Algorithms => Dynamic_programming => 0-1 knapsack problem => knapsack_problem_0_1.c
example :

Added=>Algo=>0-1 knapsack problem=>c

---

Maths_And_Stats/Geometry/Clock_Angle/clock_angle.py

- Returns the smallest angle between the hour and minute hand
- Assumes 12 hour clock format
- Raises ValueError if not 12 hour clock format
#384
Python
1.
Maths_And_Stats => Geometry => Clock_Angle => clock_angle.py

Clock Angle Problem

---

.github/workflows/contributors.yml
Maths_And_Stats/Statistics/Standard_Deviation/Standard_Deviation.c

#214 
Java
1
Algorithms=> Dynamic_Programming=> 0-1 Knapsack Problem=> 
example :

Algorithms=> Dynamic_Programming=> 0-1 Knapsack Problem=>0-1 Knapsack Problem.java 

---

Maths_And_Stats/Geometry/Pythagorean_theorem/Pythagorean_theorem.cpp

#413 
C++
1
Math_and_stats => Geometry => Pythagorean_theorem => Pythagorean_Theorem.cpp
example :

Added Pythagorean_Theorem.cpp

---

Maths_And_Stats/Series/sum of n^3.cpp

#181 
C++
1
Maths_And_Stats => series => sum of n^3.cpp

Create sum of n^3.cpp

---

Maths_And_Stats/Geometry/Vector_Product/Vector_Product.js

#408
Javascript
1
Maths_And_Stats => Geometry => Vector_Product => Vector_Product.js

Added Maths_And_Stats => Geometry => Vector_Product => Vector_Product.js #428

---

Algorithms/Sorting_Algorithms/Selection_Sort/selection sort.cs

#415 
C#
1
algo_ds_101=> Algorithms => Sorting_Algorithms => Selection_Sort => selection sort.cs

Create selection sort.cs

---

Maths_And_Stats/Geometry/Radians_Degrees_Conversion/Radians_Degrees_Conversion.py

#406 
Python
1
Maths_and_stats => Geometry => Radians_Degrees_Conversion => Radians_Degrees_Conversion.py

Added Radians_Degrees_Conversion.py

---

Maths_And_Stats/Geometry/Distance_Formula/Distance_Formula.py

#389
Python
1
Maths_And_Stats => Geometry => Distance_Formula => Distance_Formula.py

Added Maths_And_Stats => Geometry => Distance_Formula => Distance_Formula.py

---

Maths_And_Stats/Algebra/Harmonic_Progression/Harmonic Progression.cpp

#310
C++
1
Maths_And_Stats=> Algebra=> Harmonic_Progression  => Harmonic Progression.cpp
example :

Harmonic Progression in cpp

---

Maths_And_Stats/Geometry/Scalar_Product/Scalar_Product.js

#407
Javascript
1
Maths_And_Stats => Geometry => Scalar_Product => Scalar_Product.js

Added Maths_And_Stats => Geometry => Scalar_Product => Scalar_Product.js #407

---

Maths_And_Stats/Algebra/Sum_of_GP/Sum_of_GP.java

#308
Java
1
Maths_And_Stats => Algebra => Sum_of_GP => Sum_of_GP.java

Added => Maths_And_Stats => Algebra => Sum_of_GP => java

---

Algorithms/Graph_Algorithms/Bellman_Ford/bellman_ford.c

#83 
C
1
Algorithms => Graph_Algorithms => Bellman_Ford => bellman_ford.c

Bellman ford program in c

---

Maths_And_Stats/Series/Relative_Primes/RelativePrimes.c

#454
C
1
Maths_And_Stats/Series/Relative_Primes/RelativePrimes.c

Added Relatives Prime in C language #454

---

CONTRIBUTING.md

#455 
Not applicable
1
CONTRIBUTING.md

Fixed typos and inconsistencies in CONTRIBUTING.md

---

Maths_And_Stats/Series/Relative_Primes/RelativePrimes.java

#454
Java
1
Maths_And_Stats => Series => Relative_Primes => RelativePrimes.java
- [✔ ] I've read the contribution guidelines.
- [✔ ] I've referred the correct issue number.
- [ ✔] I've fill up this entire template correctly.

 Added Relatives Prime in Java language

---

Maths_And_Stats/Geometry/Scalar_Product/Scalar_Product.c
Maths_And_Stats/Geometry/Vector_Product/Vector_Product.c

#407 
#408 
C
2
Maths_And_Stats/Geometry/Scalar_Product/Scalar_Product.c
Maths_And_Stats/Geometry/Vector_Product/Vector_Product.c

Scalar and Vector in C programming language

---

Maths_And_Stats/Algebra/Factorial_of_Large_Number/Factorial_of_Large_Number.cs

#311 
C#
1
Maths_And_Stats => Algebra => Factorial_of_Large_Number => Factorial_of_Large_Number.cs

Added => Maths_And_Stats => Algebra => Factorial_of_Large_Number => C#

---

Algorithms/Graph_Algorithms/Floyd_Warshall/Floyd_Warshall.c
Algorithms/Graph_Algorithms/Floyd_Warshall/Floyd_Warshall.py

#84 
C and Python
2
Floyd_Warshall.c
Floyd_Warshall.py

Floyd Warshall program in c and python

---

Maths_And_Stats/Geometry/Polar_Cartesian_Conversion/Polar_Cartesian_Conversion.java
Maths_And_Stats/Geometry/Polar_Cartesian_Conversion/README.md

#404 
Java
2
Maths_And_Stats => Geometry => Polar_Cartesian_Conversion => Polar_Cartesian_Conversion.java
Maths_And_Stats => Geometry => Polar_Cartesian_Conversion => README.md (added explanation)

added java implementation of polar cartesian conversion

---

Maths_And_Stats/Geometry/Radians_Degrees_Conversion/Radians_Degrees_Conversion.java

#406
Java
1
Maths_And_Stats => Geometry => Radians_Degrees_Conversion => Radians_Degrees_Conversion.java

Added Maths_And_Stats => Geometry => Radians_Degrees_Conversion => Radians_Degrees_Conversion.java #406

---

Maths_And_Stats/Geometry/Manhattan_Distance/manhattan_dist.cpp

#396
C++
1
Maths_And_Stats => Geometry => Manhattan_Distance => manhattan_dist.cpp
example :

add manhattan distance cpp file

---

Algorithms/Search_Algorithms/Binary_Search/binarysearch.php

#506 
PHP
1
Algorithms=>Search_Algorithms=>Binary_Search=> binarysearch.php

binary search in php

---

Maths_And_Stats/Series/Relative_Primes/Relative_Prime.cpp

I modified my previously committed code
#454
C++
1
Maths_And_Stats => Series => Relative_Primes => Relative_Prime.cpp
- [ +] I've read the contribution guidelines.
- [ +] I've referred the correct issue number.
- [+ ] I've fill up this entire template correctly.

Added c++ code for relative prime

---

Algorithms/Graph_Algorithms/DFS/dfs.py

#82 
Python
1
Algorithms => Graph_Algorithms => DFS => dfs.py

added dfs graph algorithm python

---

Maths_And_Stats/Geometry/Distance_Formula/Distance_Formula.java

#389 
Java
1
Maths_And_Stats => Geometry => Distance_Formula => Distance_Formula.java

Added => Maths_And_Stats => Geometry => Distance_Formula => Distance_Formula.java

---

Maths_And_Stats/Geometry/Distance_Formula/Distance_Formula.php

##Assigned Issue Number ?
##389
##Language Opted ?
##PHP
##Number of files added or updated ?
##1
##Name of these files ?
Maths_And_Stats => Geometry => Distance_Formula => Distance_Formula.php

Added => Maths_And_Stats => Geometry => Distance_Formula => Distance_Formula.php

---

Maths_And_Stats/Series/Sum of n3.cpp
Maths_And_Stats/series/Sum of n3.cpp

#181
C++
1
Maths_And_Stats => series => Sum of n3.cpp

#181 Sum of n^3 in C++

---

Maths_And_Stats/Statistics/Standard_Deviation/Standard_Deviation.js

#177 
Javascript
1
Maths_And_Stats => Stats => Standard_Deviation.js

Added Maths_And_Stats => Stats => Standard_Deviation.js

---

Maths_And_Stats/Statistics/Median/Median.java

#174 
Java
1
Maths_And_Stats => Stats => Median => Median.java

Median.java added

---

Maths_And_Stats/series/sum_of_n_natural_numbers.go

#157 
Golang
1
Math_And_Stats => Series => sum_of_n_natural_numbers.go

Added => Math_And_Stats => Series => sum_of_n_natural_numbers.go

---

Maths_And_Stats/Number_Theory/Perfect_Number/Perfect_Number.java

#151 
Java
1
Maths_And_Stats/Number_Theory/Perfect_Number/Perfect_Number.java

Perfect Number in java

---

Algorithms/String_Algorithms/palindrome.go

Signed-off-by: Marvin Javier <mjavier2k@gmail.com>
#449 
Go
1
Algorithms/String_Algorithms/palindrome.go

Add palindrome check in golang

---

Algorithms/Dynamic_Programming/Maximum Achievable coins/Maximum_Achievable_coins.java

#507
java
1
Algorithms/Dynamic_Programming/Maximum Achievable coins/Maximum_Achievable_coins.java
- [ ✔] I've read the contribution guidelines.
- [✔ ] I've referred the correct issue number.
- [ ✔] I've fill up this entire template correctly.

Added Maximum Achievable coins Problem

---

Maths_And_Stats/Algebra/Sum_of_GP/Sum_Of_GP.c

#308
C
1
Math_And_Stats => Algebra => Sum_of_GP => Sum_Of_GP.c

Added=>Maths_And_Stats=>Sum_Of_GP=>C

---

Data_Structures/Arrays/Arr4 right shift.c

right shifting of an array code in c .
basic of ds algo
#007
1/2/3/4/...
example :

Tried Right shifting an array

---

Maths_And_Stats/Algebra/Factorial/factorial.php

The user gives input  and program gives output. Recursive function is used.
#279 
PHP 
1
Maths_And_Stats =>  => Algebra => Factorial => factorial.php
- [+] I've read the contribution guidelines.
- [+] I've referred the correct issue number.
- [+] I've fill up this entire template correctly.

Added factorial.php

---

Algorithms/FibonacciNumbers.java

#120 [here](https://github.com/ahampriyanshu/algo_ds_101/issues/120)
Java
1
Alogorithm=>FibonacciNumbers.java

Added Fibonacci series in java

---

Maths_And_Stats/Algebra/Sieve of Eratosthenes/SieveOfEratosthenes.cpp

#221
C++
1
Maths_And_Stats => Algebra => Sieve of Eratosthenes => SieveOfEratosthenes.cpp

Added Maths_And_Stats => Algebra => Sieve of Eratosthenes => CPP

---

Maths_And_Stats/Algebra/Sieve of Eratosthenes/SieveofEratosthenes.java

Added Java code for finding prime numbers up to a given limit using the Sieve of Eratosthenes approach.
#221
Java
1
Maths_And_Stats => Algebra => Sieve of Eratosthenes => SieveofEratosthenes.java

Added Maths_And_Stats => Algebra => Sieve of Eratosthenes => Java

---

Algorithms/Sorting_Algorithms/Radix_Sort/Radix_Sort.js
Algorithms/Sorting_Algorithms/Radix_Sort/Radix_Sort.rb

#136 
Javascript/Ruby
2
Algorithm => Sorting_Algorithms => Radix_Sort => Radix_Sort.js
Algorithm => Sorting_Algorithms => Radix_Sort => Radix_Sort.rb
example :

Added Algorithm => Sorting_Algorithms => Radix_Sort => Radix_Sort.js

---

Algorithms/Dynamic_Programming/Fibonacci_Series/Fibonacci.php

Added => Algo => Dynamic_Prog => Fibonacci_Series => PHP
#120 
PHP
1
Algo => Dynamic_Prog => Fibonacci_Series => Fibonacci.php

PHP Fibonacci implementation

---

Maths_And_Stats/Algebra/Prime_Factorization/prime_factorization.ts

Assigned Issue Number ?
#263
TypeScript
1
Maths_And_Stats => Algebra => Prime_Factorization => prime_factorization.ts
Checklist

Maths_And_Stats => Algebra => Prime_Factorization => prime_factorization.ts

---

BabesGorBtye_LCM.cpp

Code for calculating LCM

---

Maths_And_Stats/Geometry/Distance_Formula/Distance_Formula.js

#389 
JavaScript
1
Maths_And_Stats => Geometry => Distance_Formula => Distance_Formula.js

Added=>Maths_And_Stats=>Geometry=>Distance_Formula=>JavaScript

---

Maths_And_Stats/Geometry/Distance_Formula/Distance_Formula.c

#389
C
1
Added Maths_And_Stats => Geometry => Distance_Formula => Distance_Formula.c

Added Maths_And_Stats => Geometry => Distance_Formula => Distance_Formula.c

---

Algorithms/Dynamic_Programming/Gauss_Easter_Date/Gauss_Easter_Date.cpp

Algorithm for determining the easter date for a given year
#525 
C++
1
Algorithm => Dynamic Programming => Gauss_Easter_Date => Gauss_Easter_Date.cpp

Added Algorithm => Dynamic Programming => Gauss_Easter_Date => Gauss_Easter_Date.cpp

---

Algorithms/Dynamic_Programming/Gauss_Easter_Date/easterDate.js

#525 
JavaScript
1
Algorithms => Dynamic_Programming => Gauss_Easter_Date => easterDate.js

Added => Algorithms => Dynamic_Programming => Gauss algorithm for Easter date => JS

---

Data_Structures/Stacks/Stack.go

#475 
Go
1
Data_Structures => Stacks => Stack.go
example :

implemented stack data structure in Go

---

Maths_And_Stats/Series/Relative_Primes/RelativePrimes.py

#454 
Python
1
Maths_And_Stats/Series/Relative_Primes/RelativePrimes.py

Added Maths_And_Stats => Series => Relative_Primes => Python

---

Maths_And_Stats/Series/Relative_Primes/Relative_Primes.go

#454 
Go
1
Maths_And_Stats => Series => Relative_Primes => Relative_Primes.go

Added => Math => Relative_Primes

---

Algorithms/Graph_Algorithms/Floyd_Warshall/Floyd_Warshall.cpp

#84 
C++
1
Algorithm => Graph_Algorithms => Floyd Warhsall => CPP
Floyd_Warshall.cpp

Added => Algorithm => Graph_Algorithms => Floyd Warhsall => CPP

---

Algorithms/Graph_Algorithms/Kruskal's_MST/python/KruskalMST.py

Python
1
Algorithm => Graph_Algorithm => Kruskal's_MST => python => KruskalMST.py

Add Kruskal-MST in python

---

Maths_And_Stats/Geometry/Clock_Angle/ClockAngle.cs

#384 
C#
1
Maths_And_Stats => Geometry => Clock_Angle => ClockAngle.cs
example :

Added => Maths_And_Stats => Geometry => Clock_Angle => C#

---

Maths_And_Stats/Geometry/Clock_Angle/Clock_Angle.java

#384 
Java
1
Maths_And_Stats => Geometry => Clock_Angle => Clock_Angle.java

Added => Maths_And_Stats => Geometry => Clock_Angle => Clock_Angle.java

---

Maths_And_Stats/Statistics/Mode/Mode.java

#161 
Java
1
Maths_And_Stats=>Statistics=>Mode=>Mode.java

Added=>Maths_And_Stats=>Statistics=>Mode=>Mode.java

---

Maths_And_Stats/Geometry/Clock_Angle/Clock_Angle.c
Maths_And_Stats/Geometry/Clock_Angle/Clock_Angle.js
Maths_And_Stats/Statistics/Mode/mode.js

#161 
JavaScript
1
Maths_And_Stats=>Statistics=>Mode=>mode.js

Added mode.js

---

Maths_And_Stats/Geometry/Vector_Product/Vector_Product.py

#408 
Python
1
Maths_And_Stats => Geometry => Vector_Product => Vector_Product.py

Added Maths_And_Stats => Geometry => Vector_Product => Vector_Product.py

---

Maths_And_Stats/Geometry/Scalar_Product/Scalar_Product.py

#407
Python
1
Maths_And_Stats => Geometry => Scalar_Product => Scalar_Product.py

Added Maths_And_Stats => Geometry => Scalar_Product => Scalar_Product.py #407

---

Maths_And_Stats/Geometry/Pythagorean_theorem/Pythagorean_theorem.js

#413 
JavaScript
1
Maths_And_Stats => Geometry => Pythagorean_theorem => Pythagorean_theorem.js
example :
- [1 ] I've read the contribution guidelines.
- [1 ] I've referred the correct issue number.
- [ 1] I've fill up this entire template correctly.

added pythagorus theorem javascript

---

Algorithms/Graph_Algorithms/DFS/Depth First Search[DFS].cpp
Maths_And_Stats/Series/Relative_Primes/RelativePrimes.c

Added DFS in C++
C++
1
Algorithms/Graph_Algorithms/DFS/Depth First Search[DFS].cpp

Added DFS in cpp

---

Maths_And_Stats/Algebra/Arithmetic_Progression/Arithmetic_Progression.java

#305 
Java
1
main folder => math_and_stats => algebra => arithmetic_progression => arithmetic_progression.java

Added => Math_and_Stats => Arithmetic Progression => Java

---

Maths_And_Stats/Algebra/GCD/GCD.js

GCD file for javascript added.

Added GCD file in javascript

---

Maths_And_Stats/Discrete/Ackermann_Peter/Python/ackermann.py
Maths_And_Stats/Discrete/README.md

#398
Python
2
Maths_And_Stats => Discrete => Ackermann_Peter=> Python => arckemann.py 
Maths_And_Stats => Discrete => Readme

Add Maths_And_Stats => Discrete => Ackermann_Peter=> Python => arckemann.py 

---

Algorithms/String_Algorithms/anagram.swift

#232 
Swift
1
Algorithm => String_Algorithms => anagram.swift

Added => Algorithm => String_Algorithms => anagram.swift

---

Maths_And_Stats/Algebra/Factorial_of_Large_Number/Factorial_of_Large_Number.php

#311 
php
1
Maths_And_Stats => Algebra => Factorial_of_Large_Number => Factorial_of_Large_Number.php

Maths_And_Stats => Algebra => Factorial_of_Large_Number => php

---

Algorithms/String_Algorithms/palindrome.js

#449 
Javascript
1
Algorithms=> String_Algorithms => Palindrome.js

Added Algorithms=> String_Algorithms => Palindrome.js

---

Maths_And_Stats/Geometry/N_Dimensional_Distance/N_Dimensional_Distance.c

#405
C
1
Maths_And_Stats => Geometry => N_Dimensional_Distance => N_Dimensional_Distance.c

Added N_Dimensional_Distance.c

---

Maths_And_Stats/Calculus/Euler_Approximation/Euler_Approximation.java

#393 
Java
1
Maths_And_Stats => Calculus => Euler_Appromixation => Euler_Approximation.java

Added => Maths_And_Stats => Euler Approximation => JAVA

---

Algorithms/String_Algorithms/isPalindrome.cpp
Algorithms/String_Algorithms/isPalindrome.py

#449 
C++/Python
2
main folder => Algorithms => String_Algorithms => isPalindrome.py
main folder => Algorithms => String_Algorithms => isPalindrome.cpp
example :
- [*] I've referred the correct issue number.
- [*] I've fill up this entire template correctly.

Added Palindrome String in CPP and Python

---

Algorithms/Dynamic_Programming/nqueen.cpp

N-queen program using Backtracking in C++

---

Maths_And_Stats/Geometry/Scalar_Product/scalar_product.cpp

#407
C++
1
Maths_And_Stats => Geometry => Scalar_Product => scalar_product.cpp
example :

add scalar product cpp file

---

Algorithms/Sorting_Algorithms/Heap_Sort/Heap_Sort.js
Maths_And_Stats/Algebra/Matrix_Multipication/Matrix_Multiplication.js

#88 #314 
JavaScript
2
Algorithms => Sorting_Algorithms => Heap_Sort => Heap_sort.js
+1 more
example :

added Heap Sort in javascript

---

Algorithms/Dynamic_Programming/Edit_Distance/Edit_Distance.js

#118 
JavaScript
1
Algorithms=>Dynamic_Programming=>Edit_Distance=>Edit_Distance.js

Added Edit_Distance.js file

---

Algorithms/Dynamic_Programming/Gauss_Easter_Date/easterDate.cpp

#525 
C++
1
Algorithms => Dynamic_Programming => Gauss_Easter_Date => easterDate.cpp

Added => Algorithms => Dynamic_Programming => Gauss_Easter_Date

---

Algorithms/Dynamic_Programming/Gauss_Easter_Date/Gauss_Easter_Date.py

Added the Gauss Easter Algorithm.
#525 
Python
1
Algorithms => Dynamic_Programming => Gauss_Easter_Date => Gauss_Easter_Date.py

Added=>Algo=>DynamicProgramming=>Gauss_Easter_Date

---

Algorithms/Dynamic_Programming/Target_Sum/Target_Sum.c

#356
C
1
Algorithm => Dynamic_Programming =>Target_Sum => Target_Sum.c

Added Target_Sum.c

---

Maths_And_Stats/Algebra/Factorial/factorial.ts

Assigned Issue Number ?
#279
TypeScript
1
Maths_And_Stats => Algebra => Factorial => factorial.ts
Checklist

Maths_And_Stats => Algebra => Factorial => factorial.ts

---

Maths_And_Stats/Geometry/N_Dimensional_Distance/n_dimensional_distance.rb

#405
Ruby
1
Maths_And_Stats => Geometry => N_Dimensional_Distance => n_dimensional_distance.rb

Add n dims distance in Ruby

---

Maths_And_Stats/Geometry/Scalar_Product/scalar_product.rb

#407
Ruby
1
Maths_And_Stats => Geometry => Scalar_Product => scalar_product.rb

Add scalar product calculation in Ruby

---

Algorithms/Dynamic_Programming/Gauss_Easter_Date/CalculateEasterDate.java

#525
Java
1
Algorithms/Dynamic_Programming/Gauss_Easter_Date/CalculateEasterDate.java
example :
Algorithm => Dynamic_Programming => Gauss_Easter_Date => CalculateEasterDate.java

Adding Gauss Easter algorithm in Java

---

Algorithms/Graph_Algorithms/A_star/A_star.cpp

#597 
C++
1.
Algorithm => Graph_algorithms => A_star => A_star.cpp

Add Algo => graph_algos => A_star => A_star.cpp

---

Maths_And_Stats/Algebra/Matrix_Multiplication/MatrixMultiply.java

#314 
Java
1
Maths_And_Stats => Algebra => Matrix_Multiplication => MatrixMultiply.java

Added=>Maths_And_Stats=>Algebra=>Matrix_Multiplication=>MatrixMultiply.java

---

Maths_And_Stats/Statistics/Exponential_Smoothing/Exponential_Smoothing.rb

Created Exponential_Smoothing.rb

---

Algorithms/Sorting_Algorithms/Quick_Select/Quick_Select.js

#568 
JavaScript
1
Algorithms=>Sorting_Algorithms =>Quick_Select=>Quick_Select.js

Added Quick_Select.js

---

Data_Structures/Stacks/stack.rb

#475
Ruby
1
Data_Structures => Stacks => stack.rb

Add stack implementation in Ruby

---

Maths_And_Stats/Algebra/Sum_of_HP/Sum_of_HP.cs

#309
C#
1
Added => Math_And_Stats => Algebra => Sum_of_HP => Sum_of_HP.cs

Added => Math_And_Stats => Algebra => Sum_of_HP => C#

---

Algorithms/Search_Algorithms/Jump_Search/Jump_Search.cpp
Algorithms/Selection_Algorithms/Selection_Algorithms.cpp
Algorithms/Sorting_Algorithms/Tree_Sort/Tree_Sort.c
Maths_And_Stats/Algebra/Quadratic_Formula/Quadratic_Formula.cpp
Maths_And_Stats/Calculus/Leibniz_formula/Leibniz_formula.cpp
Maths_And_Stats/Calculus/Leibniz_formula/algo_ds_101/Maths_And_Stats/Calculus/Leibniz_formula/Leibniz_formula.c
Maths_And_Stats/Calculus/Riemann_Sum/Riemann_Sum.cpp
Maths_And_Stats/Number_Theory/Armstrong_Number/Armstrong_Number.c
Maths_And_Stats/Series/Fibonacci/Fiboncci.py
Maths_And_Stats/Statistics/Median/Median.c

created leibniz formula program in c language.
#391 
C/CPP/Python
9
Maths_And_Stats/Calculus/Leibniz_formula/Leibniz_formula.c
Maths_And_Stats/Calculus/Leibniz_formula/Leibniz_formula.cpp
Maths_And_Stats/Calculus/Riemann_Sum/Riemann_Sum.cpp
Maths_And_Stats/Number_Theory/Armstrong_Number/Armstrong_Number.c
Maths_And_Stats/Statistics/Median/Median.c
Maths_And_Stats/Series/Fibonacci/Fibonacci.py
Algorithms/Sorting_Algorithms/Tree_Sort/Tree_Sort.c
Algorithms/Search_Algorithms/Jump_Search/Jump_Search.cpp
Algorithms/Selection_Algorithms/Selection_Algorithms.cpp

add c version of the program

---

Algorithms/Sorting_Algorithms/Gnome Sort.cpp

Create Gnome Sort.cpp

---

Data_Structures/Queue/queue.js

#494 
JavaScript
1
Data_Structures => Queue => queue.js

Added => Data_Structures => Queue => JS

---

Maths_And_Stats/Geometry/Manhattan_Distance/manhattan_distance.py

#396 
Python
1
Maths_And_Stats => Geometry => Manhattan_Distance => manhattan_distance.py

Added => Maths_And_Stats => Geometry => Manhattan_Distance => Python

---

Maths_And_Stats/Algebra/LCM_GCD.c
Maths_And_Stats/Calculus/Factorial_of_large_number.c
Maths_And_Stats/Matrix_Multiplication.c

Hey There,
I am adding a new component call Matric_multiplication

Adding new matric_Multiplication

---

Maths_And_Stats/Algebra/Sum_of_AP.go

#306 
Golang
1
Maths_And_Stats => Algebra => Sum_of_AP.go

Added Maths_And_Stats => Algebra => Sum_of_AP.go

---

Algorithms/Sorting_Algorithms/Bucket_Sort/BucketSort.js
Maths_And_Stats/Geometry/Manhattan_Distance/ManhattanDistance.js

#396 #365
JavaScript
2
Maths_And_Stats => Geometry => Manhattan_Distance => ManhattanDistance.js
Algorithms => Search_Algorithms => Bucket_Sort => BucketSort.js

Added => Maths_And_Stats => Geometry => Manhattan_Distance => JavaScript and Added => Algorithms => Search_Algorithms => Bucket_Sort => JavaScript

---

Algorithms/Selection_Algorithms/selection_sort.c

 add-selection_sort.c-program

---

Maths_And_Stats/Algebra/Factorial_of_Large_Number/bigfactorial.cpp

#311 
C++
1
Math and Stats => Algebra => Factorial of Large Number => bigfactorial.cpp

Added  Math => Algebra => Factorial of Large Number => bigfactorial.cpp

---

Maths_And_Stats/Statistics/Exponential_Smoothing/Exponential_Smoothing.java

#399 
Java
1
Maths_And_Stats=>Statistics=>Exponential_Smoothing=>Exponential_Smoothing.java
example :

Exponential_Smoothing.java created

---

Maths_And_Stats/Algebra/Arithmetic_Progression/Arithmetic_Progression.c
Maths_And_Stats/Algebra/Arithmetic_Progression/Arithmetic_Progression.php

#305 
C/PHP
2
Maths_And_Stats => Algebra => Arthimetic_Progression => Arthimetic_Progression.c
Maths_And_Stats => Algebra => Arthimetic_Progression => Arthimetic_Progression.php

Arthimetic Progression in C and PHP

---

Algorithms/Graph_Algorithms/A_star/A_star.cpp
Algorithms/Graph_Algorithms/A_star/A_star.py

#597
Python
1
Algorithm => Graph_Algorithms => A_star => A_star.py

Ahampriyanshu

---

Algorithms/Sorting_Algorithms/Bucket_Sort/BucketSort.c

#365
C
1
Algorithms/Sorting_Algorithms/Bucket_Sort/BucketSort.c

Bucket Sort in C #365

---

Algorithms/Dynamic_Programming/Target_sum/Target_Sum.java

#356 
Java
1
Algorithms/Dynamic_Programming/Target_sum/Target_Sum.java
- [YES ] I've read the contribution guidelines.
- [ YES] I've referred the correct issue number.
- [YES ] I've fill up this entire template correctly.

Added Target Sum in Java

---

Algorithms/String_Algorithms/palindrome.swift

#449
Swift
1
Algorithms/String_Algorithms/palindrome.swift

Added palindrome program for swift

---

Algorithms/Sorting_Algorithms/Quick_Select/QuickSelect.cpp
Algorithms/Sorting_Algorithms/Quick_Select/README.md

#568
C++
1
Algorithms/Sorting_Algorithms/Quick_Select/Quick_Select.cpp
- [yes ] I've read the contribution guidelines.
- [yes ] I've referred the correct issue number.
- [ yes I've fill up this entire template correctly.

Adding QuickSelect algorithm

---

Algorithms/Pattern_Searching/Rabin_Karp/Rabin_Karp.cpp

#623
C++
1
Algorithm => Pattern_Searching => Rabin_Karp => Rabin_Karp.cpp

Added => Algo => Pattern_Searching => Rabin_Karp => Rabin_Karp.cpp

---

Maths_And_Stats/Geometry/Manhattan_Distance/ManhattanDistance.java

#396 
Java
1
Maths_And_Stats => Geometry => Manhattan_Distance => ManhattanDistance.java
example :

Added => Maths_And_Stats => Geometry => Manhattan_Distance => JAVA

---

Maths_And_Stats/Geometry/Vector_Product/Vector_Product.cpp

#408 
C++
1
algo_ds_101 => Maths_and_Stats => Geometry => Vector_Product => Vector_Product.cpp

added Vector_Product.cpp

---

Maths_And_Stats/Geometry/Radians_Degrees_Conversion/Radians_Degrees_Conversion.js

#406 
JavaScript
1
Maths_And_Stats => Geometry => Radians_Degrees_Conversion => Radians_Degrees_Conversion.js

Added=>Maths_And_Stats=>Geometry=>Radians_Degrees_Conversion=>JavaScript

---

Maths_And_Stats/Geometry/N_Dimensional_Distance/n_dimensional_distance.py

#405 
Python
1
Maths_And_Stats => Geometry => N_Dimensional_Distance =>  n_dimensional_distance.py

Added Maths_And_Stats => Geometry => N_Dimensional_Distance => n_dimensional_distance.py

---

Algorithms/Sorting_Algorithms/Insertion_Sort/Insertion_sort_2.cpp

Insertion_sort

---

Algorithms/String_Algorithms/palindrome.ts

#449 
Typescript
1
Algorithms=> String_Algorithms => palindrome.ts

Adding new palindrome algorithm in Typescript

---

Maths_And_Stats/Geometry/Pythagorean_theorem/Pythagorean_theorem.rb

#413 
Ruby
1
Math_and_stats => Geometry => Pythagorean_theorem => Pythagorean_theorem.rb
example :

Adding Pythagorean_theorem.rb

---

Algorithms/String_Algorithms/Palindrome.c
Algorithms/String_Algorithms/Palindrome.java

#449 
C and Java
2
Algorithms/String_Algorithms/Palindrome.c
Algorithms/String_Algorithms/Palindrome.java

Palindrome implementation algorithm.

---

Maths_And_Stats/Algebra/Sieve of Eratosthenes/SieveOfEratosthens.c
SieveOfEratosthenes.c

#221 
C
1
Maths_And_Stats => Algebra => Sieve of Eratosthenes => SieveOfEratosthenes.c
example :
- [×] I've read the contribution guidelines.
- [×] I've referred the correct issue number.
- [×] I've fill up this entire template correctly.

Alkatrivedi

---

Algorithms/String_Algorithms/Palindrome.cs

#Assigned Issue Number ?
#449 
C#
1
Algorithms=>String_Algorithms=>Palindrome.cs
example :

Added=>Algorithms=>String_Algorithms=>Palindrome.cs=>C#

---

Maths_And_Stats/Calculus/Riemann_Sum/Riemann_Sum.cs

#392 
C#
1
Added =>Maths_And_Stats => Calculus => Riemann_Sum => Riemann_Sum.cs

Added =>Maths_And_Stats => Calculus => Riemann_Sum => C#

---

Maths_And_Stats/Algebra/Sum_of_HP/hpSum.js

#309 
JavaScript
1
Maths_And_Stats => Algebra => Sum_of_HP => hpSum.js

Added => Maths_And_Stats => Algebra => Sum_of_HP => JS

---

Maths_And_Stats/Statistics/Confidence_Interval/Confidence_Interval.cpp
Maths_And_Stats/Statistics/Confidence_Interval/Confidence_Inverval.c

#401 
C/C++
2
Maths_And_Stats => Statistics => Confidence_Inverval => Confidence_Interval.c
Maths_And_Stats => Statistics => Confidence_Inverval => Confidence_Interval.cpp

Added Confidence_Interval for C++ and C

---

Maths_And_Stats/Number_Theory/Sieve_of_Erastosthenes/Sieve_of_Erastosthenes.ts

#609 
TypeScript
1
Maths_And_Stats =>Number_Theory => Sieve_of_Eratosthenes => Sieve_of_Eratosthenes.ts

Added => Math_And_Stats => Number_Theory => Seive_of_Eratosthenes => Sieve_of_Eratosthenes.ts

---

Algorithms/String_Algorithms/palindrome.java

#449 
Java
1
Algorithms=> String_Algorithms => Palindrome.java

Added Algorithms=> String_Algorithms => Palindrome.java

---

Algorithms/Pattern_Searching/Rabin_Karp/Rabin_Karp.java

Algorithm => Pattern_Searching => Rabin_Karp => Rabin_Karp.java

Added => Algo => Pattern_Searching => Rabin_Karp => Rabin_Karp.java #623

---

Algorithms/String_Algorithms/palindrome.js

#449 
Javascript
1
Algorithms => String_Algorithms => palindrome.ts

Reducing complexity on javascript palindrome algorithm

---

Maths_And_Stats/Number_Theory/Sieve_of_Eratosthenes/SieveOfEratosthenes.cs

#609 
C#
1
Maths_And_Stats => Number_Theory =>  Sieve_of_Eratosthenes => Sieve_of_Eratosthenes.cs

Added => Maths_And_Stats => Number_Theory =>  Sieve_of_Eratosthenes => C#

---

Algorithms/Merging_Intervals/Merging_Intervals.java

#229 
Java
1
Added => Algorithms => Merging Intervals => Merging_Intervals.java

Added => Algorithms => Merging Intervals => Java

---

Data_Structures/Linked_List/Doubly_Linked_List/double linked list.c

doubly linked list.c

---

Algorithms/Pattern_Searching/Rabin_Karp/Rabin_karp.c

#623 
C
1
Algorithms => Pattern_Searching => Rabin_Karp => Rabin_Karp.c

Added => Algo => Pattern_Searching => Rabin_Karp => Rabin_Karp.c

---

Maths_And_Stats/Geometry/Pythagorean_theorem/Pythagorean_theorem.swift

#413 
Swift
1
Maths_And_Stats => Geometry => Pythagorean_theorem => Pythagorean_theorem.swift

Added => Maths_And_Stats => Geometry => Pythagorean_theorem => Pythagorean_theorem.swift

---

Maths_And_Stats/Geometry/Pythagorean_theorem/PythagoreanTheorem.cs

#413 
C#
1
Added => Maths_And_Stats => Geometry => Pythagorean_theorem => PythagoreanTheorem.cs

Added => Maths_And_Stats => Geometry => Pythagorean_theorem => C#

---

Maths_And_Stats/Geometry/Polar_Cartesian_Conversion/Polar_Cartesian_Conversion.py

#404
Python
1
Maths_And_Stats => Geometry => Polar_Cartesian_Conversion => Polar_Cartesian_Conversion.py

Maths_And_Stats => Geometry => Polar_Cartesian_Conversion => Polar_Cartesian_Conversion.py

---

Algorithms/Dynamic_Programming/Gauss_Easter_Date/easterDate.java

#525 
Java
1
Algorithm => Dynamic Programming => Gauss_Easter_Date => easterDate.java

Added => Algorithms => Dynamic_Programming => Gauss_Easter_Date => easterDate.java

---

Data_Structures/Linked_List/Circular_Linked_List/csharp/CircularLinkedList.cs
Data_Structures/Tree/Binary_Search_Tree/csharp/BST.cs

#502
C#
1
Data_Structures => Linked_List => Circular_Linked_List => CircularLinkedList.cs

Data_Structures => Linked_List => Circular_Linked_List => CircularLinkedList.cs

---

Data_Structures/Tree/Binary_Search_Tree/csharp/BST.cs

#498 
C#
1
Data_Structures => Tree => Binary_Search_Tree => BST.cs

Data_Structures => Tree => Binary_Search_Tree => BST.cs

---

Algorithms/Sorting_Algorithms/Selection_Sort/selection_sort.rb

#415 
Ruby
1
Algorithms ==> Sorting_Algorithms ==> Selection_Sort ==> selection_sort.rb

added ==> Algorithms ==> Sorting_Algorithms ==> Selection_Sort ==> selection_sort.rb

---

Algorithms/Merging_Intervals/merge_intervals.cpp

merge_intervals.cpp

---

Algorithms/Cryptography_Algorithm/Caesar_Cipher/Caesar Cypher.py

Added Python implementation of Caesar Cypher

---

Algorithms/Cryptography_Algorithm/Caesar_Cipher/Caesar Cypher.cpp

Added C++ implementation of Caesar Cypher

---

Algorithms/Sorting_Algorithms/Heap_Sort/heap_sort.java

heap_sort.java

---

Algorithms/Sorting_Algorithms/Heap_Sort/heap_sort.cpp

heap_sort.cpp

---

Data_Structures/Arrays/longest_common_subsequene.cpp

longest_common_subsequene.cpp

---

Algorithms/Search_Algorithms/Binary_Search/binarySearch.js
Algorithms/Sorting_Algorithms/Bead_Sort/Bead_sort.cpp
Algorithms/Sorting_Algorithms/Quick_Sort/QuickSort.py
Algorithms/Sorting_Algorithms/Quick_Sort/quicksort.C
Algorithms/String_Algorithms/Palindrome.java
Maths_And_Stats/Series/Modular_Exponentiation/Modular_Exponentiation.cpp

#651 
C++
1
Algorith => Sorting_Algorithm => Bead_Sort => Bead_Sort.cpp
example :
- [y ] I've read the contribution guidelines.
- [ y] I've referred the correct issue number.
- [ y] I've fill up this entire template correctly.

added c++ beat_sort file

---

Data_Structures/Tree/Binary_Search_Tree/valid BST

#007
C++
1/2/3/4/...
Data Structures => Trees => Validate_BST.cpp
- [*] I've referred the correct issue number.
- [*] I've fill up this entire template correctly.

Validate BST

---

Algorithms/Cryptography_Algorithm/Caesar_Cipher/Caesar_Cipher.c
Algorithms/Cryptography_Algorithm/Caesar_Cipher/Caesar_Cipher.js

Added Caesar Cipher implementation in C and JavaScript
#664 
C and JavaScript.
2
Algorithms => Cryptography_Algorithm => Caesar_Cipher =>  Caesar_Cipher.c
Algorithms => Cryptography_Algorithm => Caesar_Cipher =>  Caesar_Cipher.js

Added => Algo => Caesar Cipher => C and JS

---

Algorithms/Sorting_Algorithms/Tree_Sort/treesort.java
Algorithms/String_Algorithms/palindromecheck.go

#449 
Golang
1
Algorithms => String_Algorithms => palindromcheck.go

Algorithm=> String_Algorithms=> palindromecheck.go

---

Data_Structures/Arrays/revering_array.c

reversing_array.c

---

Data_Structures/Arrays/merging_2_arrays.c

merging_2_arrays.c

---

Algorithms/Sorting_Algorithms/Cycle_Sort/cyclesort.c
Algorithms/Sorting_Algorithms/Cycle_Sort/stoogesort.java

#705 #700 
C
2
Algorithm => Sorting Algorithm => Cycle_Sort => cyclesort.c 
+1  more
example :
- [yes] I've read the contribution guidelines.
- [yes ] I've referred the correct issue number.
- [yes] I've fill up this entire template correctly.

Cycle and Stooge sort in C

---

Algorithms/Sorting_Algorithms/Comb_Sort/comb_sort.rb

#699 
Ruby
1
algo_ds_101/Algorithms/Sorting_Algorithms/Comb_Sort/comb_sort.rb
- [ x ] I've read the contribution guidelines.
- [ x ] I've referred the correct issue number.
- [ x ] I've fill up this entire template correctly.

Added => Algorithms => Sorting_Algorithms => Comb_Sort => comb_sort.rb

---

Algorithms/Dynamic_Programming/Tower_of_hanoi.ts

#697 
Typescript
1
Algorithm =>Dynamic_Programming=>Tower_of_hanoi
example :

Tower_of_hanoi_in_typescript

---

Maths_And_Stats/Series/Harmonic_Progression/Harmonic.java
Maths_And_Stats/Series/Harmonic_Progression/Harmonic_Expression.java

#688 
Java
1
Added Maths_And_Stats => Series => Harmonic_Expression => Harmonic_Expression.java
example :

Added Maths_And_Stats => Series => Harmonic_Expression => Harmonic_Expression.java

---

Algorithm/Sorting_Programming/Counting_Sort/Counting_Sort.extension

#704 
C++
1
Algorithm => Sorting_Programming => Counting_Sort => Counting_Sort.extension
- [ ✔] I've read the contribution guidelines.
- [✔] I've referred the correct issue number.
- [✔ ] I've fill up this entire template correctly.

Added=>Algo=>Counting Sort=>CPP

---

.vscode/settings.json
Maths_And_Stats/Calculus/Riemann_Sum/riemann_sum.py

#392 
Python
1
Added => Math_And_Stats => Calculus => Riemann_Sum => riemann_sum.py

Added => Math_And_Stats => Calculus => Riemann_Sum => Python

---

Maths_And_Stats/Discrete/Ackermann_Peter/Ackermann_Peter.c
Maths_And_Stats/Discrete/Ackermann_Peter/Ackermann_Peter.js

#398 
C / JavaScript
2
Maths_And_Stats => Discrete => Ackermann_Peter => Ackermann_Peter.c
Maths_And_Stats => Discrete => Ackermann_Peter => Ackermann_Peter.js

Added Ackermann_Peter.c and Ackermann_Peter.js

---

Algorithms/Pattern_Searching/Rabin_Karp/Rabin_Karp.ts

#623 
TypeScript
1
Algorithms => Pattern_Searching => Rabin_Karp => Rabin_Karp.ts

ADDED => Alg => Pattern_Searching => Rabin_Karp => Rabin_Karp.ts 

---

Algorithms/Pattern_Searching/search.php

#623 
PHP
1
Algorithms/Pattern_Searching/search.php
- [ X] I've read the contribution guidelines.
- [ X] I've referred the correct issue number.
- [ X] I've fill up this entire template correctly.

Added Rabin-Karp in PHP

---

Data_Structures/Tree/Binary_Search_Tree/Validate_BST.py

#676
Python
1
Data_Structures => Tree => Binary_Search_Tree => Validate_BST.py

Added => Data_Structures => Tree => Binary_search_Tree => Validate_BST => Py

---

Algorithms/Cryptography_Algorithm/Vernam_Cipher/Vernam_Cipher.py

#666
Python
1
Algorithms => Cryptography_Algorithm => Vernam_Cipher => Vernam_Cipher.py

Added => Algorithms => Cryptography_Algorithm => Vernam_Cipher => Vernam_Cipher.py

---

Algorithms/Cryptography_Algorithm/RSA_Cipher/RSA_Cipher.py

#665
Python
1
Algorithms => Cryptography_Algorithm => RSA_Cipher => RSA_Cipher.extension

RSA_Cipher Added

---

Algorithms/Sorting_Algorithms/Tim_Sort/Tim_Sort.c

#701
C
1
Algorithm => Sorting_Programming => Tim_Sort => Tim_Sort.c
- [ yes ] I've read the contribution guidelines.
- [ yes] I've referred the correct issue number.
- [ yes] I've fill up this entire template correctly.

Added Tim_Sort.c (issue #701)

---

Algorithms/Sorting_Algorithms/Counting_Sort/Counting_Sort.c

#704
C
1
Algorithm => Sorting_Programming => Counting_Sort => Counting_Sort.c

Add Couting_Sort.c

---

Algorithms/Dynamic_Programming/Target_Sum/Target_Sum.js

#356
Javascript
1
Algorithm => Dynamic_Programming =>Target_Sum => Target_Sum.js

Algorithm => Dynamic_Programming =>Target_Sum => Target_Sum.js

---

Algorithms/Dynamic_Programming/Maximum_Achievable_Coins/Maximum_Achievable_coins.py

#507
Python
1
Algorithm => Dynamic Programming => Maximum Achievable coins => Maximum_Achievable_coins.py

Added => Algorithm => Dynamic Programming => Maximum Achievable coins => PY

---

Maths_And_Stats/Number_Theory/Ugly_Number/Ugly_Number.rb

#710 
Ruby
1
Maths_And_Stats => Number_Theory => Ugly_Number.rb

Added => Maths_And_Stats => Number_Theory => Ugly Number => Ruby

---

Algorithms/Sorting_Algorithms/Counting Sort/counting_sort.java

#704 
Java
1
Algo=>Counting Sort=>Java

Added=>Algo=>Counting Sort=>Java

---

Algorithms/Graph_Algorithms/BFS/bfs.js

#081
Javascript
1
algo_ds_101 => Algorithms => Graph_Algorithms => BFS => bfs.js

added bfs graph algorithm javascript

---

Maths_And_Stats/Series/Sum_of_AP/Sum_of_AP.js

#306 
JavaScript
1
Maths_And_Stats => Series => Sum_of_AP => Sum_of_AP.js

Added=>Math and Stats=>Series=>Sum of AP=>JS

---

Maths_And_Stats/Number_Theory/Ugly_Number/Ugly_Number.java

#710 
Java
1
Maths_And_Stats=>Number_Theory=>Ugly_Number=>Ugly_Number.java

Created Ugly_Number.java

---

Maths_And_Stats/Series/Lucas_Series/Lucas_Series.cpp

#709 
C++
1
example :
Maths_And_Stats => Series => Lucas_Series => Lucas_Series.cpp

add Lucas_Series.cpp

---

Maths_And_Stats/Geometry/Clock_Angle/clock_angle.go

#384
Golang
1
Math_And_Stats => Geometry => Clock_Angle  => clock_angle.go

Added => Math_And_Stats => Geometry => Clock_Angle  => clock_angle.go

---

Algorithms/Sorting_Algorithms/Cycle_Sort/CYCLESort.cs

CREATE CODE FOR CYCLE SORT
#729
C#
1
Algorithm => Sorting_Algorithms => Cycle_Sort => CYCLESort.cs
example :
- [✓] I've read the contribution guidelines.
- [ ✓] I've referred the correct issue number.
- [ ✓] I've fill up this entire template correctly.

MAKE CYCLE SORT WITH C# 

---

Data_Structures/Tree/Binary_Search_Tree/Validate_BST/Validate_BST.cpp

#676 
C++
1
Data_Structures ->Tree ->Binary_Search_Tree ->Validate_BST -> Validate_BST.cpp

Added -> Data_Structures ->Tree ->Binary_Search_Tree ->Validate_BST -> C++

---

Maths_And_Stats/Number_Theory/Ugly_Number/UglyNumbers.sh
Maths_And_Stats/Number_Theory/Ugly_Number/Ugly_Numbers.sh

#710 
Bash Script 
1
Maths_And_Stats/Number_Theory/Ugly_Number/Ugly_Numbers.sh
example :
Maths_And_Stast => Number_Theory => Ugly_Numbers =>Ugly_Numbers.sh(Bash script)

Added Ugly_Numbers.sh (Bash script) 

---

Maths_And_Stats/Number_Theory/Ugly_Number/UglyNumbers.sh

Added Bash shell script for recognition of Ugly Numbers.
#007
Bash Script
1
Maths_And_Stats/Number_Theory/UglyNumbers.sh
example :
Check whether the inputted number is a UglyNumber or not. 

Added UglyNumbers.sh

---

Data_Structures/Tree/Binary_Search_Tree/Validate_BST/Validate_BST.java

#676 
Java
1
Data_Structures => Tree => Binary_Search_Tree => Validate_BST

Created Validate_BST.java

---

Maths_And_Stats/Number_Theory/Ugly_Number/Ugly_Number.c

#710
C
1
Maths_And_Stats => Number_Theory => Ugly_Number => Ugly_Number.c

Added Ugly_Number.c

---

Maths_And_Stats/Number_Theory/Ugly_Number/Ugly_Number.py

#710 
Python
1
Maths_And_Stats => Number_Theory  => Ugly_Number =>Ugly_Number.py
- [✅] I've read the contribution guidelines.
- [✅ ] I've referred the correct issue number.
- [✅ ] I've fill up this entire template correctly.

Added => Ugly Number => Python

---

Algorithms/Sorting_Algorithms/Counting_Sort/Count_sort.py

#704 
Python
1
Algorithm => Sorting_algorithm => Counting_Sort =>  Count_sort.py

Add=>Algo=>Count_sort=>Python

---

Algorithms/Sorting_Algorithms/Counting_Sort/Counting_sort.js

#704
Javascript
1
main folder => Algorithms=> Sorting_Algorithms => Counting_Sort => Counting_sort.js
example :
Algorithms=> Sorting_Algorithms => Counting_Sort => Counting_sort.js

added => algo => Counting Sort => JS

---

Data_Structures/Linked_List/Doubly_Linked_List/DoublyLinkedList_C++_Template/DLL.h
Data_Structures/Linked_List/Doubly_Linked_List/DoublyLinkedList_C++_Template/DLLtest.cpp

#800
C++
2
Data_Structures => Linked_List => Doubly_Linked_List => DoublyLinkedList_C++_Template=>DLL.h
Data_Structures => Linked_List => Doubly_Linked_List => DoublyLinkedList_C++_Template=>DLLtest.cpp

add c++ Templates data structure of Doubly Link List

---

Algorithms/Recursion/recursion.js

#788 
JavaScript
1
Algorithms => Recursion => recursion.js

Created recursion.js

---

Algorithms/Sorting_Algorithms/Pancake_Sort/PancakeSort.java

This algorithm takes the name because it resembles sorting pancakes with a big spatula, where the cook uses it to flip some of the pancakes on the top.
To achieve a correct sorting, the first step is to find the max element position (method findGreatestElement), then "flipping" the numbers until the max element position, and repeat.
#702 
Java
1
Algorithms => Sorting_Algorithms => Pancake_Sort => PancakeSort.java

Implementing PancakeSort in Java language.

---

Algorithms/Sorting_Algorithms/Pancake_Sort/Pancake_Sort.c++

#702
C++
1
Algorithm => Sorting_Algorithm => Pancake_Sort => Pancake_Sort.c++

Added Pancake_Sort.c++

---

Algorithms/Sorting_Algorithms/Pancake_Sort/Pancake_Sort.py

#702 
Python
1
Algorithm  => Sorting_Algorithms => Pancake_Sort => Pancake_Sort.py
- [✅ ] I've read the contribution guidelines.
- [✅ ] I've referred the correct issue number.
- [✅] I've fill up this entire template correctly.

Added pancake sort code in python

---

Algorithms/Sorting_Algorithms/Circle_Sort/Circle_Sort.java

#703
Java
1
Algorithm => Sorting_Algorithm => Circle_Search => Circle_Sort.java

Addded Circle_Sort.java

---

Algorithms/Sorting_Algorithms/Counting_Sort/Counting_Sort.cs

#704
C#
1
Added  Algorithms => Sorting_Algorithms => Counting_Sort => Counting_Sort.cs

Added  Algorithms => Sorting_Algorithms => Counting_Sort => C#

---

Algorithms/Sorting_Algorithms/Heap_Sort/README.md
Algorithms/Sorting_Algorithms/Heap_Sort/heap-sort.c

#653 
C
1
Algorithms => Sorting_Algorithms => Heap_Sort => heap-sort.c

 Added => Algo => Heap Sort => C

---

Algorithms/Search_Algorithms/Trie_Search/TrieDataStructure.java

#685
Java
1
Algorithms=>Search_Algorithms=>Trie_Search=>TrieDataStructure.java
example :

Trie Search and Insert

---

Algorithms/Sorting_Algorithms/Shell_Sort/Shell_Sort.js

#649 
Javascript
1
Algorithm => Sorting_Algorithm =>Shell_Sort.js

Added => Algo => Sorting_Algo =>Shell_Sort => Javascript

---

Algorithms/Selection_Algorithms/Quick_Select/Quick_Select.php

#568
php
1
Algorithms => Selection_Algorithms => Quick_Select => Quick_Select.php

Algorithms => Selection_Algorithms => Quick_Select => php

---

Data_Structures/Queues/queue.go

#494
Golang
1
Data_Structures => Queue => queue.go

Data_Structures => Queue => queue.go

---

Data_Structures/Tree/AVL_Tree/AVL_Tree.py

Added one file for basic AVL Tree implementation in python
#489 
Python
1
Added Data_Structures=>Tree=>AVL_Tree=>AVL_Tree.py

Added Data_Structures=>Tree=>AVL_Tree=>AVL_Tree.py

---

Algorithms/Sorting_Algorithms/Heap_Sort/heap_sort.go

#653
Golang
1
Algorithms => Sorting_Algorithms => Heap_Sort => heap_sort.go

Added => Algorithms => Sorting Algorithms => Heap Sort => Go

---

Algorithms/Sorting_Algorithms/Cocktail_Sort/Cocktail_Sort.py

Cocktail sort program in python language. It is similar to bubble sort with less complexity.
#698
Python
1
Algorithms/Sorting_Algorithms/Cocktail_Sort/Cocktail_Sort.py

Cocktail Sort In Python

---

Algorithms/Dynamic_Programming/LIS/LIS.go

#686
Golang
1
Algorithms => Dynamic_Programming => LIS => LIS.GO

Added => Algorithms => Dynamic Programming => LIS => Go

---

Data_Structures/Tree/RED BLACK TREE USING C++

Implementation of Red-Black Tree in C++
#007
1/2/3/4/...
example :

RED BLACK TREE USING C++

---

Data_Structures/Tree/B TREE  USING C++

IMPLEMENTATION OF B TREE USING C++
#007
1/2/3/4/...
example :

B TREE  USING C++

---

Data_Structures/Tree/SPLAY TREE

IMPLEMENTATION OF SPLAY TREE USING C++
#007
1/2/3/4/...
example :

SPLAY TREE

---

Data_Structures/Tree/RED BLACK TREE

C++ implementation for Red-Black Tree Insertion
#007
1/2/3/4/...
example :

RED BLACK TREE

---

Data_Structures/Tree/RED BLACK TREE USING C

Implementation of Red-Black Tree in C
#007
1/2/3/4/...
example :

RED BLACK TREE USING C

---

Algorithms/Recursion_Algorithm/Factorial.java
Algorithms/Recursion_Algorithm/FibonacciSeriesRecursion.java
Algorithms/Recursion_Algorithm/Recursion Algorithm
CONTRIBUTORS.md

#788
Java
3
Algorithms => Recursion_Algorithm =>FibonacciSeriesRecursion.java, Factorial.java, Recursive Algorithm
example :

Jayavardhani

---

Data_Structures/Linked_List/Singly_Linked_List/CycleDetection.java

#737 
Java
1
Data_Structures => Linked_List => Singly_Linked_List => CycleDetection.java

Created CycleDetection.java

---

Maths_And_Stats/Number_Theory/Ugly_Number/UglyNumber.go

Signed-off-by: parauliya <parauliya.aman@gmail.com>
#710 
Golang
1 - Added 
Maths_And_Stats => Number_Theory => Ugly_Number => UglyNumber.go

UglyNumber programe in Golang

---

Algorithms/Cryptography_Algorithm/Affine_Cipher/Affine_Cipher.cpp

The Affine cipher is a type of monoalphabetic substitution cipher, wherein each letter in an alphabet is mapped to its numeric equivalent, encrypted using a simple mathematical function, and converted back to a letter.
#007
C++
1

Adding code for Affine Cipher

---

Algorithms/Cryptography_Algorithm/Vernam_Cipher/Vernam_Cipher.js

#666 
Javascript
1
Algorithm => Cryptography_Algorithm => Vernam_Cipher => Vernam_Cipher.js
example :

Algorithm => Cryptography_Algorithm => Vernam_Cipher => Vernam_Cipher.js

---

Maths_And_Stats/Number_Theory/Fibonacci_Number/Fibonacci_Number.clj

#863
Clojure
1
Maths_And_Stats => Number_Theory => Fibonacci_Number => Fibonacci_Number.clj

Added => Maths And Stats => Number Theory => Fibonacci Number => Clojure

---

Algorithms/Dynamic_Programming/Gauss_Easter_Date/Gauss_Easter_Date.php
Maths_And_Stats/c/Lucas_Series/Lucas_Series.php

#525
#709
PHP
2
Algorithm => Dynamic Programming => Gauss_Easter_Date => Gauss_Easter_Date.php
Maths_And_Stats => c => Lucas_Series => Lucas_Series.php

Added Algorithm => Dynamic Programming => Gauss_Easter_Date => Gauss_Easter_Date.php & Added Maths_And_Stats => c => Lucas_Series => Lucas_Series.php

---

Data_Structures/Tree/AVL_Tree/AVLtree.c

AVL Tree #489
C
1
Data_Structures/Tree/AVL_Tree/AVLtree.c

Added =>Data_Structures => Tree => AVL_Tree => AVLtree.c

---

Algorithms/Sorting_Algorithms/Bubble_Sort/readme.md
Algorithms/Sorting_Algorithms/Insertion_Sort/README.md
Algorithms/Sorting_Algorithms/Merge_Sort/README.md
Algorithms/Sorting_Algorithms/Quick_Sort/README.md
Algorithms/Sorting_Algorithms/README.md
Algorithms/Sorting_Algorithms/Selection_Sort/README.md

Added Readme 

---

LSCS.cpp

#852 
C++
1
Algorithms => Dynamic_Programming => LSCS.cpp

Added Largest Sum Contiguous Subarray C++

---

Maths_And_Stats/Number_Theory/Ugly_Number/Ugly_Number.php

#710 
PHP
1
Maths_And_Stats => Number_Theory => Ugly_Number => Ugly_Number.php
- [ X] I've referred the correct issue number.
- [ X] I've fill up this entire template correctly.

Add => Number_Theory => Ugly_Number => Ugly_Number.php

---

Maths_And_Stats/Number_Theory/Ugly_Number/Ugly_Number.js

#710
Javascript
1
Maths_And_Stats => Number_Theory => Ugly_Number => Ugly_Number.js

Maths_And_Stats => Number_Theory => Ugly_Number => Ugly_Number.js

---

Algorithms/Dynamic_Programming/Max_Product_Subarray/max_product_subarray.py

Problem link: https://leetcode.com/problems/maximum-product-subarray/
#007
Python
1
Algorithm => Dynamic_Programming => Maximum_Product_Subaraay => max_product_subarray.py

[Python] Add maximum product subarray

---

Maths_And_Stats/Number_Theory/Sieve_of_Eratosthenes/Sieve_of_Erastosthenes.rb

#609
Ruby
1
Maths_And_Stats => Number_Theory => Sieve_of_Eratosthenes => Sieve_of_Eratosthenes.rb

Added  Number_Theory => Sieve of Erathostenes => Ruby

---

Algorithms/Cryptography_Algorithm/Caesar_Cipher/Caesar_Cipher.cs

#664
C#
1
Algorithm => Cryptography_Algorithm => Caesar_Cipher => Caesar_Cipher.cs

Added Algorithm => Cryptography_Algorithm => Caesar_Cipher => C#

---

Maths_And_Stats/Statistics/Compound_Interest/Compound_Interest.cs

#763 
C#
1
Maths_and_Stats => Statistics => Compound_Interest => Compound_Interest.cs

Added => Maths_and_Stats => Statistics => Compound_Interest => C#

---

Maths_And_Stats/Statistics/Compound_Interest/Compound_Interest.rb

#763 
Ruby
1
Maths_And_Stats => Statistics => Compound _Interest => Compound_Interest.rb
example :

Adding Compound_Interest.rb

---

Data_Structures/Linked_List/Singly_Linked_List/DetectCycle.py
Maths_And_Stats/Statistics/Compound_Interest/Compound_Interest.py

#737 
Python
1
example :
Main_Folder => Data_Structures => Linked_List => Singly_Linked_List => DetectCycle.py

Added Linked List cycle detection code in python

---

Algorithms/Sorting_Algorithms/Stooge_Sort/Stooge_Sort.py

#734 
Python
1
Algorithms/Sorting_Algorithms/Stooge_Sort/Stooge_Sort.py

Added Stooge_Sort.py

---

Data_Structures/Stacks/stack.cs

#475
C#
1
Data_Structures => Stacks => stack.cs

Created stack.cs

---

Algorithms/Dynamic_Programming/Maximum_Achievable_Coins/Maximum_Achievable_coins.c

Sorry for the late response there were internet issues.
#507 
C
1
Algorithms=>Dynamic_Programming=>Maximum_Achievable_Coins
example :

Added=> Algorithms=>Dynamic_Programming =>Maximum_Achievable_Coins

---

Data_Structures/Linked_List/Singly_Linked_List/merge2sortedlinkedlists.cpp

#810
C++
1
merge2sortedlinkedlists.cpp
algo_ds_101\Data_Structures\Linked_List\Singly_Linked_List

added a new code for merging 2 sorted linked lists into one

---

Data_Structures/Linked_List/Singly_Linked_List/linked list.c

This contains basic operations which can be carried out on a linked list using C programming language.
#007
1/2/3/4/...
example :

Linked list using C language

---

Algorithms/Cryptography_Algorithm/Vigenere_Cipher/Vigenere_Cipher.cpp

#667 
C++
1
Algorithm => Cryptography_Algorithm => Vigenere_Cipher => Vigenere_Cipher.cpp

Added Vigenere_Cipher.cpp

---

.vscode/settings.json
Maths_And_Stats/Calculus/Leibniz_formula/LeibnizFormula.py

#391 
Python
1
Maths_And_Stats => Calculus => Leibniz_Formula => LeibnizFormula.py

Maths_And_Stats => Calculus => Leibniz_Formula => Python

---

Data_Structures/Linked_List/Singly_Linked_List/DetectCycle(Go)/main.go

#737 
Go
1
Data_Structures/Linked_List/Singly_Linked_List/DetectCycle\(Go\)/main.go

Added => Data Structures => Linked List => Singly Linked List => Detect Cycle => Golang

---

Algorithms/Sorting_Algorithms/Stooge_Sort/Stooge_Sort.py

#734 
Python
1
Algorithm => Sorting_Algorithm => Stooge_Sort => Stooge_Sort.py

Added => Algo => Stooge Sort => Python

---

Algorithms/Sorting_Algorithms/Counting_Sort/Counting_Sort.java

added counting sort in java #704

---

Algorithms/Sorting_Algorithms/Cocktail_Sort/Cocktail_Sort.java

Cocktail sort function sorts the unsorted array similar to bubble sort but has less complexity in comparison.
#698
Python
1
Algorithms/Sorting_Algorithms/Cocktail_Sort/Cocktail_Sort.java

Cocktail Sort In Java

---

Data_Structures/Recursion/towerOfHanoi.cpp

C++
2
Data Structure => Recursion => TowerOfHanoi.cpp
example :

Recursion => TowerOfHanoi.cpp
