ahampriyanshu/algo_ds_101

- Algorithms/Search_Algorithms/Binary_Search/binarySearch.scala
#862
Scala
1
Algorithms => Search_Algorithms => Binary_Search => binarySearch.scala
> Added =>  Algorithms => Search_Algorithms => Binary_Search =>Scala

- Algorithms/Sorting_Algorithms/Circle_Sort/Circle_Sort.c
#703
C
1
Algorithms => Sorting_Algorithms => Circle_Sort => Circle_Sort.c
> Added Circle_Sort.c

- Data_Structures/K Dimensional Tree
Implementation of  K Dimensional Tree  in C++
#007
1/2/3/4/...
example :
> K Dimensional Tree

- Maths_And_Stats/Series/Harmonic_Progression/HarmonicProgresion.c
#688
C
1
Maths_And_Stats => Series => Harmonic_Progression => HarmonicProgresion.c
> Added => Maths_And_Stats => Series => Harmonic_Progression => HarmonicProgresion.c

- Data_Structures/Queues/Queue.swift
#494 
Swift
1
Data_Structures => Queues => Queue.swift
> Added => Data Stuctures => Queues => Swift

- Data_Structures/Tree/AVL_Tree/AVL_Tree.java
#489 
Java
1
Data_Structures=> Tree => AVL_Tree=>AVL_Tree.java
>  Data_Structures=> Tree => AVL_Tree=>AVL_Tree.java

- Algorithms/Sorting_Algorithms/Shell_Sort/Shell_Sort.cpp
#649 
C++
1
Algorithms => Sorting_Algorithms => Shell_Sort => Shell_Sort.cpp
> Added => Algorithms => Sorting_Algorithms => Shell_Sort => CPP

- Algorithms/Cryptography_Algorithm/Caesar_Cipher/CaesarCipher.java
#664
Java
1
Algorithms => Cryptography_Algorithm => Caesar_Cipher => CaesarCipher.java
> Added => Algo => Crypt => Caesar_Cipher => JAVA

- Algorithms/Cryptography_Algorithm/Caesar_Cipher/Caesar_Cypher.rb
#664
Ruby
1
Algorithms => Cryptography => Caesar Cipher => Caesar_Cipher.rb
> Added  Algorithms => Cryptography => Caesar Cipher => Ruby

- Data_Structures/Maps_Hash_Dict/amicable.js
> Data_Structures => Maps_Hash_Dict => amicable.js

- Data_Structures/Maps_Hash_Dict/Amicable_Numbers..c
- Data_Structures/Maps_Hash_Dict/Amicable_Numbers.cpp
- Maths_And_Stats/Algebra/GCD/GCD.sh
#847 
C and C++
2
Data_Structures/Maps_Hash_Dict/Amicable_Numbers.c
Data_Structures/Maps_Hash_Dict/Amicable_Numbers.cpp
example :
Data_Structures => Maps_Hash_Dict => Amicable_Numbers
- [ y] I've read the contribution guidelines.
- [y ] I've referred the correct issue number.
- [ y] I've fill up this entire template correctly.
> Added files for Amicable_Numbers for c and cpp languages

- Data_Structures/Maps_Hash_Dict/Verticle_sum_of_Binary_Tree.cpp
#845 
C++
1
Data_Structures => Maps_Hash_Dict => Vertical Sum of Binary Tree  => Vertical_sum_Of_Binary_Tree.cpp
example :
> Added => Data_Structures => Maps_Hash_Dict => Vertical Sum of Binary Tree  => Cpp

- Data_Structures/Queues/reversing a queue.cpp
#893
C++
1
reversing a queue.cpp
algo_ds_101\Data_Structures\Queues
> reverse a queue code added-common in interviews

- Algorithms/Sorting_Algorithms/Comb_Sort/comb.py
#699
Python
1
Algorithms => Sorting_Algorithms => Comb_Sort => comb.py
> Added => Algo => Comb Sort => Python

- Algorithms/Graph_Algorithms/Dijkstra/Dijkstra.go
#684
Golang
1
Added => Graph_Algorithms => Dijkstra => Dijkstra.go
> Added => Graph Algorithms => Dijkstra => Go

- Algorithms/Recursion_Algorithm/Fibonacci.cs
#788 
C#
1
Algorithms => Recursion_Algorithm => Fibonacci.cs
example :
> added Fibonacci.cs

- Data_Structures/Arrays/Remove-Dublicate.js
> Algorithm => Data Structure => Array => Remove-Dublicate.js

- Data_Structures/Arrays/README.md
- Data_Structures/Arrays/copyarray.c
> Readme.md update and copy array in c added

- Algorithms/Search_Algorithms/Binary_Search/binarysearch.sh
- Algorithms/Sorting_Algorithms/Merge_Sort/mergesort.sh
- Data_Structures/Linked_List/Doubly_Linked_List/DoublyLinkedList.hs
- Data_Structures/Linked_List/Singly_Linked_List/singly_linked_list.hs
- Data_Structures/Stacks/stacks.hs
#859 
Haskell
3
1. Data_Structures => Stacks => stacks.hs
2. Data_Structures => Linked_List => Singly_Linked_List => singly_linked_list.hs
3. Data_Structures => Linked_List => Doubly_Linked_List => DoublyLinkedList.hs
> Added haskell codes for Stack, SinglyLinkedList & DoublyLinkedList

- Algorithms/Search_Algorithms/Binary_Search/binarysearch.sh
- Algorithms/Sorting_Algorithms/Merge_Sort/mergesort.sh
#860
bash
2
1.  Algorithms => Sorting_Algorithms => Merge_Sort => mergesort.sh
2.  Algorithms => Search_Algorithms => Binary_Search => binarysearch.sh
> Added bash programs for Mergesort and BinarySearch

- Algorithms/Cryptography_Algorithm/Vigenere_Cipher/Vigenere_Cipher.py
#667 Vigenere Cipher
Python
1
Algorithms > Cryptography_Algorithm > Vigenere > Vigenere_Cipher.py
> Algorithms > Cryptography_Algorithm > Vigenere > Vigenere_Cipher.py

- Algorithms/Dynamic_Programming/LIS/LIS.java
- Algorithms/Dynamic_Programming/LIS/README.md
#686
Java
2
Algorithm => Dynamic Programming =>LIS=>LIS.java
Algorithm => Dynamic Programming =>LIS=>README.md
> Added LIS Java Solution and Updated Readme

- Algorithms/Sorting_Algorithms/Quick_Sort/Quick_Sort.sh
- Algorithms/String_Algorithms/anagrams.sh
Outputs:
- Quicksort
- Anagrams
#860 
Bash
2
1. Algorithms/Sorting_Algorithms/Quick_Sort/Quick_Sort.sh
2. Algorithms/String_Algorithms/anagrams.sh
> Added Quicksort and checking Anagrams in bash

- Algorithms/Cryptography_Algorithm/Vernam_Cipher/Vernam_Cipher.cpp
#666 
C++
1
Algorithm => Cryptography_Algorithm => Vernam_Cipher => Vernam_Cipher.cpp
> Added Vernam_Cipher.cpp

- Algorithms/Graph_Algorithms/Dijkstra/dijkstra_leftist_heap/README.txt
- Algorithms/Graph_Algorithms/Dijkstra/dijkstra_leftist_heap/WDGraph.cpp
- Algorithms/Graph_Algorithms/Dijkstra/dijkstra_leftist_heap/WDGraph.h
- Algorithms/Graph_Algorithms/Dijkstra/dijkstra_leftist_heap/dijkstra.cpp
- Algorithms/Graph_Algorithms/Dijkstra/dijkstra_leftist_heap/leftistHeap.cpp
- Algorithms/Graph_Algorithms/Dijkstra/dijkstra_leftist_heap/leftistHeap.h
#920
C++
6
Algorithms/Graph_Algorithms/Dijkstra/dijkstra_leftist_heap/*
> adding Algorithms/Graph_Algorithms/Dijkstra/dijkstra_leftist_heap/*

- Algorithms/Dynamic_Programming/Tower_Of_Hanoi/Tower_Of_Hanoi.cs
Added tower_of_hanoi for issue #697
#697
C#
1
Algorithm => Dynamic_Programming => Tower_Of_Hanoi => Tower_Of_Hanoi.ext
> Create Tower_Of_Hanoi in C#

- Algorithms/Dynamic_Programming/Gauss_Easter_Date/Gauss_Easter_Date.rb
##525
Ruby
1
Algorithm => Dynamic Programming => Gauss_Easter_Date => Gauss_Easter_Date.rb
> Algorithm => Dynamic Programming => Gauss_Easter_Date => Ruby

- Algorithms/Cryptography_Algorithm/Vigenere_Cipher/vigenereCipher.py
#667 
Python
1
Algorithm => Cryptography_Algorithm => Vigenere_Cipher => vigenereCipher.py
> Added => Cryptographic Algo => Vigenere cipher => Python

- Algorithms/Search_Algorithms/Trie_Search/Trie_Search.py
#685 
Python
1
Algorithms => Search_Algorithms => Trie_Search => Trie_Search.py
> Added => Algo => Trie Search => Python

- Data_Structures/Linked_List/Singly_Linked_List/DetectCycle.ts
#737
TypeScript
1
Data_Structures => Linked_List => Singly_Linked_List => DetectCycle.ts
> Find cycle in a Linked List - TypeScript

- Algorithms/Sorting_Algorithms/Stooge_Sort/Stooge_Sort.go
#734 
Golang
1
Algorithms ==> Sorting_Algorithms ==> Stooge_Sort ==> Stooge_Sort.go
- [yes ] I've read the contribution guidelines.
- [yes] I've referred the correct issue number.
- [yes] I've fill up this entire template correctly.
> Added => Algo => Stooge Sort => Golang #734

- Algorithms/Graph_Algorithms/A_Star/A_star.ts
#597 
TypeScript
1
Algorithms => Graph_Algorithms => A_star => A_Star.ts
example :
Algorithms => Graph_Algorithms => A_Star => A_Star.ts
> A_star algorithm in typscript

- queue.java
#494
Java
1
Data_Structures => Queue => queue.java
> Added => Data_Structures => Queue => queue.java

- Maths_And_Stats/Algebra/LCM/LCM.sh
- Maths_And_Stats/Algebra/Quadratic_Formula/Quadratic_Formula.sh
- Maths_And_Stats/Number_Theory/Perfect_Number/Perfect_Number,sh
- Maths_And_Stats/Series/Arithmetic_Progression/Arithmetic_Progression.sh
- Maths_And_Stats/Series/Fibonacci/Fibonacci.sh
- Maths_And_Stats/Series/Geometric_Progression/Geometric_Progression.sh
#860 
Bash Shell Scripts
6
Maths_And_Stats/Algebra/LCM/LCM.sh
Maths_And_Stats/Algebra/Quadratic_Formula/Quadratic_Formula.sh 
Maths_And_Stats/Series/Arithmetic_Progression/Arithmetic_Progression.sh
Maths_And_Stats/Series/Geometric_Progression/Geometric_Progression.sh
Maths_And_Stats/Series/Fibonacci/Fibonacci.sh
Maths_And_Stats/Number_Theory/Perfect_Numbers/Perfect_Numbers.sh
example :
Maths_And_Stats=>Algebra =>LCM =>bash scripts
- [ y] I've read the contribution guidelines.
- [ y] I've referred the correct issue number.
- [ y] I've fill up this entire template correctly.
> Added Bash Script for LCM and Quadratic_Formula

- Maths_And_Stats/Calculus/Runge–Kutta_Method/README.md
- Maths_And_Stats/Calculus/Runge–Kutta_Method/Runge-Kutta.cpp
#395 
2
Maths_And_Stats => Calculus =>Runge–Kutta_Method =>Runge-Kutta.cpp
Maths_And_Stats => Calculus =>Runge–Kutta_Method =>README.md
- [ X] I've read the contribution guidelines.
- [ X] I've referred the correct issue number.
- [X ] I've fill up this entire template correctly.
> Added Runga Kutta implemetation in c++

- Algorithms/Dynamic_Programming/Largest_Sum_Contiguous_Subarray/lscs.c
Solution for Largest Sum Contiguous Subarray in C language.
#852 
C
1
Algorithm => Dynamic Programming => Largest_Sum_Contiguous_Subarray => lscs.c
example :
Algorithm => Dynamic Programming => Largest_Sum_Contiguous_Subarray => lscs.c
> Largest Sum Contiguous Subarray in C language

- Algorithms/Dynamic_Programming/Largest_Sum_Contiguous_Subarray/LSCS.swift
#852 
Swift
1
example :
Algorithm => Dynamic_Programming =>Largest_Sum_Contiguous_Subarray=> ... => LSCS.swift
> Added => Algo =>  Dynamic Programming => kadane's => Swift

- Algorithms/String_Algorithms/ScrambleString.java
#942 
Java
1
Algorithm => String_algorithm => ScrambleString.java
> Added => Algorithms => String_Algorithms => ScrambleString => Java

- Maths_And_Stats/Statistics/Mode/mode.py
#843 
Python
1
algo_ds_101 => Maths_And_Stats => Statistics => Mode => mode.py
> Python stats 'mode' function added

- Algorithms/MOS_Algorithm.cpp
You are given array Arr of length N and Q queries. Each query is represented by two numbers L and R, and it asks you to compute some function Func with subarray Arr[L..R] as its argument.
There is an integer array Arr of length N and Q queries. For each i, query #i asks you to output the sum of numbers on subarray [Li, Ri], i.e. Arr[Li] + Arr[Li + 1] + … + Arr[Ri].
Here we have Func([L, R]) = Arr[L] + Arr[L + 1] + ... + Arr[R].
Mo’s algorithm provides a way to answer all queries in O((N + Q) * sqrt(N) * F) time with at least O(Q) additional memory.
#997 
C++
1...
Algorithm => Mos_Algorithm => MOS_Alogrithm.cpp
example :
> MOS_Algorithm.cpp

- Maths_And_Stats/Statistics/Confidence_Interval/confidenceInterval.js
#691
Javascript
1
Maths_And_Stats\Statistics\Confidence_Interval
> implemented confidence interval calculation in JS

- .gitignore
- Maths_And_Stats/Number_Theory/Strong_Number/strong_number.c
- Maths_And_Stats/Number_Theory/Strong_Number/strong_number.cpp
- Maths_And_Stats/Number_Theory/Strong_Number/strong_number.java
- Maths_And_Stats/Number_Theory/Strong_Number/strong_number.py
- Maths_And_Stats/Number_Theory/Strong_Number/strong_number.sh
> ## Assigned Issue Number ?
> #860
>
> ## Language Opted ?
> Bash,C,CPP,Java,Python
>
> ## Number of files added or updated ?
> 5
>
> ## Name of these files ?
> main folder => Maths_And_Stats => Number_Theory => Strong_Number => strong_number.sh
>main folder => Maths_And_Stats => Number_Theory => Strong_Number => strong_number.c
>main folder => Maths_And_Stats => Number_Theory => Strong_Number => strong_number.cpp
>main folder => Maths_And_Stats => Number_Theory => Strong_Number => strong_number.java
>main folder => Maths_And_Stats => Number_Theory => Strong_Number => strong_number.py
>
> ### Checklist
> * [x]  I've read the contribution guidelines.
> * [x]  I've referred the correct issue number.
> * [x]  I've fill up this entire template correctly.
> Added => Maths_And_Stats => Number_Theory => Strong_Number

- Algorithms/Recursion_Algorithm/Factorial_Algorithm.cpp
#1027 
C++
1
Algorithms => Recursion_Algorithm => Factorial_Algorithm.cpp
> Factorial Recursive Algorithm #1027

- Algorithms/Sorting_Algorithms/Merge_Sort/non_recursive_merge_sort.c
#1036
C
1
Algorithm => Sorting_Algorithms => Merge_sort => non_recursive_merge_sort.c
> Create  non_recursive_merge_sort.c

- Algorithms/Sorting_Algorithms/Shell_Sort/Shell_Sort.swift
#649 
Swift
1
Algorith => Sorting_Algorithm => Shell_Sort =>Shell_Sort.swift
> Added => Algo => Shell_Sort => swift

- Data_Structures/Linked_List/Singly_Linked_List/linked.cpp
- Data_Structures/Linked_List/Singly_Linked_List/linkedlist.cpp
- Data_Structures/Queues/cirqueue.cpp
- Data_Structures/Queues/linkqueue.cpp
- Data_Structures/Queues/queue1.c
- Data_Structures/Stacks/linkstack.cpp
- Data_Structures/Tree/Binary_Search_Tree/operationBST.cpp
Added linked list,stack,queue,circular queue in C++ and Operations on BST
C/C++
7
Data_Structures/Linked_List/Singly_Linked_List/linked.cpp
Data_Structures/Linked_List/Singly_Linked_List/linkedlist.cpp
Data_Structures/Queues/cirqueue.cpp
Data_Structures/Queues/linkqueue.cpp
Data_Structures/Queues/queue1.c
Data_Structures/Stacks/linkstack.cpp
Data_Structures/Stacks/linkstack.cpp
Data_Structures/Tree/Binary_Search_Tree/operationBST.cpp
> Added linked list,Stack,queue,circular queue

- Algorithms/Recursion_Algorithm/All_Subsets.c
- Algorithms/Recursion_Algorithm/Factorial.c
- Algorithms/Recursion_Algorithm/NFirst_Term_Fibonacci.c
#788 
#1027
C
3
Algorithms => Recursion_Algorithm => All_Subsets.c
Algorithms => Recursion_Algorithm => Factorial.c
Algorithms => Recursion_Algorithm => NFirst_Term_Fibonacci.c
> Implementation recursive algorithms

- Algorithms/Recursion_Algorithm/Factorial_Algorithm.py
#1027
Python
1
Algorithm => Algorithms => Recursion_Algorithm=> Factorial_Algorithm.py
> Factorial Recursive Algorithm

- Data_Structures/Deque/Deque.ts
#911
TypeScript
1
Data_Structures => Deque => Deque.ts
> Generic Deque Implementation - TypeScript

- Algorithms/Sorting_Algorithms/Pigeonhole_Sort/PigeonholeSort.ts
#964 
TypeScript.
1
Algorithms => Sorting_Algorithms => Pigeonhole_Sort => PigeonholeSort.ts
> PigeonholeSort Implementation in TypeScript

- Data_Structures/Tree/Binary_Search_Tree/binary_tree_trans.cpp
#41 
C++
1
Data_Structures =>Tree => Binary_Search_Tree.cpp
- [* ] I've read the contribution guidelines.
- [* ] I've referred the correct issue number.
- [ *] I've fill up this entire template correctly.
> Anti Clockwise spiral traversal of a binary tree in C++

- Algorithms/Recursion_Algorithm/Factorial.go
Created new Factorial program using recursion (Golang)
#1027 
Golang
1
Algorithms => Recursion_Algorithm => Factorial.go
> Factorial in Go

- Algorithms/Cryptography_Algorithm/Affine_Cipher/Affine_Cipher.py
#661
Python
1
Algorithm => Cryptography_Algorithm => Affine_Cipher => Affine_Cipher.py
> added Algorithm => Cryptography_Algorithm => Affine_Cipher => Affine_Cipher.py

- Maths_And_Stats/Geometry/Clock_Angle/Clock_Angle.hs
- Maths_And_Stats/Geometry/Distance_Formula/Distance_Formula.hs
- Maths_And_Stats/Geometry/Manhattan_Distance/Manhattan_Distance.hs
- Maths_And_Stats/Geometry/N_dimensional_distance
- Maths_And_Stats/Geometry/Polar_Cartesian_Conversion/Polar_Cartesian_Conversion.hs
- Maths_And_Stats/Geometry/Pythagorean_theorem/Pythagorean_theorem.hs
- Maths_And_Stats/Geometry/Radians_Degrees_Conversion/Radians_Degrees_Conversion.hs
- Maths_And_Stats/Geometry/Scalar_Product/Scalar_Product.hs
- Maths_And_Stats/Geometry/Vector_Product/Vector_Product.hs
#859
Haskell
9
Maths_And_Stats => Geometry => Clock_Angle => Clock_Angle.hs
Maths_And_Stats => Geometry => Distance_Formula => Distance_Formula.hs
Maths_And_Stats => Geometry => Manhattan_Distance => Manhattan_Distance.hs
Maths_And_Stats => Geometry => N_Dimensional_Distance.hs => N_Dimensional_Distance.hs
Maths_And_Stats => Geometry => Polar_Cartesian_Conversion => Polar_Cartesian_Conversion.hs
Maths_And_Stats => Geometry => Pythagorean_theorem => Pythagorean_theorem.hs
Maths_And_Stats => Geometry => Radians_Degrees_Conversion => Radians_Degrees_Conversion.hs
Maths_And_Stats => Geometry => Scalar_Product => Scalar_Product.hs
Maths_And_Stats => Geometry => Vector_Product => Vector_Product.hs
> Geometry formulae added in Haskell

- Algorithms/Dynamic_Programming/Egg_Drop.cpp
#1045 
C++
1
Algorithms => Dynamic_Programming => Egg_Drop.cpp
> Added=>Algorithms=>Dynamic_Programming=>Egg_Drop.cpp

- Maths_And_Stats/Algebra/Markov_Matrix/Markov_Matrix.cs
#708
C#
1
Maths_and_Stats => Algebra => Markov_Matrix => Markov_Matrix.cs
example :
> Added Markov_Matrix.cs

- Maths_And_Stats/MOs_Algorithm/MOs_Algorithm.c
#997 
C
1
Maths_And_Stats => MOs_Algorithm => MOs_Algorithm.c
> Created MOs_Algorithm.c

- Data_Structures/Queues/Priority Queue/priorityQueue.js
#994 
JavaScript
1
main folder => Data_Structures => Queues => Priority Queue => priorityQueue.js
> Added => Data_Structures => Queues => Priority Queue => JS

- Maths_And_Stats/Algebra/Factorial/factorial.sh
#860 
Bash
1
main folder => Maths_And_Stats => Algebra => Factorial => factorial.sh
> Added => Maths_And_Stats => Algebra => Factorial => Bash

- Algorithms/Recursion_Algorithm/Factorial.cs
#1027 
C#
1
Algorithms => Recursion_Algorithm => Factorial.cs
> Ari factorial

- Algorithms/Search_Algorithms/Fibonacci_Search/Fibonacci_search.java
- Data_Structures/Tree/AVL_Tree/AVL_Tree.py
>  Fibonacci_search.java

- Algorithms/Dynamic_Programming/Sudoku_Solver/Sudoku_Solver.cs
#694
C#
1
Algorithm => Dynamic_Programming => Sudoku_Solver => Sudoku_Solver.cs
> Added Sudoku_Solver.cs

- Algorithms/Sorting_Algorithms/Cocktail_Sort/Cocktail_Sort.c
#698 
C
1
Algorithms => Sorting_Algorithms => Cocktail_Sort => Cocktail_Sort.c
> Added => Algo => Cocktail Sort => C

- Algorithms/Sorting_Algorithms/Bubble_Sort/BubbleSort.scala
- Algorithms/Sorting_Algorithms/Selection_Sort/SelectionSort.scala
….scala
#862
Scala
1
Algorithms => Sorting_Algorithms =>Bubble_Sort => BubbleSort.scala
> Added => Algorithms => Sorting_Algorithms =>Bubble_Sort => Scala

- Algorithms/Dynamic_Programming/Minimum_Sum_Descent/min-sum.c
#940
C
1
Algorithm/Dynamic_Programming/Minimum_Sum_Descent/minsum.c
> added min-sum.c

- Maths_And_Stats/Statistics/Compound_Interest/Compound_Interest.html
I have added Compound_Interest.html file which consist of JavaScript code that will calculate Compound Interest by taking inputs dynamically from STANDARD INPUT.
#763 
JavaScript
1
Maths_And_Stats => Statistics => Compound_Interest => Compound_Interest.html
> Added => Maths_and_Stats => Statistics => Compound Interest => JS

- Algorithms/Dynamic_Programming/Minimum_Sum_Descent/minsum.cs
#940 
C#
1
Algorithms => Minimum_Sum_Descent => minsum.cs
> Created minsum.cs

- Data_Structures/Graph Algorithm/Kruskal_Algorithm.cpp
#726
C++
1
Data_Structures => Graph Algorithm => Kruskal_Algorithm.cpp
> Added => Data_Structures => Graph Algorithm => Kruskal_Algorithm.cpp

- Algorithms/Sorting_Algorithms/Pigeonhole_Sort/Pigeonhole_Sort.c
- Algorithms/Sorting_Algorithms/Pigeonhole_Sort/Pigeonhole_Sort.java
#964
C/Java
2
Algorithms => Sorting_Algorithms => Pigeonhole_Sort => Pigeonhole_Sort.java
Algorithms => Sorting_Algorithms => Pigeonhole_Sort => Pigeonhole_Sort.c
> Added Pigeonhole_Sort.java & Pigeonhole_Sort.c

- Data_Structures/Queues/Queue.rb
#494
Ruby
1
example :
Data_Structure => Queues => Queue.rb
> Added => DataStructure => Queue => Ruby

- Data_Structures/Maps_Hash_Dict/amicable.cs
#847 
C#/.NET
1
algo_ds_101 => Data_Structures => Maps_Hash_Dict => amicable.cs
> Amicable numbers csharp

- Maths_And_Stats/Series/Sum_of_N/sumOfNNumbers.sh
- Maths_And_Stats/Series/Sum_of_N3/SumOfN^3.py
#860
Bash
1
Maths_And_Stats=>Series=>Sum_of_N=>sumOfNNumbers.sh
> Bash script for sum of n numbers

- Maths_And_Stats/Series/Lucas_Series/Lucas_Series.go
Signed-off-by: parauliya <parauliya.aman@gmail.com>
#709 
Golang
1
Maths_And_Stats => Series => Lucas_Series => Lucas_Series.go
> Lucas Series in Golang

- Algorithms/Sorting_Algorithms/Pancake_Sort/Pancake_Sort.rb
#702
Ruby
1
Algorithm => Sorting_Programming => Pancake_Sort => Pancake_Sort.rb
> Added => Algo => Pancake_Sort => Ruby

- Algorithms/Sorting_Algorithms/Circle_Sort/Circle_Sort.rb
#703 
Ruby
1
Algorithm => Sort_Algorithms => Circle_Sort => Circle_Sort.py
> Added => Algo => Circle Sort => Ruby

- Algorithms/Sorting_Algorithms/Bubble_Sort/bubble_sort.sh
#860 
bash
1
Algorithms => Sorting_Algorithm => Bubble_Sort  => bubble_sort.sh
>  Algo => Sorting => Bubble_Sort  => bash

- Algorithms/Search_Algorithms/Linear_Search/linear_search.sh
#860
bash
1
Algorithms => Search_Algorithms => Linear_Search => linear_search.sh
> Added => Algo => Search =>Linear_Search => bash

- Algorithms/Dynamic_Programming/Sudoku_Solver/Sudoku_Solver.cpp
#694 
C++
1
Algorithm=>Dynamic_Programming=>Sudoku Solver=>Sudoku_Solver.cpp
example :
> Added=>Algorithm=>Dynamic_Programming=>Sudoku Solver=>C++

- Maths_And_Stats/Statistics/Compound_Interest/Compound_Interest.ts
#763 
Typescript
1
Maths_And_Stats => Statistics => Compound _Interest => Compound_Interest.ts
> Add Typescript solution to Compound Interest #763

- Algorithms/Sorting_Algorithms/Merge_Sort/non_recursive_merge_sort.py
#1036 
python3
1
Algorithms=>Sorting_Algorithms=>Merge_Sort=>non_recursive_merge_sort.py
example :
> Algorithms=>Sorting_Algorithms=>Merge_Sort=>non_recursive_merge_sort.py

- Algorithms/Sorting_Algorithms/Merge_Sort/Non_recursive_merge_sort.cpp
Assigned Issue Number ?
#1036 
C++
1
Algorithm => Sorting_Algorithms => Merge_sort => Non_recursive_merge_sort.cpp
Checklist
> Non recursive merge sort in C++

- Data_Structures/Stacks/balanced_brackets_stack.cpp
#007
c++
1
Data_Structures -> Stacks -> balanced brackets .cpp
example :
> created  stack  balanced brackets cpp file

- Algorithms/Sorting_Algorithms/Heap_Sort/Heap_Sort.swift
#653 
Swift
1
Algorithm => Sorting_Algorithm => Heap_Sort => Heap_Sort.swift
> Added => Algo => Heap_Sort => swift

- Algorithms/Backtracking/Nqueens.cpp
- Algorithms/Backtracking/Nqueens_optimized.cpp
#1039
C++
2
Algorithms=>Backtracking=>Nqueens.cpp
Algorithms=>Backtracking=>Nqueens_optimized.cpp
- [ Yes] I've read the contribution guidelines.
- [Yes ] I've referred the correct issue number.
- [ Yes] I've fill up this entire template correctly.
> Added=>Algorithms=>Backtracking=>Nqueens=>CPP 

- Algorithms/Dynamic_Programming/Largest_Sum_Contiguous_Subarray/.vscode/c_cpp_properties.json
- Algorithms/Dynamic_Programming/Largest_Sum_Contiguous_Subarray/.vscode/launch.json
- Algorithms/Dynamic_Programming/Largest_Sum_Contiguous_Subarray/.vscode/tasks.json
- Algorithms/Dynamic_Programming/Largest_Sum_Contiguous_Subarray/Kadane's Algorithm.cpp
#852 
C++
4
algo_ds_101 => Dynamic_Programming => Largest_Sum_Contiguous_Subarray => Kadane's Algorithm.cpp
> Added Kadane's Algorithm

- Algorithms/Sorting_Algorithms/Selection_Sort/SelectionSort.py
Updated code is faster and more efficient than the existing code.
#008
Python
1
algo_ds_101/Algorithms/Sorting_Algorithms/Selection_Sort/
> enhancement

- Algorithms/egg drop.java
#1045 
Java
1
Algorithms =>egg drop.java
- [YES ] I've read the contribution guidelines.
- [ YES] I've referred the correct issue number.
- [ YES] I've fill up this entire template correctly.
> egg drop.java

- Algorithms/Recaman's Sequence.c
#848 
C
1
Algorithm => Recaman's Sequence.c
- [YES ] I've read the contribution guidelines.
- [ YES] I've referred the correct issue number.
- [ YES] I've fill up this entire template correctly.
> Recaman's Sequence.c

- Data_Structures/Arrays/check_two_equal_array.cpp
- Data_Structures/Graph Algorithm/BFS_DFS_Graph.java
- Maths_And_Stats/Number_Theory/Prime Numbers upto N  and changing their base/prime_and_base.py
#007
C++,Python,Java
3
Data Structures => Array => check_two_equal_array.cpp
Data Structures => Graph_Algorithm => BFS_DFS_Graph.java
Data Structures => Array => check_two_equal_array.cpp
Maths_And_Stats=>Number_Theory=>Prime Numbers upto N  and changing their base=>prime_and_base.py
- [] I've referred the correct issue number.
> added 3 ds algo programs

- Algorithms/Dynamic_Programming/LIS/LIS.c
#686 
C
1
Algorithms => Dynamic_Programming => LIS => LIS.c
> Added => Algo => Longest Increasing Subsequence => C

- Algorithms/Search_Algorithms/Trie_Search/Trie1_HashMap.java
#685
Java
1
example :
Algorithm => Search_Algorithm => Trei_Search => Trie1_HashMap.java
> Added => Algo => Search_Algo => Trie_Search => Trie_HashMap

- CONTRIBUTORS.md
- Data_Structures/Linked_List/Singly_Linked_List/linked_list_cycle_detection.js
#737 
Javascript
1
algo_ds_101=>Data_Structures=>Linked_List=>Singly_Linked_List=>linked_list_cycle_detection.js
> Added detect cycle  linked list in javascript

- Algorithms/Dynamic_Programming/LIS/LongestIncreaseSubSequence.cpp
> adding LIS solution

- Algorithms/Sorting_Algorithms/Merge_Sort/non_recursive_merge_sort.cs
- Algorithms/Sorting_Algorithms/Shell_Sort/Shell_Sort.cs
#1036 
c#
1
Algorithm => Sorting_Algorithms => Merge_sort => non_recursive_merge_sort.cs
> non_recursive_merge_sort.cs

- Algorithms/Dynamic_Programming/Partition_Sum/partition_sum.c
- Algorithms/Dynamic_Programming/Partition_Sum/partition_sum.cpp
#1080 
C,C++
2
Algorithms => Dynamic_Programming => Partition_Sum => partition_sum.c , partition_sum.cpp
> Added => Algo => Partition Sum => C,C++

- Algorithms/Dynamic_Programming/Partition_Sum/partition_sum.php
#1080
PHP
1
Algorithms => Dynamic_Programming => Partition_Sum => partition_sum.php
example :
> PHP solution for the Partition Problem.

- Algorithms/Sorting_Algorithms/Shell_Sort/Shell_Sort.c
#649 
C
1
Algorithms => Sorting_Algorithms => Shell_Sort => Shell_Sort.c
example :
> Added => Algo => Shell Sort => Shell_Sort.c

- Data_Structures/Arrays/Merge-Sorted-Array.py
#1144 
Python
1
algo_ds_101 => Data_Structures => Arrays => Merge-Sorted-Array.py
-  [x] I've referred the correct issue number.
> Create  Merge-Sorted-Array.py

- Data_Structures/Arrays/Merge-Sorted-Array.cpp
#1144
C++
1
main folder => algo_ds_101 => Data_Structures => Arrays => Merge-Sorted-Array.cpp
> Added => Algo => Merge Sorted Array => CPP

- Algorithms/Cryptography_Algorithm/Affine_Cipher/Affine_Cipher.cpp
#661
C++
1
Algorithm => Cryptography_Algorithm => Affine_Cipher => Affine_Cipher.cpp
> Added different case and custom function support

- Algorithms/Backtracking/Crossword.cpp
#1091 
C++
1
Algorithm=>Backtracking=>Crossword.cpp
> Added=>Algorithm=>Backtracking=>Crossword.cpp

- Maths_And_Stats/Algebra/Factorial/Factorial.hs
- Maths_And_Stats/Algebra/Factorial_of_Large_Number/Factorial_of_Large_Number.hs
- Maths_And_Stats/Algebra/Quadratic_Formula/Quadratic_Formula.hs
#859
Haskell
3
Maths_And_Stats => Algebra => Factorial => Factorial.hs
Maths_And_Stats => Algebra => Factorial_of_Large_Number => Factorial_of_Large_Number.hs
Maths_And_Stats => Algebra => Quadratic_Formula => Quadratic_Formula.hs
> Added factorials and quadratic formula in Haskell

- Data_Structures/Deque/Deque.py
#911 
Python
1
Data_Structures => Deque => Deque.py
> Added => Data_structures => Deque => Deque.py

- Algorithms/Dynamic_Programming/Shortest_Common_Supersequence/shortest_common_supersequence.cpp
#1152 
C++
1
Algorithms => Dynamic_Programming => Shortest_Common_Supersequence => shortest_common_supersequence.cpp
> Added => Algo => Shortest Common Supersequence => C++

- Algorithms/Dynamic_Programming/LSCS/shortest_common_supersequence.c
#1152 
C
1
Added => Algorithm => LSCS =>shortest_common_supersequence.c
example :
> Added => Algorithm => LSCS => C

- Algorithms/Dynamic_Programming/AdjacentBitCounts.cpp
#1159 
C++
1
Algorithms => Dynamic_Programming => AdjacentBitCounts.cpp
> Adjacent Bit Counts

- Maths_And_Stats/Number_Theory/Segmented_Sieve/Segmented_Sieve.java
#1058
Java
1
Maths_And_Stats => Number_Theory => Segmented_Sieve=> Segmented_Sieve.java
> Added Maths_And_Stats => Number_Theory => Segmented_Sieve=> Segmented_Sieve.java

- Algorithms/Dynamic_Programming/Shortest_Common_Supersequence/shortest_common_supersequence.js
#1152
JavaScript
1
Algorithms => Dynamic_Programming => Shortest_Common_Supersequence => shortest_common_supersequence.js
> Added => Algo => Shortest Common Supersequence => Javascript

- Algorithms/Dynamic_Programming/Minimum_Sum_Descent/minsum.go
#940
Golang
1
Algorithm => Dynamic_Programming => Minimum_Sum_Descent => minsum.go
> Added => Algo => Minimum_Sum_Descent => Golang

- Algorithms/Dynamic_Programming/Minimum_Sum_Descent/minsum.ts
#940 
TypeScript
1
Algorithms => Dynamic_Programming => Minimum_Sum_Descent => minsum.ts
> Added implementation of Minimum Sum Descent in TypeScript

- Algorithms/Sorting_Algorithms/Insertion_Sort/InsertionSort.scala
- Algorithms/Sorting_Algorithms/Merge_Sort/MergeSort.scala
#862 
Scala
2
1. Algorithms => Sorting_Algorithms => Merge_Sort => MergeSort.scala
2. Algorithms => Sorting_Algorithms => Insertion_Sort => InsertionSort.scala
> Added Scala codes => MergeSort.scala and InsertionSort.scala

- Data_Structures/Tree/BTree/Btree.java
#980 
Java
1
Data_Structures => Tree => BTree => Btree.java
> added Btree.java

- Maths_And_Stats/Calculus/Euler_Approximation/Euler_Approximation.py
#690 
Python
1
Maths_And_Stats => Calculus => Euler_Approximation => Euler_Approximation.py
> Added  Euler_Approximation.py

- Algorithms/Cryptography_Algorithm/RSA_Cipher/RSA_cipher.java
#665
Java
1
Algorithm => Cryptography_Algorithm => RSA_Cipher => RSA_Cipher.java
> Added=>Algorithm => Cryptography_Algorithm => RSA_Cipher => RSA_Cipher.java

- Algorithms/Dynamic_Programming/LSCS/lscs.go
#1152
golang
1
Added => Algorithm => Dynamic Programming => LSCS => lscs.go
> feat(lscs) add golang code

- Algorithms/Dynamic_Programming/Shortest_Common_Supersequence/shortest_common_supersequence.py
#1152 
Python
1
Algorithms/Dynamic_Programming/Shortest_Common_Supersequence/shortest_common_sequence.py
> Shortest Common Super Sequence coded in Python3

- Algorithms/Dynamic_Programming/Shortest_Common_Supersequence/shortest_common_sequence.java
#1152 
Java
1
Algorithms/Dynamic_Programming/Shortest_Common_Supersequence/shortest_common_sequence.java
> Java code Added

- Data_Structures/Arrays/Merge-Sorted-Array.js
#1144 
javascript
1
main folder => algo_ds_101 => Data_Structures => Arrays => Merge-Sorted-Array.js
example :
> Adding Merge_sorted_array Algorithm

- Algorithms/String_Algorithms/anagram.c
#1151 
C
1
algo_ds_101\Algorithms\String_Algorithms\anagram.c
- [y ] I've read the contribution guidelines.
- [ y] I've referred the correct issue number.
- [y ] I've fill up this entire template correctly.
> Algorithm=>String Algorithms => anagram.c 

- Algorithms/Tree_Algorithms/Min Heap Construction/QUESTION.md
- Algorithms/Tree_Algorithms/Min Heap Construction/min-heap-construc.py
#1115
Python
2
algo_ds_101 => Algorithms => Tree_Algorithms => Min Heap Construction => min-heap-construc.py 
algo_ds_101 => Algorithms => Tree_Algorithms => Min Heap Construction => QUESTION.md
example :
> Added solution for Min Heap Construction 

- Algorithms/Sorting_Algorithms/Shell_Sort/shell_sort.sh
#860 
Shell Script
1
Algorithms => Sorting_Algorithms =>Shell_Sort => shell_sort.sh
> Algorithms=>Sorting_Algorithms=>Shell_Sort=>sh

- STL/Map/map.cpp
#007
c++
1
algo_ds => STL =>Map=> map.cpp
example :
> Created map.cpp in MAP STL

- Algorithms/Recursion_Algorithm/Combination_Sum/Combination_Sum.php
#968 
php
1
Algorithms => Recursion_Algorithm => Combination_Sum => Combination_Sum.php
>  Algorithms => Recursion_Algorithm => Combination_Sum => php

- Data_Structures/Red Black Tree.py
#1124 
Python
1
Data structures => Red Black Tree.py
- [YES ] I've read the contribution guidelines.
- [YES ] I've referred the correct issue number.
- [YES ] I've fill up this entire template correctly.
> Red Black Tree.py

- Data_Structures/Maps_Hash_Dict/amicable.swift
#847
Swift
1
Data Structure => Maps Hash Dict => amicable.swift
> Added Data Structure => Maps Hash Dict => Amicable Numbers

- Data_Structures/Maps_Hash_Dict/recaman_sequence.cpp
#848 
C++
1
Data_Structures => Maps_Hash_Dict => recaman_sequence.cpp
> recaman_sequence in c++

- Data_Structures/Arrays/InsertArray.c
C program to insert elements in array in sorted order.
C
1.
main folder => Data Structure => Arrays => InsertArray.cpp
- [*] I've referred the correct issue number.
- [*] I've fill up this entire template correctly.
> Added InsertArray.c

- Algorithms/Sorting_Algorithms/Shell_Sort/Shell_Sort.java
#649 
Java
1
Algorithm => Sorting_Algorithm => Shell_Sort => Shell_Sort.java
> Added => Algorithms => Sorting_Algorithms => Shell_Sort => Java

- Maths_And_Stats/Algebra/Factorial/factorial.swift
> adding factorial in swift

- Algorithms/Graph_Algorithms/A_Star/A_star.cs
#597
C#
1
Algorithms => Graph_Algorithms => A_Star => A_star.cs
example :
> Added A_star.cs

- Data_Structures/Arrays/counting_frequency_of_char_in_string.c
> added counting_frequency_of_char_in_string.c

- Maths_And_Stats/Segmented_Sieve/Segmented_Sieve.php
#1058
PHP
1
Maths_And_Stats => Segmented_Sieve => Segmented_Sieve.php
example :
> PHP solution for the Sieve of Eratosthenes.

- Algorithms/Sorting_Algorithms/Cocktail_Sort/cocktail_sort.js
#698 
JavaScript
1
Algorithms => Sorting_Algorithms => Cocktail_Sort => cocktail_sort.js
> Algorithms=>Sorting_Algorithms=>Cocktail_Sort=>js

- Data_Structures/Maps_Hash_Dict/DivisiblePairCount.js
> Maps_Hash_Dict => DivisiblePairCount.js

- STL/Deque/dequeue.cpp
- STL/Heap/heap.cpp
- STL/Map/README.md
- STL/Map/map.cpp
- STL/Priority Queue/priority_queue.cpp
- STL/Queue/Queue.cpp
- STL/README.md
- STL/Set/set.cpp
- STL/Stack/stack.cpp
- STL/Vector/Vector.cpp
#007
3
STL 
example :
STL => Heaps, Priority_queue
> added some data structures in STL.

- Algorithms/Dynamic_Programming/Scramble Strings/ScrambleString.cpp
#942 
C++
1/2/3/4/...
Algorithm =>Dynamic_Programming=>ScrambleString=>ScrambledStrings.cpp
example :
> ScrambleStrings

- Maths_And_Stats/Calculus/Runge–Kutta_Method/Runge-Kutta.py
Please apply _hacktoberfest-accepted_ label to this pull request in case of being accepted.
#395
Python
1
Maths_And_Stats => Calculus => Runge–Kutta_Method => Runge–Kutta_Method.py
example :
Maths_And_Stats => Calculus => Euler-Methods => .py
> Add Runge-kutta in Python.

- Algorithms/Graph_Algorithms/Youngest Common Ancestor/QUESTION.md
- Algorithms/Graph_Algorithms/Youngest Common Ancestor/youngest-comm-anc.py
#1174 
Python
2
algo_ds_101 => Algorithms => Graph Algorithms => Youngest_Common_Ancestor => youngest-comm-anc.py
algo_ds_101 => Algorithms => Graph Algorithms => Youngest_Common_Ancestor => QUESTION.md
example :
> algo_ds_101 => Algorithms => Graph Algorithms => Youngest_Common_Ancestor #1174

- Data_Structures/Linked_List/Doubly_Linked_List/Doubly_Linked_List.py
#1132
Python
1
algo_ds_101 => Data Structures => Linked_List => Doubly_Linked_List =>Doubly_Linked_List.py
example :
> algo_ds_101 => Data Structures => Linked_List => Doubly_Linked_List #1132

- Data_Structures/Arrays/merge-sorted-arrays-algo-only.py
#1144
Python
1
algo_ds_101 => Data Structures => Arrays => merge-sorted-arrays-algo-only.py
example :
> algo_ds_101 => Data Structures => Arrays #1144

- Maths_And_Stats/Number_Theory/Segmented_Sieve/segmented_sieve.py
#1058 
I have implemented the segmented sieve code for Python language
1
Maths_And_Stats => Number_Theory => Segmented_Sieve => segmented_sieve.py
> added segmented_sieve.py

- Algorithms/Tree_Algorithms/Min Heap Construction/min-heap-construc.cpp
#1115
Python
1
algo_ds_101 => Data Structures => Tree_Algorithms =>  Min_Heap_Construction => min-heap-construc.cpp
example :
> algo_ds_101 => Data Structures => Tree_Algorithms =>  Min_Heap_Construction #1115

- Algorithms/Search_Algorithms/Fibonacci_Search/fibonacci_search.c
Fibonacci Search in C
#007
C
1
fibonacci_search.c
example :
Algorithm => Search_Algorithm => Fibonacci Search=> fibonacci_search.c
> Fibonacci Search in C

- Maths_and_Stats/Algebra/Factorial/factorial_of_a_no.golang
#1175
GO
1
Added=>Maths_and_Stats=>Factorial=>factorial_of_a_no.golang
example :
> Added=>Maths_and_Stats=>Factorial=>GO

- Algorithms/Dynamic_Programming/Egg_Drop/egg_drop.ts
#1045 
TypeScript
1
Algorithms => Dynamic_Programming => Egg_Drop => egg_drop.ts
> TypeScript Implemention of Egg Drop Puzzle

- Algorithms/Dynamic_Programming/Count_Square_Matrices.py
#1160 
Python
1
Algorithms => Dynamic_Programming => Count_Square_Matrices.py
example :
> Added => Algorithms => Dynamic_Programming => Count_Square_Matrices.py

- Data_Structures/Linked_List/Doubly_Linked_List/DoublyLinkedList.cs
#1132 
C#
1
Data_Structures => Linked_List=>Doubly_Linked_List=>DoublyLinkedList.cs
> Adding DoublyLinkedList.cs

- Algorithms/Dynamic_Programming/AdjacentBitCounts.js
#1159
JavaScript
1
Algorithms => Dynamic_Programming => AdjacentBitCounts.js
> Added => Algorithms => Dynamic_Programming => AdjacentBitCounts.js

- Algorithms/Sorting_Algorithms/Topological_Sort/Topological_sort.cs
#1140 
C#
1
main folder => Algorithm => Sorting_Algorithm=> Topological_sort => Topological_sort.cs
example :
> adding Topological_sort in c#

- algo_ds_101/Data_Structures/Linked_List/Doubly_Linked_List/doubly.c
#1132 
C
1
Added=>Data_Structures=>Doubly_linked_list=>doublylinkedlist.c
example :
- [Y ] I've read the contribution guidelines.
- [Y ] I've referred the correct issue number.
- [Y ] I've fill up this entire template correctly.
> Added=>Data_Structures=>Doubly_linked_list=>C

- Data_Structures/Tree/23Tree/23Tree.cpp
#1233 
C++
1
Data_Structures => Tree => 23Tree => 23Tree.cpp
> Added => Data_Structures => Tree => 23Tree => 23Tree.cpp

- Algorithms/Graph_Algorithms/Flood_Fill/Flood_Fill.cpp
#1232 
C++
1
Algorithms=> Graph_Algorithms=> Flood_Fill => Flood_Fill.cpp
example :
Algorithm => Search_Algorithm => Linear_Search => Linear_Search.cpp
> Added => Algorithms => Graph_Algorithms => Flood_Fill => Flood_Fill.cpp

- Algorithms/Sorting_Algorithms/Wave_Sort/Wave_Sort.py
#1227 
Python
1
Algorithms => Sorting_Algorithms => Wave_Sort => Wave_Sort.py
example :
> Added => Algorithms => Sorting_Algorithms => Wave_Sort => Wave_Sort.py

- Data_Structures/Maps_Hash_Dict/Cuckoo_Hashing.cpp
Added Cuckoo_Hashing.cpp file which will perform Cuckoo hashing on numbers entered dynamically.
#846 
C++
1
Data_Structures => Maps_Hash_Dict => Cuckoo_Hashing.cpp
> Added => Data_Structures => Maps_Hash_Dict => Cuckoo_Hashing => CPP

- Algorithms/Recursion_Algorithm/Permutation.js
#1211
JavaScript
1
Algorithm=>Recursion_Algorithm=>Permutation.js
> Permutation in JavaScript using Recursion

- Maths_And_Stats/Calculus/Euler_Approximation/Euler_Approximation.c
#690 
C
1
Maths_And_Stats => Calculus => Euler_Approximation => Euler_Approximation.c
> Maths_And_Stats => Calculus => Euler_Approximation => Euler_Approximation.c

- Data_Structures/Stacks/operationsOnStacks.c
Push, Pop, Peek are the main operations that can be performed in a stack.
This is a menu driven program written in C .
It gives the user the option to Push or Pop.
I'm a newbie when it comes to Open Source Contribution :)
#007
1/2/3/4/...
example :
> Operations on Stack

- Data_Structures/Tree/Red_Black_Tree/tree.java
#1124 
Java
1
Data_Structures/Tree/Red_Black_Tree/tree.java
> RED BLACK TREE IN JAVA

- Algorithms/Graph_Algorithms/Topological sort/README.md
- Algorithms/Graph_Algorithms/Topological sort/Topological_sort.cpp
#1140 
C++
2
algo_ds_101 => Algorithms => Graph_Algorithms => Topological Sort => Topological_Sort.cpp + README.md
example :
> Ashima0699

- Algorithms/Recursion_Algorithm/Permutation.ts
#1211
TypeScript
1
Algorithm=>Recursion_Algorithm=>Permutation.ts
> Permutation in TypeScript using Recursion

- Data_Structures/Linked_List/Singly_Linked_List/ReversedLinkedList.js
#1186 
JavaScript
1
Data Structures => Linked List => Singly Linked List => ReversedLinkedList.js
- [+] I've read the contribution guidelines.
- [+ ] I've referred the correct issue number.
- [ +] I've fill up this entire template correctly.
> Added => Data Structures => Linked List => Singly Linked List => Reverse => JS

- Algorithms/Recursion_Algorithm/Permutation.cs
#1211 
C#
1
Algorithms=> Recursion_Algorithm=> Permutation.cs
> Adding Permutation.cs in Resursion_Algorithm folder

- Algorithms/Graph_Algorithms/Topological Sort/QUESTION.md
- Algorithms/Graph_Algorithms/Topological Sort/topo_sort.py
#1140 
Python
2
algo_ds_101 => Algorithms => Graph_Algorithms => Topological Sort => QUESTION.md
algo_ds_101 => Algorithms => Graph_Algorithms => Topological Sort => topo_sort.py
example :
> algo_ds_101 => Algorithms => Graph_Algorithms => Topological Sort 

- Maths_And_Stats/Number_Theory/Extended Euclidean Algorithm/extendEuclid.cpp
- Maths_And_Stats/Number_Theory/Extended Euclidean Algorithm/extendEuclid.py
#007
Python...
1...
Maths_And_Stats => Number Theory => Extended Euclidean Algorithm => extendEuclid.py
example :
Added  Maths_And_Stats => Number Theory => Extended Euclidean Algorithm => extendEuclid.py
> Added  Maths_And_Stats => Number Theory => Extended Euclidean Algorithm => extendEuclid.py

- Algorithms/Graph_Algorithms/Flood_Fill/Flood_Fill.js
#1232 
Javascript
1
Algorithms => Graph_Algorithms => Flood_Fill => Flood_Fill.js
> Added Algorithms => Graph_Algorithms => Flood_Fill => Flood_Fill.js

- Algorithms/Search_Algorithms/Exponential_Search/exponential_search.cpp
- Algorithms/Search_Algorithms/Exponential_Search/exponential_search.php
- Algorithms/Search_Algorithms/Sublist_Search/sublist_search.cpp
- Algorithms/Search_Algorithms/Sublist_Search/sublist_search.java
- Algorithms/Search_Algorithms/Sublist_Search/sublist_search.py
- Data_Structures/Linked_List/Singly_Linked_List/LoopDetection.cpp
#1295 
#1273 
#737 
C++/Python/Java/PHP
6
Algorithm => Search_Algorithm => Exponential_Search => exponential_search.cpp
Algorithm => Search_Algorithm => Exponential_Search => exponential_search.php
Algorithm => Search_Algorithm => Sublist_Search => sublist_search.cpp
Algorithm => Search_Algorithm => Sublist_Search => sublist_search.java
Algorithm => Search_Algorithm => Sublist_Search => sublist_search.py
Data_Structures => Linked_List => Singly_Linked_List => LoopDetection.cpp
example :
> Adding Exponential Search and Sublist Search and Loop Detection in Single Linked List

- Data_Structures/Maps_Hash_Dict/Brick_Wall/Brick_wall.cpp
- Data_Structures/Maps_Hash_Dict/Brick_Wall/QUESTION.md
#1254 
C++
2
Data_Structures => Maps_Hash_Dict => Brick_Wall => Brick_wall.cpp
Data_Structures => Maps_Hash_Dict => Brick_Wall => QUESTION.md
example :
> Data_Structures => Maps_Hash_Dict => Brick_Wall

- Algorithms/Cryptography_Algorithm/Affine_Cipher/affine_cipher.c
#661 
C
1
Algorithm=>Cryptography_Algorithm=>Affine_Cipher=>Affine_Cipher.c
example :
> Algorithm=>Cryptography_Algorithm=>Affine_Cipher=>Affine_Cipher.c

- Algorithms/Search_Algorithms/Binary_Search/Rotated-Sorted-Array-Search.cs
#1217 
C#
1
algo_ds_101 => Algorithms => Search_Algorithms => Binary_Search => Rotated-Sorted-Array-Search.cs
> added Rotated-Sorted-Array-Search.cs

- Algorithms/Recursion_Algorithm/Permutations_Recursion.py
#1211 
Python
1
Algorithms => Recursion_Algorithm => Permutations_Recursion.py
example :
> Added => Algorithms=> Recursion_Algorithm=> Permutations_Recursion.py

- right_view_of_binary_tree.cpp
#1247 
C++
1
algo_ds_101 => Data Structures => Tree => Binary_Tree => Right_View => right_view_of_binary_tree.cpp
> Added => Data Structures => Tree => Binary_Tree => Right_View => right_view_of_binary_tree.cpp

- floyd_cycle_detection.cpp
#1230 
C++
1
algo_ds_101 => Data structures=> Linked_List => Floyd_Cycle_Detection => floyd_cycle_detection.cpp
> Added => Data structures=> Linked_List => Floyd_Cycle_Detection => floyd_cycle_detection.cpp

- Algorithms/Tree_Algorithms/Max_Path_Sum_BST/Max_Path_Sum_BST.py
#1226 
Python
1
algo_ds_101 => Algorithms => Tree_Algorithms => Max_Path_Sum_BST => Max_Path_Sum_BST.py
> algo_ds_101 => Algorithms => Tree_Algorithms => Max_Path_Sum_BST => Max_Path_Sum_BST.py

- Algorithms/Sorting_Algorithms/Wave_Sort/wave_sort.cpp
#1227 
C++
1
algo_ds_101 => Algorithms => Sorting_Algorithms => Wave_Sort => Wave_Sort.cpp
> algo_ds_101 => Algorithms => Sorting_Algorithms => Wave_Sort => Wave_Sort.cpp

- Data_Structures/Linked_List/Singly_Linked_List/Delete_Kth_Node_From_End/Delete_Kth_Node_From_End.java
#1260
Java
1
Data_Structures => Linked_List => Singly_Linked_List => Delete_Kth_Node_From_End => Delete_Kth_Node_From_End.java
> Added => Data_Structures => Linked_List => Singly_Linked_List => Delete_Kth_Node_From_End => Delete_Kth_Node_From_End.java

- Algorithms/Tree_Algorithms/Max_Path_Sum_BST/Max_Path_Sum_BST.cpp
…Path_Sum_BST.cpp
#1226 
C++
1
algo_ds_101 => Algorithms => Tree_Algorithms =>Max_Path_Sum_BST=>Max_Path_Sum_BST.cpp
example :
> algo_ds_101 => Algorithms => Tree_Algorithms =>Max_Path_Sum_BST=>Max_Path_Sum_BST.cpp

- Algorithms/Dynamic_Programming/Water_Area/QUESTION.md
- Algorithms/Dynamic_Programming/Water_Area/Water-area.py
#1246 
Python
2
algo_ds_101 => Algorithms => Dynamic_Programming => Water_Area => Water_area.ext
example :
> algo_ds_101 => Algorithms => Dynamic_Programming => Water_Area #1246

- Data_Structures/Tree/Binary_Tree/DensityBtree.c
#1249 
C
1
algo_ds_101 => Data_Structures => Tree => BinaryTree => DensityBtree.c
> algo_ds_101 => Data_Structures => Tree => BTree => DensityBTree.c

- invert_binary_tree.cpp
#1225 
C++
1
algo_ds_101 => Data Structures => Tree => Binary Tree => Invert_Binary_Tree => invert_binary_tree.cpp
> Added => Data Structures => Tree => Binary Tree => invert_binary_tree.cpp

- Data_Structures/Tree/Binary_Tree/subtree_check.cpp
#1286 
C++
1
Data_Structures => Tree => Binary_Tree => subtree_check.cpp
example :
> Data_Structures => Tree => Binary_Tree => Subtree_check.cpp

- Algorithms/Search_Algorithms/Sublist_Search/sublist_search.cs
#1295 
C#
1
Algorithms => Search_Algorithms => Sublist_Search => sublist_search.cs
> added sublist_search.cs

- Data_Structures/Linked_List/Singly_Linked_List/Delete_Kth_Node_From_End/Delete_Kth_Node_From_End.rb
#1260 
Ruby
1
Data_Structures => Linked_List => Singly_Linked_List => Delete_Kth_Node_From_End => Delete_Kth_Node_From_End.rb
> Remove kth Node From End of Linked List

- Algorithms/Tree_Algorithms/Min_Heap_Construction/Min_Heap.c
> Add min heap in c language

- Data_Structures/Tree/Binary_Tree/DensityBtree.cpp
- Data_Structures/Tree/Binary_Tree/RightViewBTree.java
#1247 
Java
2.
algo_ds_101 => Data_Structures => Tree=> BTree => RightViewBtree.java
>  algo_ds_101 => Data_Structures => Tree=> BTree => RightViewBtree.java

- Data_Structures/Tree/Binary_Tree/DensityBtree.cpp
#1249 
C++
1
algo_ds_101 => Data_Structures => Tree => BTree => DensityBTree.cpp
> algo_ds_101 => Data_Structures => Tree => BTree => DensityBTree.cpp

- Algorithms/Tree_Algorithms/Max_Heap_Construction/minmaxheap.cpp
C++
1
Algorithms/Tree Algorithms/Max_Heap_Construction/maxminheap.cpp
> Added Algorithms/Tree Algorithms/Max_Heap_Construction/maxminheap.cpp

- Algorithms/Sorting_Algorithms/Wave_Sort/wave_sort.c
#1227 
C
1
Algorithms => Sorting_Algorithms => Wave_Sort => Wave_Sort.c
> Algorithms => Sorting_Algorithms => Wave_Sort => Wave_Sort.c

- Data_Structures/Linked_List/Singly_Linked_List/Delete_Kth_Node_From_End.cpp
- Data_Structures/Linked_List/Singly_Linked_List/Delete_Kth_Node_From_End.py
C++...
1...
Data_Structures => Linked_List => Singly_Linked_List => Delete_Kth_Node_From_End.cpp
example :
Data_Structures => Linked_List => Singly_Linked_List => Delete_Kth_Node_From_End.cpp
> added Delete_Kth_Node_From_End.cpp

- permutations.cpp
#1314 
C++
1
algo_ds_101 => Algorithms => Backtracking => permutations.cpp
> Added => Algorithms => Backtracking => permutations.cpp

- Algorithms/Sorting_Algorithms/3-Way_Quick_Sort/3-Way_Quick_Sort.cs
#1241 
C#
1
Algorithms/Sorting_Algorithms/3-Way_Quick_Sort/3-Way_Quick_Sort.cs
> 3-Way quick sort added in c#

- Data_Structures/Maps_Hash_Dict/Amicable_Number.rb
#847
Ruby
1
Data_Structures => Maps_Hash_Dict => Amicable_Number.rb
> Added Data_Structures => Maps_Hash_Dict => Amicable_Number.rb

- Maths_And_Stats/Number_Theory/Segmented_Sieve/segmented_sieve.js
#1058 
JavaScript
1
Maths_And_Stats => Number_Theory => Segmented_Sieve=> Segmented_Sieve.js
> added segmented_sieve.js

- Algorithms/Graph_Algorithms/Lowest_Common_Manager/Lowest_Common_Manager.py
- Algorithms/Graph_Algorithms/Lowest_Common_Manager/QUESTION.md
- Algorithms/Tree_Algorithms/Max_Path_Sum_BST/Max_Path_Sum_BST.py
#1224
Python, Markdown
2
algo_ds_101 => Algorithms => Graph_Algorithms => Lowest_Common_Manager => Lowest_Common_Manager.py
algo_ds_101 => Algorithms => Graph_Algorithms => Lowest_Common_Manager => QUESTION.md
> algo_ds_101 => Algorithms => Graph_Algorithms => Lowest_Common_Manager #1224

- Algorithms/Graph_Algorithms/Flood_Fill/flood_fill_algorithm.cs
- Data_Structures/Tree/Binary_Search_Tree/subtree_check/Subtree_check.cpp
#1286
C++.
1
Data_Structures => Tree => Binary_Tree =>subtree_check=>subtree_check.cpp
> Added => Data_Structures => Tree => Binary_Tree =>subtree_check=> subtree_check.cpp

- Algorithms/Sorting_Algorithms/Bubble_Sort/Bubble_Sort.cs
#1172 
C#
1
algo_ds_101 => Algorithms => Sorting_Algorithms => Bubble_Sort => Bubble_Sort.cs
> Added =>  Algorithms => Sorting_Algorithms => Bubble_Sort => Bubble_Sort.cs

- Data_Structures/Linked_List/Doubly_Linked_List/doubly_ll.py
- Data_Structures/Queue/Priority_Queue/PriorityQueue.py
> Priority_Queue_using_python

- Algorithms/Search_Algorithms/Sublist_Search/Sublist_Search.php
#1295 
php
1
Algorithms => Search_Algorithms => Sublist_Search => Sublist_Search.php
> Algorithms => Search_Algorithms => Sublist_Search => php

- Data_Structures/Tree/Binary_Tree/Deserialize/Deserialize.cpp
#1332
C++
1
Tree=>Binary_Tree=>Deserialize=>Deserialize.cpp
> Deserialize a binary tree

- Algorithms/Cryptography_Algorithm/RSA_Cipher/RSA_cipher.cpp
#665
C++
1
Algorithm => Cryptography_Algorithm => RSA_Cipher => RSA_cipher.cpp
example :
> cppfileadded

- Algorithms/Search_Algorithms/Binary_Search/Koko_Eating_Bananas/Koko_Eating_Bananas.cpp
- Algorithms/Search_Algorithms/Binary_Search/Koko_Eating_Bananas/QUESTION.md
#1310 
C++
2
Algorithms => Search_Algorithms => Binary_Search => Koko_Eating_Bananas => Koko_Eating_Bananas.cpp
Algorithms => Search_Algorithms => Binary_Search => Koko_Eating_Bananas => QUESTION.md
example :
> added question and cpp solution to problem

- Data_Structures/Queue/Priority_Queue/PriorityQueueBysid1207.cpp
#994 
C
1
Data_Structures=>Queue=>PriorityQueue=>priorityQueueBysid1207.cpp
> Added=>Data_Structures=>Queue=>PriorityQueue=>CPP

- Algorithms/Backtracking/permutation.py
#007
Python
1
Algorithms => Backtracking => permutations.py
example :
-  I've read the contribution guidelines.
-  I've referred the correct issue number.
-  I've fill up this entire template correctly.
> Added => Algo => Permutation => Python3

- Algorithms/Tree_Algorithms/LCA/LCA.cpp
#1327 
C++
1
Algorithms => Tree_Algorithms => LCA => LCA.cpp
> Lowest Common Ancestor of a Binary Tree

- Data_Structures/Linked_List/detect_cycle.cpp
#1311 
C++
1
algo_ds_101 => Data_Structures => LinkedList => detect_cycle.cpp
example :
> Added detect_cycle.cpp

- Algorithms/Backtracking/Permutations.c
#1314 
C
1
Algorithms => Backtracking => Permutations.c
example :
> Algorithms => Backtracking => Permutations.c

- Data_Structures/Tree/Binary_Tree/Two_level_Node.java
#1285 
java
1
Data_Structures => Tree => Binary_Tree =>Two_level_Node.java
> Added Data_Structures => Tree => Binary_Tree =>Two_level_Node.java

- Data_Structures/Tree/Binary_Tree/Two_level_Node/two_level_Node.cpp
Data_Structures => Tree => Binary_Tree => Two_level_Node =>Two_level_Node.cpp
> Added Data_Structures => Tree => Binary_Tree => Two_level_Node =>Two_level_Node.cpp

- Data_Structures/Tree/Binary_Tree/Check_duplicates_in _BTree.java
- Data_Structures/Tree/Binary_Tree/SymmetricBTree.java
#1339 
Java.
2
algo_ds_101 => Data_Structures => Tree => Binary_Tree => SymmetricBTree.java
> Added => Data_Structures => Tree => Binary_Tree => SymmetricBTree.java

- Data_Structures/Tree/Binary_Tree/Check_duplicates_in _BTree.java
#1330 
Java/...
1
algo_ds_101 => Data_Structures => Tree => Binary_Tree=> Check_duplicate_BTree.java
> Added => Data_Structures => Tree => Binary_Tree=> Check_duplicate_BTree.java

- Data_Structures/Tree/Binary_Tree/Deserialize/Deserialize.rb
#1332
Ruby
added 1 file
Data_Structures => Tree => Binary_Tree => Deserialize => Deserialize.rb
> Added => Data_Structures => Tree => Binary_Tree => Deserialize => Deserialize.rb

- Algorithms/Backtracking/permutations.js
#1314 
JavaScript
1
Algorithms => Backtracking => permutations.js
> added permutations.js

- Algorithms/Sorting_Algorithms/Strand_Sort/README.md
- Algorithms/Sorting_Algorithms/Strand_Sort/Strand_Sort.cpp
#1353 
C++
2
Algorithms => Sorting_Algorithms => Strand_Sort => Strand_Sort.cpp
Algorithms => Sorting_Algorithms => Strand_Sort => README.md
example :
> Adding solution for Strand Sort

- Algorithms/String_Algorithms/LPS/longest_palindromic_substring.rb
#1337
Ruby
1
algo_ds_101 => Algorithms => String_Algorithms => LPS => longest_palindromic_substring.rb
> Added => Algorithms => String_Algorithms => LPS => longest_palindromic_substring.rb

- Data_Structures/Tree/Binary_Tree/symmetry_bTree.cpp
#1339 
C++
1
algo_ds_101 => Data_Structures => Tree => Binary_Tree => symmetry_bTree.cpp
> Added =>  Data_Structures => Tree => Binary_Tree => symmetry_bTree.cpp

- Algorithms/Search_Algorithms/Sublist_Search/sublist_search.js
#1295
JavaScript
1
example :
Algorithms => Search_Algorithms => Sublist_Search => sublist_search.js
> Added => Algo => search_algorithms => sublist_search => JS

- Data_Structures/Maps_Hash_Dict/Group_Anagrams/Group_Anagrams.cpp
- Data_Structures/Maps_Hash_Dict/Group_Anagrams/QUESTIONS.md
#1368 
C++
2
Data_Structures => Maps_Hash_Dict => Group_Anagrams => Group_Anagrams.cpp
Data_Structures => Maps_Hash_Dict => Group_Anagrams => QUESTIONS.md
example :
> Data_Structures => Maps_Hash_Dict => Group_Anagrams

- Algorithms/Tree_Algorithms/LCA/LCA.py
#1327 
Python
1
Algorithms => Tree_Algorithms => LCA => LCA.py
> LCA|Python

- Algorithms/Graph_Algorithms/Youngest_Common_Ancestor/YoungestCommonAncestor.java
… YoungestCommonAncestor.java
#1174
Java
1
Algorithms=> Graph_Algorithms => Youngest_Common_Ancestor => YoungestCommonAncestor.java
> Added => Algorithms=> Graph_Algorithms => Youngest_Common_Ancestor => YoungestCommonAncestor.java

- Data_Structures/Tree/Binary_Tree/SymmetryBTree/SymmetryBTree.rb
Given a binary tree, check whether it is a mirror of itself.
#1339
Ruby
added 1
Data_Structures => Tree => Binary_Tree => SymmetryBTree => SymmetryBTree.rb
> Added => Data_Structures => Tree => Binary_Tree => SymmetryBTree => SymmetryBTree.rb

- Maths_And_Stats/Algebra/Babylionian/Babylionian.go
#1374 
golang
1
Maths_And_Stats =>Algebra=> Babylionian=>Babylionian.go
- [yes ] I've read the contribution guidelines.
- [ yes] I've referred the correct issue number.
- [ yes] I've fill up this entire template correctly.
> Maths_And_Stats =>Algebra=> Babylionian=>Babylionian.go

- Maths_And_Stats/Algebra/Babylonian/babylonian_square_root.c
#1374 
C
1
Maths_And_Stats => Algebra => Babylonian => babylonian_square_root.c
- [Y ] I've read the contribution guidelines.
- [Y ] I've referred the correct issue number.
- [Y ] I've fill up this entire template correctly.
> Babylonian Method to find Square Root in C is added.

- Data_Structures/Graph/UsingList.py
python
#1359
Python
1
Data_Structures => Graph => UsingList.py
- [*] I've referred the correct issue number.
- [* ] I've fill up this entire template correctly.
> undirected graph implementation with adjacent list approach in python

- Algorithms/Sorting_Algorithms/Strand_Sort/Strand_sort.java
Strand sort in java added
#1353 
Java
1
Algorithms => Sorting_Algorithms => Strand_Sort => Strand_sort.java
example :
> Strand sort

- CONTRIBUTORS.md
- Data_Structures/Linked_List/Singly_Linked_List/Sublist_Search.rb
#1295
Ruby
1
Data Structures => Linked_List => Singly_Linked_List => Sublist_Search.rb
> added Data Structures => Linked_List => Singly_Linked_List => Sublist_Search.rb

- Data_Structures/LinkedList/detect_cycle.go
#1311
Golang
1
algo_ds_101 => Data_Structures => LinkedList => detect_cycle.go
>  Check for closed loop using Floyd's cycle algorithm [ Golang ] 

- Data_Structures/Linked_List/detect_cycle.cs
#1311 
C#
1
algo_ds_101 => Data_Structures => LinkedList => detect_cycle.cs
> Added Floyd cycle detection implementation with C#

- Data_Structures/Linked_List/Floyd_Cylce_detectiom/floyd_cycle_detection.java
#1311
Java
1
algo_ds_101 => Data_Structures => LinkedList => Floyd_Cylce_detectiom => floyd_cycle_detection.java
- [✔] I've read the contribution guidelines.
- [✔] I've referred the correct issue number.
- [✔] I've fill up this entire template correctly.
> Added Floyd’s Cycle-Finding Algorithm

- Data_Structures/Tree/Binary_Tree/Serialize/Serialize.cpp
Assigned Issue Number ?
#1331
C++
1
Tree=>Binary_Tree=>Serialize=>Serialize.cpp
Checklist
[y] I've read the contribution guidelines.
[y] I've referred the correct issue number.
[y] I've fill up this entire template correctly.
> Added Serialize.cpp

- Algorithms/Dynamic_Programming/0-1_Knapsack_Problem/Branch_And_Bound/0-1_knapsack.cpp
#1335
C++
1
algo_ds_101 => Algorithm => Dynamic_Programming => Branch_And_Bound => 0/1_KnapSack.cpp
> Added algo_ds_101 => Algorithm => Dynamic_Programming => Branch_And_Bound => 0/1_KnapSack.cpp

- Algorithms/String_Algorithms/LPS/longest_palindromic_substring.py
- Data_Structures/Tree/Binary_Tree/SymmetryBTree.py
#1337 
Python
1
Algorithms => String_Algorithms => LPS => longest_palindromic_substring.py
> Longest Palindromic Substring (LPS)

- CONTRIBUTORS.md
- Data_Structures/Tree/Binary_Tree/duplicate_values.rb
#1330
Ruby
1
Data Structures => Tree => Binary_Tree => duplicate_values.rb
> added Data Structures => Tree => Binary_Tree => duplicate_values.rb

- CONTRIBUTORS.md
- Data_Structures/Tree/Binary_Tree/Invert_Binary_Tree/invertBinTree.rb
#1225 
Ruby
1
Data Structures => Tree => Binary_Tree => Invert_Binary_Tree => invertBinTree.rb
> added Data Structures => Tree => Binary_Tree => Invert_Binary_Tree => invertBinTree.rb

- Algorithms/Graph_Algorithms/Kosarajus_Algorithm/kosaraju.ts
#1180 
TypeScript...
1
Algorithms => Graph_Algorithms => Kosaraju's Algorithm => kosaraju.ts
> TypeScript Implementation of Kosarajus Algorithm

- CONTRIBUTORS.md
#1260 
C/C++
1
Data_Structures => Linked_List => Singly_Linked_List => Delete_Kth_Node_From_End => Delete_Kth_Node_From_End.cpp
> Added=>Data_Structures => Linked_List => Singly_Linked_List => Delete_Kth_Node_From_End => Delete_Kth_Node_From_End.cpp

- Data_Structures/Arrays/Merge-Sorted-Array.c
#1144 
C
1
algo_ds_101 => Data_Structures => Arrays => Merge-Sorted-Array.c
example :
> cfileadded

- Algorithms/Sorting_Algorithms/Bead_Sort/Bead_Sort.rb
#651
Ruby
1 
Algorithms => Sorting_Algorithms => Bead_Sort => Bead_Sort.rb
> Algorith => Sorting_Algorithm => Bead_Sort => Bead_Sort.rb

- Algorithms/Search_Algorithms/Fibonacci_Search/Fibonacci_search.php
- Algorithms/Tree_Algorithms/LCA/LCA.cs
- Data_Structures/Tree/Binary_Tree/Duplicate_values.cs
#1385
C#, PHP
2
Data_Structures => Tree => Binary_Tree => Duplicate_values =>Duplicate_values.cs
Algorithms=> Search_Algorithms=>Fibonacci_Search => fibonacci_search.php
Algorithms => Tree_Algorithms => LCA => LCA.cs
> Check if a Binary Tree has duplicate values C#

- Data_Structures/Linked_List/Singly_Linked_List/Remove_Duplicates_in_LL.py
#1410 
Python
1
Data_Structures => Linked_List => Singly_Linked_List => Remove_Duplicates_in_LL.py
> Added => Data_Structures => Linked_List => Singly_Linked_List => Remove_Duplicates_in_LL => Python

- Algorithms/Search_Algorithms/Exponential_Search/exponential_search.py
#1273
Python
1
Algorithms => Search_Algorithms => Exponential_Search => Exponential_Search.py
example :
> Add exponential serch Python.

- Data_Structures/Linked_List/Singly_Linked_List/MiddleElementLL.cpp
#1408 
/C++/
1/
Data_Structures => Linked_List => Singly_Linked_List=> MiddleElementLL.cpp
example :
> Added MiddleElementLL

- Data_Structures/Linked_List/Singly_Linked_List/Remove duplicates from linked_list.c
#1410
C
1
Data_Structures => Linked_List => Singly_Linked_List => Remove duplicates from linked_list.c
example :
> Create remove duplicates from linked_list.c

- Algorithms/Dynamic_Programming/Largest_Divisible_Subsets.py
#1425
Python
1
Algorithm => Dynamic_Programming => Largest_Divisible_Subsets.py
> Added => Algo => Dynamic_Programming => Largest_Divisible_Subset => Python

- Data_Structures/Linked_List/Singly_Linked_List/PalindromeLinkedList.js
Palindrome Linked List  #1407
JavaScript
1
main folder =>Data_Structures=>Linked_List=>Singly_Linked_List=>PalindromeLinkedList.js
> Added=>Data_Structures=>Linked_List=>Singly_Linked_List=>PalindromeLinkedList.js

- Algorithms/Sorting_Algorithms/Strand_Sort/strand_sort.c
#1353 
C
1
main folder => sub_folder => ... => ... => ... strand_sort.c
example :
Algorithm => sorting_algorithm=>strand_sort=>strand_sort.c
> Add strand_sort.c

- Algorithms/Dynamic_Programming/Largest Divisible Subset.cpp
#1425 
C++
1
Algorithm=>Dynamic_Programming=>Largest Divisible Subset.cpp
> Added =>Algo=>Dynamic_Programming=>Largest Divisible Subset.cpp

- Data_Structures/Tree/Binary_Tree/VerticalOrderTraversal.java
#1394 
Java
1
Data_Structures =>Tree => Binary_Tree => VerticalOrderTraversal.java
> Added Data_Structures=>Tree=>Binary_Tree => VerticalOrderTraversal.java

- Atm codes by python
I have created atm codes by python
#007
1/2/3/4/...
example :
> Create atm codes using python

- Data_Structures/Tree/Fibonacci_Heap/Fibonacci_Heap.c
#1371
C
1
Data_Structure=>Tree=>Fibonacci_Heap=>Fibonacci_Heap.c
> Fibonacci Heap

- Algorithms/Dynamic_Programming/Largest_Divisible_Subsets.java
#1425
Java
1
Algorithm => Dynamic_Programming => LargestDivisibleSubsets.java
> Added => Algo => Largest_Divisible_Subsets => Java

- Algorithms/Dynamic_Programming/Largest divisible subset in array/file.py
Fixes #1425
Python
1
Algorithms => Dynamic_Programming => Largest divisible subset in array => file.py
> Largest divisible subset in array

- Data_Structures/Linked_List/Singly_Linked_List/middle.ts
#1408
TypeScript
1
Data_Structures => Linked_List => Singly_Linked_List =>middle.ts
> 1408: Middle Element of LinkedList in TypeScript

- Maths_And_Stats/Algebra/Babylionian/Babylonian.java
#1374
Java
1
Maths_And_Stats =>Algebra=> Babylionian=>Babylionian.java
> Added => Maths_And_Stats => Algebra => Babylionian => Java

- Algorithms/Graph_Algorithms/Hopcroft_Karp/Hopcroft_Karp_algorithm.cpp
#1445 
C++
1
Algorithm=>Graph=>Hopcroft_Karp=>Hopcroft_Karp_algorithm.cpp
> Added Hopcroft_Karp_algorithm.cpp

- Algorithms/Search_Algorithms/Binary_Search/Rotated-Sorted-Array-Search.py
#1217 
Python
1
Algorithms => Search_Algorithms => Binary_Search => Rotated-Sorted-Array-Search.py
example :
> Added => Algorithms => Search_Algorithms => Binary_Search => Rotated-Sorted-Array-Search.py

- Algorithms/Dynamic_Programming/creating an string input function in C.c
- Algorithms/Search_Algorithms/Fibonacci_Search/Fibonacci_search_in_C.c
- Algorithms/Sorting_Algorithms/Bucket_Sort/bucketsortinC.c
- Data_Structures/Tree/Binary_Tree/Binary tree using C.c
#1477
C
1
Algorithms/Search_Algorithms/Fibonacci_Search/Fibonacci_search_in_C.c
> Fibonacci Search algorithm in C

- Data_Structures/Linked_List/Floyd_Cylce_detection/floyd_cycle_detection.swift
#1311
Swift
1
algo_ds_101 => Data_Structures => Linked_List => Floyd_Cylce_detection => floyd_cycle_detection.swift
> Added Floyd’s Cycle-Finding algorithm in Swift

- Algorithms/Sorting_Algorithms/Merge_Sort_on_Doubly_Linked_List/Mergesort_doubly.c
- Algorithms/Sorting_Algorithms/Merge_Sort_on_Doubly_Linked_List/Mergesort_doubly.cpp
- Algorithms/Sorting_Algorithms/Merge_Sort_on_Doubly_Linked_List/Mergesort_doubly.java
- Algorithms/Sorting_Algorithms/Merge_Sort_on_Doubly_Linked_List/Mergesort_doubly.py
added code in c,cpp,java & python
#007
1/2/3/4/...
example :
> added codes

- Data_Structures/Tree/Binary_Tree/Serialize/Serialize.py
Data_Structures => Tree => Binary_Tree => Serialize => Serialize.py
#1331
Python
1
Data_Structures => Tree => Binary_Tree => Serialize => Serialize.py
The program can't take dynamic input (I think it's going to make the code much more complicated).
There is still a hardcoded example.
> added Data_Structures => Tree => Binary_Tree => Serialize => Serialize.py

- Data_Structures/Graph/graph_implementation_in_C_bfs_dfs.c
- Maths_And_Stats/Algebra/Permutation_And_Combination/permutation_combination.cpp
#1359 
C
1
Data_Structures => Graph =>  graph_implementation_in_C_bfs_dfs.c
> Implementated Graph Data Structure in C using List and used BFS, DFS.

- Data_Structures/Graph/graph_implementation_in_C_bfs_dfs.c
- Maths_And_Stats/Algebra/Permutation_And_Combination/permutation_combination.cpp
#1483 
C++
1
Maths_And_Stats => Algebra => Permutation_And_Combination => permutation_combination.cpp
> My workspace2

- Algorithms/Dynamic_Programming/Branch_And_Bound/Knapsack_Branch_and_Bound.java
#1335
Java
1
Algorithm => Dynamic_Programming => Branch_And_Bound => Knapsack_Branch_and_Boound.java
> Added 0-1 Knapsack using Branch and Bound in Java

- Data_Structures/Maps_Hash_Dict/Group_Anagrams/group_anagrams.js
#1368 
Javascript
1
Data_Structures => Maps_Hash_Dict => Group_Anagrams => group_anagrams.js
> added group_anagrans.js

- Maths_And_Stats/Series/Sum_of_AP/Sum_of_AP.c
#1482 
C
1
Maths_And_Stats => Series => Sum_of_AP => Sum_of_AP.c
> Implemented the sum of arithematic series in C.

- Maths_And_Stats/Algebra/Permutation_And_Combination/permutation_combination.js
Javascript implementation of permutation and combination
to run use
**`node <filename> [option 1] [option 2] [option 3]`**
where
[option 1] is `P` or `C` where P is for permutation and C is for Combination
[option 2] is ( `N` ) where N is for nCr or nPr 
[option 3] is ( `R `) where R is for nCr or nPr 
#1483 
Javascript
1
Maths_And_Stats => Algebra => Permutation_And_Combination => permutation_combination.js
> Added=>Math=>Algebra=>Permutation and combination =>javascript

- Data_Structure/Queue/circular_queue_c
- Data_Structures/Linked_List/sparce matrix/sparce addition.cpp
> Added=>Data_atructure=>Queue=>circular queue=>C

- Data_Structures/Linked_List/sparce matrix/sparce addition.cpp
Addition of 2 sparce matrix
#007
1/2/3/4/...
example :
> Add sparce matrix implementation using linked list

- Data_Structures/Tree/Binary_Indexed_Tree/range_max_query_BIT.cpp
#1506 
C++
1
algo_ds_101 => Data_Structures => Tree => Binary_Indexed_Tree => range_max_query_BIT.cpp
> Range Max Query Using Binary Indexed Tree

- Maths_And_Stats/Algebra/Babylonian/Babylonian.js
#1374
JavaScript
1
main folder => Maths_And_Stats => Algebra => Babylonian => Babylonian.js
> Babylonian method for square root in javascript

- Algorithms/Sorting_Algorithms/Patience_Sort/Patience_sort.cpp
- Algorithms/Sorting_Algorithms/Patience_Sort/README.md
#1480 
C
2
Algorithms => Sorting_Algorithms => Patience_Sort => Patience_sort.cpp & README.md
> Patience Sort Algorithm

- Data_Structures/Tree/Binary_Indexed_Tree/Binary_Indexed_Tree.go
- Data_Structures/Tree/Binary_Indexed_Tree/Binary_Indexed_Tree.py
#1506
Python / Golang
2
Data_Structures => Tree => Binary_Indexed_Tree => Binary_Indexed_Tree.py
Data_Structures => Tree => Binary_Indexed_Tree => Binary_Indexed_Tree.go
> added Binary_Indexed_Tree.py and Binary_Indexed_Tree.go

- Algorithms/Dynamic_Programming/Tower_Of_Hanoi/tower_of_hanoi.go
#697
Go
1
Algorithm => Dynamic_Programming => Tower_Of_Hanoi => tower_of_hanoi.go
example :
> added tower_of_hanoi.go

- Algorithms/Dynamic_Programming/Largest_Divisible_Subset.js
#1425 
JavaScript
1
Algorithm => Dynamic_Programming => Largest_Divisible_Subsets.js
> Added => Algo => Largest_Divisible_Subsets => JavaScript

- Algorithms/Graph_Algorithms/Johnson_algorithm/Johnson_algorithm.cpp
#1448 
C++
1
Algorithm=>Graph=>Johnson_algorithm=>Johnson_algorithm.cpp
> Added Johnson_algorithm.cpp

- Algorithms/Sorting_Algorithms/Strand_Sort/strand_sort.ts
#1353
TypeScript
1
Algorithms => Sorting_Algorithms => strand_sort.ts
> Guilherme oliveira casagrande

- Data_Structures/Graph/GraphUsingList.kt
https://github.com/ahampriyanshu/algo_ds_101/issues/1523
Kotlin
1
Data_Structures/Graph/GraphUsingList.kt
> Create GraphUsingList Kotlin

- Algorithms/Dynamic_Programming/Water_Area/water_area.rb
#1246 
Ruby
1
Algorithms => Dynamic_Programming => Water_Area => water_area.rb
example :
> Adding water_area.rb

- Data_Structures/Linked_List/Singly_Linked_List/Remove duplicates in a Linked List.cpp
#1410
C++
1
algo_ds_101 => Data_Structures => Linked_list => Singly_Linked_List => Remove duplicates in a Linked List.cpp
example :
> cppfile added

- Data_Structures/Queue/circular_queue.cs
#1505 
C#
1
Data_Structure=>Queue=>circular_queue.cs
> added circular_queue.cs

- Algorithms/Sorting_Algorithms/Patience_Sort/PatienceSort.cs
#1480
C#
1
Folder``(Algorithms/Sorting_Algorithms/...)`` => Sub_Folder``(Patience_Sort)`` => ``PatienceSort.cs``
> Added => Algorithms => Sorting_Algorithms => Patience_Sort => PatienceSort.cs

- Algorithms/Graph_Algorithms/Bidirectional_search/Bidirectional_search.cpp
- Algorithms/Graph_Algorithms/Hungarian_algorithm/Hungarian_algorithm.cpp
#1446 
C++
2
Algo => Graph_Algo => Bidirectional_search => Bidirectional_search.cpp
> Algo => Graph_Algo => Bidirectional_search => Bidirectional_search.cpp

- Algorithms/String_Algorithms/LPS/longest_palindromic_substring.java
#1337 
Java
1
Algorithms => String_Algorithms => LPS => longest_palindromic_substring.java
> Algorithms => String_Algorithms => LPS => longest_palindromic_substring.java

- Data_Structures/Hash_Set/hash_set.cpp
#1520 
C++
1.
Data_Structures\Hash_Set\hash_set.cpp
> Added => Data_Structures => Hash_Set => hash_set.cpp

- Data_Structures/Tree/Binary_Indexed_Tree/BInary_Indexed_Tree.c
#1506 
C
1
algo_ds_101 => Data_Structures => Tree => Binary_Indexed_Tree => Binary_Indexed_Tree.c
> Added Fenwick_Tree in c

- Algorithms/Pattern_Searching/KMP_Algorithm/kmp.cpp
#1525 
C++
1
algo_ds_101\Algorithms\Pattern_Searching\KMP_Algorithm\kmp.cpp
> Added => Algo => Pattern_Searching => KMP_Algo

- Data_Structures/Tree/Binary_Indexed_Tree/Binary_Index_Tree.java
#1506
Java
1
algo_ds_101 => Data_Structures => Tree => Binary_Indexed_Tree => Binary_Index_Tree.java
> Added Binary_Index_Tree in Java

- Algorithms/Search_Algorithms/Trie_Search/Trie_Search.go
#1527 
Golang (Go)
1
Algorithms => Search_Algorithms => Trie_Search => Trie_Search.go
> Added Trie search implementation in Golang - #1527

- Data_Structures/Tree/Binary_Tree/VerticalOrderTraversal.py
#1394 
Python
1
algo_ds_101 => Data_Structures => Tree => VerticalOrderTraversal.py
> Added python solution for Vertical Order Traversal

- Algorithms/Graph_Algorithms/Bidirectional_search/Bidirectional_Search.py
#1446 
Python
1
Algorithms/Graph_Algorithms/Bidirectional_search/Bidirectional_Search.py
> Bidirectional_Search.py

- Algorithms/Pattern_Searching/KMP_Algorithm/KMP_Algorithm.php
#1525 
PHP
1
Algorithms => Pattern_Searching => KMP_Algorithm => KMP_Algorithm.php
> Added KMP_Algorithm.php

- Algorithms/Data_Structures/Array/Equal Subset Sum Partition/EqualSubsetSumPartition.java
#1552 
Java
1
Algorithm/Data_Structures/Array/Equal Subset Sum Partition/EqualSubsetSumPartition.java
> 1552 equal subset sum partition java

- Data_Structures/Maps_Hash_Dict/hashset.c
#1520
C
1
Data_Structures/Maps_Has_Dict/hashset.c
> Added HashSet in C

- Data_Structures/Arrays/README.md
#Issue_Number
1/2/3/4/...
Folder``(Algorithm/Data_Structures/...)`` => Sub_Folder``(Sorting_Algo/Trees/Algebra)`` => ... => ``File.extension``
> fixing jekyl error 2

- Algorithms/Cryptography/AES_Cipher/AES_Cipher.py
- Algorithms/Cryptography/AES_Cipher/README.md
#1582 
Python
2
``Algorithm`` => ``Cryptography`` => ``AES_Cipher`` => ``AES_Cipher.py``
> AES Encryption Decryption Algorithm

- Data-Structures/Queue/Deque/Deque.js
#Issue_Number: #1587
JavaScript
1
``Data-Structures => Queue => Deque => Deque.js``
- [ x ] Input has been taken dynamically.
- [ x ] I've referred the correct issue number.
- [ x ] Comments have been added
- [ x ] I've  synced-up my forked repo.
- [ x ] Ain't pushing from the main branch.
- [ x ] I've followed the [naming convention](https://github.com/ahampriyanshu/algo_ds_101/blob/main/CONTRIBUTING.md)
> Added => Data-Structures => Queue => Deque => JS

- Data-Structures/Array/Array.cpp
#Issue_Number   #1591
C++
1
Data-Structures => Array => Array.cpp
> Added=>Data-Structures=>Array=>CPP

- Data-Structures/Queue/Priority-Queue/priorityQueue.cpp
#Issue_Number #1590
C++
1
Added=>Data-Structures => Queue => Priority-Queue => priorityQueue.cpp
> Added=>Data-Structures => Queue => Priority-Queue =>priorityQueue.cpp

- Collection/ArrayList/ArrayList .java
Implemented the ArrayList basic methods
#1592
Java
1
``Collection=>ArrayList=>ArrayList.java``
> Collection=>ArrayList=>ArrayList.java

- Data-Structures/Array/Array.py
#1591
Python
1..
Folder => Sub_Folder => ... => File.extension
``Data-Structures => Array => Array.py``
> Added=>Data-Structures=>Array=>Python

- Collection/Vector/Vector.java
#1602
Java
1.
Java => Collection => Vector => Vector.java
> Java => Collection => Vector => Vector.java

- Collection/Queue/Queue.java
#1600 
Java
1
Collection => Queue => Queue.java
- [x ] Input has been taken dynamically.
- [x ] Comments have been added
- [ x] I've  synced-up my forked repo.
- [ x] Ain't pushing from the main branch.
- [x ] I've followed the [naming convention](https://github.com/ahampriyanshu/algo_ds_101/blob/main/CONTRIBUTING.md)
> Created a queue sample in java

- Data-Structures/Array/Array.ts
#1591 
TypeScript
1
`Data-Structures => Array => Array.ts`
> Added=>Data-Structures=>Array=>TypeScript

- Data-Structures/Array/Stack_Using_Array/Stack_Using_Array.java
#1608 
Java
1
Data Structures => Array => Stack Using Array => Java
> Added => Data Structures => Array => Stack Using Array => Java

- Collection/Stack/StackCollection.java
#1601
Java
1
Collection => Stack =>  StackCollection.java
> Added=> Collection => Stack => Java

- Data-Structures/Array/Array.php
#1591
Php
1
Data-Structures => Array => Array.php
> Data-Structures => Array => Array.php

- Data-Structures/Array/Array.php
- Data-Structures/Queue/Priority-Queue/PriorityQueue.php
- Data-Structures/Stack/StackUsingArray.php
#1590
PHP
1
Data-Structures => Queue => Priority-Queue => PriorityQueue.php
> Data-Structures => Queue => Priority-Queue => PriorityQueue.php

- Data-Structures/Array/Array.php
- Data-Structures/Stack/StackUsingArray.php
#1608
PHP
1
Data-Structures => Stack => StackUsingArray.php
> Data-Structures => Stack => StackUsingArray.php

- Data-Structures/Array/Array.c
#1591
C
1
Data-Structures => Array => Array.c
> Added=>Data-Structures=>Array=>C

- Data-Structures/Stack/StackUsingLL.js
#1609 
JavaScript
1
Data-Structures=> Stack => StackUsingLL.js
- [x ] Input has been taken dynamically.
- [ x] Comments have been added
- [ x] I've  synced-up my forked repo.
- [ x] Ain't pushing from the main branch.
- [ x] I've followed the [naming convention](https://github.com/ahampriyanshu/algo_ds_101/blob/main/CONTRIBUTING.md)
> Added=>Data-Structures=>Stack=>StackUsingLL.js

- Data-Structures/Stack/stackUsingLinkedList.c
C
1
Data-Structures=> Stack => stackUsingLL.c
> Added=>Data-Structure=>Stack=>StackUsingLL.c

- Deque.java
#1595
Java
1
Collection => Deque => Deque.java
> Added => Collection => Deque => Deque.java

- Collection/PriorityQueue/PriorityQueue.java
#1599
Java
1
Collection => PriorityQueue => PriorityQueue.java
> Added => Collection => PriorityQueue => PriorityQueue.java

- Data-Structures/Array/Array.js
#1591
JavaScript.
1
Data-Structure => Array => Array.js
> Added => Data-Structure => Array => JavaScript

- Collection/HashMap/HashMap.java
#1597
Java
1
Collection => HashMap => HashMap.java
> Added => Collection => HashMap => HashMap.java

- Data-Structures/Queue/Deque/Deque.java
#1587
Java
1
Data-Structures => Queue => Deque => Deque.java
> Created Deque in java

- Collection/HashMap/HashMapJava.java
#1597
Java 
1
collection => hashmap => hashmapjava.java
- [ x] **I've followed the [contributing guidelines](https://github.com/ahampriyanshu/algo_ds_101/blob/main/CONTRIBUTING.md)**
- [ x] I've synced-up my forked repo.
- [ x] Ain't pushing from the main branch.
- [ x] The content added isn't directly copied from any sources like gfg, tutorialpoint, etc.
- [ x] Input has been taken dynamically.
- [ x] Comments have been added
- [ x] I've  synced-up my forked repo.
- [ x] Ain't pushing from the main branch.
> added hashmap

- Algorithms/Hashing/Open Addressing/linearProbingHashTable.cpp
- Algorithms/Hashing/Open Addressing/linear_probing_hash_table.cpp
#1648
C++
1
Algorithms => Hashing => Open Addressing => linearProbingHashTable.cpp
> Linear probing

- Collection/HashSet/HashSet.java
#1598
Java
1
Collection => HashSet => HashSet.java
> Added => Collection => HashSet => HashSet.java

- Algorithms/Hashing/Open Addressing/quadraticProbingHashTable.cpp
#1654
C++
1
Algorithms => Hashing => Open Addressing => quadraticProbingHashingTable.cpp
> added quadratic probing hashing algorithm; closes #1654

- Algorithms/Hashing/Open Addressing/linearProbingHashTable.cpp
- Algorithms/Hashing/Open Addressing/quadraticProbingHashTable.cpp
#1669
C++
1
Algorithm => Hashing => Open Addressing => linearProbingHashTable.cpp
> fixed linear probing algorithm; closes #1669

- Algorithms/Hashing/Open Addressing/doubleHashHashingTable.cpp
#1666
C++
1
Algorithm => Hashing => Open Addressing => doubleHashHashingTable.cpp
> added double hashing algorithm; closes #1666

- Maths/Number-Theory/Smith_number/smith_numbers_till_n.cpp
#1661
C++
1
Maths=>Number-Theory =>Smith_number =>smith_numbers_till_n.cpp
- [x ] **I've followed the [contributing guidelines](https://github.com/ahampriyanshu/algo_ds_101/blob/main/CONTRIBUTING.md)**
- [ x] The content added isn't directly copied from any sources like gfg, tutorialpoint, etc.
- [x ] Input has been taken dynamically.
- [x ] Comments have been added
- [x ] I've  synced-up my forked repo.
- [x ] Ain't pushing from the main branch.
> smith number done in cpp

- Data-Structures/Tree/Binary-Search-Tree/Binary_Search_Tree.cpp
Tried to include all possible operations, Traversal of BST
#Issue_Number
C/C++/Python/Java ...
1/2/3/4/...
Folder => Sub_Folder => ... => File.extension
> All possible operations of BST

- Algorithms/Searching/Binary_Search/search_in_2d_matrix.cpp
#1689
C++
1
Algorithms => Searching => Binary Search => search_in_2d_matrix.cpp
> Added => Algorithms => Searching => Binary Search => search_in_2d_matrix.cpp

- Algorithms/Hashing/Chaining/chainingHashing.cpp
#1673
C++
1
Algorithm => Hashing => Chaining => chainingHashing.cpp
> added chaining algorithm; closes #1673

- Algorithms/Sorting/Merge_Sort/Application of Merge Sort/Count_Inversions.c
- Algorithms/Sorting/Merge_Sort/Application of Merge Sort/Count_Inversions.cpp
#1687 
C/C++
2
Algorithms => Sorting => Merge Sort => Application of Merge Sort => Count_Inversions.cpp
Algorithms => Sorting => Merge Sort => Application of Merge Sort => Count_Inversions.c
> Added => Algorithms => Sorting => Merge Sort => Application of Merge Sort => Count_Inversions.cpp and Count_Inversions.c

- Algorithms/Array-Algorithm/rearrange-high-low.java
#1678
Java
1
Algorithms=>Array-Algorithm
> Added=>Algorithms=>Array-Algorithm

- Algorithms/Array-Algorithm/Rearrange-High-Low.js
#1678 
Javascript
1
Algorithms=>Array-Algorithm => Rearrange-High-Low.js
> Added=>Algorithms=>Array-Algorithm => Rearrange-High-Low.js

- Data-Structures/Array/array_menudriven.cpp
#1591 
c++
1
/algo_ds_101/Data-Structures/Array
all the function operation which can be performed on an array is implemented by me.
like :- push , binary search, linear search, merging , intersection, sum of elements etc.
> array is implemented in menu driven format

- Data-Structures/Tree/Binary-Search-Tree/Binary_Search_Tree_operations.cpp
changes made
#Issue_Number
C++
1
algo_ds_101 => Data-Structures => Tree => Binary-Search-Tree => Binary_Search_Tree_operations.cpp
- [x Ain't pushing from the main branch.
> Included all possible operations on BST

- Algorithms/Searching/Binary_Search/matrix_binary_search.py
#1689 
Python
1
Algorithms => Searching => Binary Search => matrix_binary_search.py
> Implementation of Binary Search in row ordered Matrix in Python

- Algorithms/DSU/dsu.py
#1686
Python
1
Algorithms=>Graph-Algorithms=>DSU=>dsu.py
> Added Algorithms=>Graph-Algorithms=>DSU python

- Algorithms/Tree-Algorithm/GenericTreeImplementation/GenericTree.cpp
> Generic Tree added in cpp

- Data-Structures/Tree/Trie/Trie.java
- Data-Structures/Tree/Trie/Trie.js
- Data-Structures/Tree/Trie/Trie.ts
#1631 
Java, JavaScript & TypeScript
3
Added => Data Structures => Trie => Trie.java (Java)
Added => Data Structures => Trie => Trie.js (JavaScript)
Added => Data Structures => Trie => Trie.ts (TypeScript)
> Trie Implementation: Java, Javascript, Typescript

- Algorithms/String-Algorithm/suffix_array.cpp
C++
1
Algorithms=>String-Algorithm=>suffix_array.cpp
> added suffix array

- Algorithms/Graph-Algorithms/DSU/dsu.cpp
- Algorithms/Graph-Algorithms/DSU/dsu.py
Sorry for this, but in the previous PR I accidentally pushed python implementation to the folder where only categories live. Moved python implementation to Graph-Algorithms and added C++ one
#1686 
C++/Python
2
Algorithms=>Graph-Algorithms=>DSU=>dsu.py
> Added Algorithms=>Graph-Algorithms=>DSU C++

- Algorithms/String-Algorithm/Isomorphic-String.java
#1682
Algorithms=>String-Algorithm
> Added=>Algorithms=>String-Algorithm

- Algorithms/String-Algorithm/Isomorphic.js
#1682 
Algorithms/String-Algorithm/Isomorphic.js
- [ YES] **I've followed the [contributing guidelines](https://github.com/ahampriyanshu/algo_ds_101/blob/main/CONTRIBUTING.md)**
- [ YES] The content added isn't directly copied from any sources like gfg, tutorialpoint, etc.
- [ NO] Input has been taken dynamically.
- [ YES] I've referred the correct issue number.
- [ YES] Comments have been added
- [ YES] I've  synced-up my forked repo.
- [ YES] Ain't pushing from the main branch.
> Added => Isomorphic.js

- Algorithms/Recursion/jophesus.cpp
#1764
Algorithms => Recursion => ... => josephus.cpp
> Added Josephus Problem

- Data-Structures/Array/Array.go
#1591
Go
1
DataStructure => Array => array.go.
> Added => data structure => array => go

- Data-Structures/Queue/Circular-Queue/circular_queue_LL.c
- Data-Structures/Stack/stackusingLL.c
#Issue_Number 1609
Folder => Sub-Folder => ... => File.extension
Data Structures=>Stack=>stackusingll.c
- [* ] **I've followed the [contributing guidelines](https://github.com/ahampriyanshu/algo_ds_101/blob/main/CONTRIBUTING.md)**
- [* ] The content added isn't directly copied from any sources like gfg, tutorialpoint, etc.
- [ *] Input has been taken dynamically.
- [* ] I've referred to the correct issue number.
- [* ] Comments have been added
- [* ] I've synced up my forked repo.
- [* ] Ain't pushing from the main branch.
> Implemented stack using Linked List in C

- Data-Structures/Queue/QueueUsingStacks.cpp
#Issue_Number
C++ 
1 
main/Data-Structures/Queue/QueueUsingStacks.cpp
> Added Queue Using Stacks

- Algorithms/Tree-Algorithm/Binary_Lifting/Binary-Lifting.cpp
#1733 
Algorithms=>Tree-Algorithm=>Binary_Lifting=>Binary-Lifting.cpp
> Added Binary Lifting For Finding LCA on Trees in C++

- Algorithms/Recursion/Josephus.c
- Algorithms/Tree-Algorithm/LCA/LCA.js
#1733 #1764
Algorithms=>Tree-Algorithm=>Binary_Lifting=>LCA.js
Algorithm => Recursion => Josephus.c
> LCA in JavaScript and Josephus in c

- Algorithms/Tree_Algorithms/Binary_Lifting/Binary Lifting.py
#1733
Algorithms=>Tree-Algorithm=>Binary_Lifting.py
> [#1733]- Added Binary Lifting For LCA on Trees in python

- Algorithms/Array-Algorithm/merging_2_arrays.c
i make more simple using the algo used above with comments to make it easy understable for any basic C programmer
#Issue_Number
Folder => Sub-Folder => ... => File.extension
> merge2array.c

- lcs.cpp
> Longest Common Subsequence

- Algorithms/Array-Algorithm/Rearrange-High-Low.kt
#Issue_Number
Folder => Sub-Folder => ... => File.extension
> Added=>Algorithms=>Array-Algorithm => Rearrange-High-Low.kt

- Data-Structures/Queue/Circular-Queue/circular_queue_array_implementation.c
#Issue_Number
Issue Number 1588
Folder => Sub-Folder => ... => File.extension
Data-Structures/Queue/Circular-Queue/circular_queue_array_implementation.c
- [* ] **I've followed the [contributing guidelines](https://github.com/ahampriyanshu/algo_ds_101/blob/main/CONTRIBUTING.md)**
- [* ] The content added isn't directly copied from any sources like gfg, tutorialpoint, etc.
- [* ] Input has been taken dynamically.
- [* ] I've referred the correct issue number.
- [ *] Comments have been added
- [* ] I've  synced-up my forked repo.
- [* ] Ain't pushing from the main branch.
> added circular queue implementation using arrays in C

- Algorithms/Array-Algorithm/twoSum.cpp
- Algorithms/Array-Algorithm/twoSum.kt
- Algorithms/Searching/Binary_Search/binarySearch.kt
#1789 
Algorithms => Array-Algorithm => ... => twoSum.kt
> Added => twoSum.kt

- Algorithms/Array-Algorithm/twoSum.cpp
- Algorithms/Array-Algorithm/twoSum.kt
- Algorithms/Searching/Binary_Search/binarySearch.kt
Algorithms => Searching => ... => binarySearch.kt
> Added => binarySearch.kt

- Algorithms/Searching/Binary_Search/Binary-Search.java
#1754 
Algorithms => Searching => Binary_Search => Binary-Search.java
> Added => Binary Search in java

- Data-Structures/Tree/Threaded Binary Tree/Threaded_Binary_Tree.cpp
#Issue_Number
algo_ds_101/Data-Structures/Tree/Threaded Binary Tree/Threaded_Binary_Tree.cpp
> Added code for Threaded binary Tree

- Data-Structures/Tree/Expression Tree/Expression_Tree.cpp
#Issue_Number
algo_ds_101/Data-Structures/Tree/Expression Tree/Expression_Tree.cpp
> Added Expression Tree code

- Data-Structures/Disjoint Set Union/DisjointSet.java
#1784
Data-Structures => Disjoint Set Union => DisjointSet.java
> Added : DisjointSet.java

- Data-Structures/Stack/Infix_to_prefix_postfix.cpp
converting infix expression to prefix and postfix using stack
#Issue_Number
algo_ds_101/Data-Structures/Stack/Infix_to_prefix_postfix.cpp
> infix to prefix and postfix

- Algorithms/Tree-Algorithm/level_traversing/level_traversing.php
#1655 
Algorithm ==> Tree Algorithm ==> level_traversing.php
- [yes ] **I've followed the [contributing guidelines](https://github.com/ahampriyanshu/algo_ds_101/blob/main/CONTRIBUTING.md)**
- [yes ] The content added isn't directly copied from any sources like gfg, tutorialpoint, etc.
- [yes ] I've referred the correct issue number.
- [yes ] Comments have been added
- [yes ] I've  synced-up my forked repo.
- [yes ] Ain't pushing from the main branch.
> Create BST Level Order Traversal in PHP

- Maths/Number-Theory/Smith_number/SmithNumber.py
#1661 
Maths => Number Theory => Smith Number => SmithNumber.py
- [YES] **I've followed the [contributing guidelines](https://github.com/ahampriyanshu/algo_ds_101/blob/main/CONTRIBUTING.md)**
- [YES ] The content added isn't directly copied from any sources like gfg, tutorialpoint, etc.
- [YES] Input has been taken dynamically.
- [YES] I've referred the correct issue number.
- [YES ] Comments have been added
- [YES] I've  synced-up my forked repo.
- [YES] Ain't pushing from the main branch.
> SmithNumber

- Maths/Number-Theory/Tribonacci_Number/nthTribonacci.kt
#1807 
Maths => Number Theory => Tribonacc_number => nthTribonacci.kt
> Added => Tribonacci_Number => nthTribonacci.kt

- Algorithms/Two-Pointer/TrappingWater/TrappingWater.cpp
#1812 
Algorithm => Two-Pointer => TrappingWater => TrappingWater.cpp
- [YES ] **I've followed the [contributing guidelines](https://github.com/ahampriyanshu/algo_ds_101/blob/main/CONTRIBUTING.md)**
- [YES ] The content added isn't directly copied from any sources like gfg, tutorialpoint, etc.
- [YES] Input has been taken dynamically.
- [YES ] I've referred the correct issue number.
- [YES ] Comments have been added
- [YES ] I've  synced-up my forked repo.
- [YES ] Ain't pushing from the main branch.
> Added TrappingWater.cpp issue #1812

- Algorithms/Sorting/Heap_Sort/Max_heap_sort.cpp
#Issue_Number
algo_ds_101/Algorithms/Sorting/Heap_Sort/Max_heap_sort.cpp
> Added efficient code max heap sort

- Algorithms/String-Algorithm/String-Searching/RabinKarpAlgo.java
- Algorithms/Two-Pointer/TrappingWater/TrappingWater.cpp
#1838
Algorithms => String-Algorithm =>String-Searching
> Pattern-Searching (Rabin-Karp Algorithm)

- Algorithms/Searching/Binary_Search/search_in_2D_matrix.java
- Data-Structures/Stack/StackUsingLL.java
Algorithm =>Searching =>Binary Search=>search_in_2D_matrix.java
**Kindly review my PR #1689**
> Search in a sorted 2-D matrix (BINARY SEARCH) (#1689) java added

- Algorithms/Array-Algorithm/merge_without_extraspace.cpp
#Issue_Number
algo_ds_101/Algorithms/Array-Algorithm/merge_without_extraspace.cpp
> Added efficient code foe merge without extra space

- Algorithms/Array-Algorithm/findpos.py
#997
Python
1
algo_ds_101/Algorithms/Array-Algorithm/findpos/.py
> Saadfareed

- Algorithms/Graph-Algorithm/Prim's_MST/Prims_MST.java
I used PriorityQueue here for reducing tc
#1823
algo_ds_101=>Algorithms=>Graph-Algorithms=>Prim's_MST
> Added Prim's_MST algorithm
